### ISSUE TITLE
Problem with running unsupervised scikit learn agglomerative clustering

### ISSUE THREAD

**Issue by sguptabsp** [vaexio/vaex#1004]
Hi, 

Can you please help me with the issue below:

I want to use agglomerative clustring in my project and I am having an error like this ..rawdf is a minmax scaled df looks correct.  But it gives me error like this. Am i doing anything wrong?. Please suggest. 

# from sklearn.cluster import AgglomerativeClustering
n_clusters = 5
cluster1 = AgglomerativeClustering(n_clusters=n_clusters, affinity='euclidean', linkage='ward')
features=['minmax_scaled_relative_elev_min',
 'minmax_scaled_slope',
 'minmax_scaled_swi',
 'minmax_scaled_om',
 'minmax_scaled_cec',
 'minmax_scaled_nlpbl']   
model = Predictor(model=AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward'),features=features,prediction_name='pred')
model.fit(raw_df,progress=True)
Z= model.transform(raw_df)

Gives me following error:
Traceback (most recent call last):

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))

KeyError: "Unknown variables or column: ''"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 1996, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)

  File "<string>", line unknown
    
    ^
SyntaxError: unexpected EOF while parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))

KeyError: "Unknown variables or column: ''"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-283-ad6fb2cb4c83>", line 16, in <module>
    model.fit(raw_df,progress=True)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\ml\sklearn.py", line 96, in fit
    y = df.evaluate(self.target)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 5352, in _evaluate_implementation
    dtypes[expression] = df.data_type(expression, internal=False)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 1998, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)

  File "C:\Users\ShrutiGupta\anaconda3\envs\myana37\lib\site-packages\vaex\scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)

  File "<string>", line unknown
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by JovanVeljanoski** [comment]
Hi @sguptabsp 

If you read the docstring of `veax.ml.sklearn.Predictor`, you will find that it is meant to wrap a sklearn `Estimator` class objects (or what we sometimes call "predictors", i.e. classes that implement the `.predict` method).

The clustering algorithms in scikit-learn do not really follow this pattern. They are, however, similar enough to the Estimators/Predictors that you can use the `veax.ml.sklearn.Predictor` wrapper class with them.  The reason why your exception happens, is that `veax.ml.sklearn.Predictor` expects a kwarg `target`, that is by default set to `''` (empty string), which expects you to provide a target (for supervised learning). 

The way to go around this is to simply pass any valid column name to the `target` kwarg from your input/training dataframe to `veax.ml.sklearn.Predictor`. This is equivalent to the `y` argument in the `.fit()` methods in sklearn, and for the clustering algorithms it is ignored (it is there mostly for uniformity of the API I think). 

Some notes on this:
 - Note that using any scikit-learn class/algorithm with vaex for not out of core, meaning that you are materializing your data (i.e. putting it all on memory) and then calling the scikit-learn algorithm normally as if you were using numpy. `veax.ml.sklearn.Predictor` is just a wrapper, we do not re implement anything in scikit-learn. So be mindful of memory use.
- I do not see a great benefit to using `veax.ml.sklearn.Predictor` with a clustering algorithm that does not implement the `.predict` method like in your case. The main point of `veax.ml.sklearn.Predictor` is to provide serialization for the implicit/automatic pipeline by vaex, but that assumes a transformation/prediction can be done on an unseen dataset (with `.predict` for example). If in doubt, you an always use `df[features].values` and pass that to `.fit` of a clustering algorithm.
- If you continue using `veax.ml.sklearn.Predictor` with a clustering algorithm (nothing wrong with that btw!), note that you can access the scikit-learn class by (using your notation): `model.model`, to get access to attributes like `labels_` or others that you may be interested in.

I hope this helps.

**Comment by maartenbreddels** [comment]
Should we change the default argument of target? This leads to a very bad
user experience? Maybe open a separate issue for this, or maybe you can do
a pr Jovan if this is straightforward.

(from mobile phone)
