### ISSUE TITLE
ZeroDivisionError on joining dataframes

### ISSUE THREAD

**Issue by sheetalakadam** [vaexio/vaex#1031]
**Description**
I get the **ZeroDivisionError** on doing a left join on the data frames. I got the same error when performing inner join too in the past. In the past I have observed the following when doing inner joins.
1. the error occurs when there is no match and the resulting data frame is empty- can be handled in a try catch
2. the error occurs when the size of left dataframe is smaller- can be handled by switching the df positions.

This is the left join code I am using :

`df1 = (df1.join(df2,on='id', lsuffix='_incl', rsuffix='_excl', allow_duplication=True))`

But as I am doing a left join this time I cannot switch the df positions. There are no virtual columns in both the dataframes

To give you some context regarding the use case, I want to do a set difference kind of operation on the dataframes. For example, if the 2 dataframes are df1 and df2- get all rows that are there in df1 but are not there in df2.  I was trying to do this using left join and isnan() filtering.

Since the left join operation is not woking I am trying the following to methods:
1. Use isin on the joining key ` df1[~df1.unq_member_id.isin(df2['id'])]` - this is giving error **len() of unsized object**
2. concat the 2 dataframes->group by with the joining key->filter out the one with count==1

Both my dataframes are quite big. Which approach do you think is best for this kind of problem?

**Software information**
 - Vaex version : 3
 - Vaex was installed via: pip 
 - OS: Ubuntu 18.04.3 LTS

**Comment by JovanVeljanoski** [comment]
Hi, 

Can you maybe try to isolate the issue, maybe send us an reproducible example? I understand the data is big, but issues like these are typically reproducible with small samples if one chooses the right stuff that cause the problem..

Things to try are including / excluding, nans or missing values, inspect the dtypes, along those lines..

**Comment by sheetalakadam** [comment]
I am not able to reproduce the error with dummy data. I am going to try to reproduce the error with some public datasets. Meanwhile, I ran the same code on a different machine  (below are the specs) on which I did not get the error with the same code and same data. But now for some of the cases, I get: 
 `ValueError: zero-size array to reduction operation minimum which has no identity`

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/vaex/execution.py", line 157, in execute_async
    cancel=lambda: self._cancel(run), unpack=True, run=run):
  File "/opt/conda/lib/python3.7/site-packages/vaex/multithreading.py", line 74, in map_async
    yield await value
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.7/site-packages/vaex/multithreading.py", line 64, in <lambda>
    iterator = [loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in values]
  File "/opt/conda/lib/python3.7/site-packages/vaex/multithreading.py", line 54, in wrapped
    callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/opt/conda/lib/python3.7/site-packages/vaex/execution.py", line 206, in process_part
    block_dict = {expression: block_scope.evaluate(expression) for expression in run.expressions}
  File "/opt/conda/lib/python3.7/site-packages/vaex/execution.py", line 206, in <dictcomp>
    block_dict = {expression: block_scope.evaluate(expression) for expression in run.expressions}
  File "/opt/conda/lib/python3.7/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/opt/conda/lib/python3.7/site-packages/vaex/scopes.py", line 128, in __getitem__
    self.values[variable] = self.df.columns[variable][offset+self.i1:offset+self.i2]
  File "/opt/conda/lib/python3.7/site-packages/vaex/column.py", line 149, in __getitem__
    i1, i2 = np.min(unmasked_indices), np.max(unmasked_indices)
  File "<__array_function__ internals>", line 6, in amin
  File "/home/s1967611/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2831, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/home/s1967611/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

New Machine Information

 Debian GNU/Linux 9.13 (stretch) (GNU/Linux 4.9.0-13-amd64 x86_64\n)


This might be related to https://github.com/vaexio/vaex/issues/1001
