### ISSUE TITLE
Issue with opening a hdf5 file from GCS

### ISSUE THREAD

**Issue by xinnyuann** [vaexio/vaex#1033]
I'm trying to open hdf5 files from GCS, so initially just wanted to open the files you listed as the example here: https://vaex.readthedocs.io/en/latest/api.html

```
df = vaex.open('gs://vaex-data/airlines/us_airline_data_1988_2019.hdf5?token=anon')
df = vaex.open('gs://vaex-data/testing/xys.hdf5?token=anon&cache=False')
```

Both of them gave me the error below:

```
ERROR:MainThread:vaex:error opening 'gs://vaex-data/airlines/us_airline_data_1988_2019.hdf5?token=anon'
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-29-b41f5d7b0b89> in <module>
----> 1 df = vaex.open("gs://vaex-data/airlines/us_airline_data_1988_2019.hdf5?token=anon")

/opt/conda/lib/python3.7/site-packages/vaex/__init__.py in open(path, convert, shuffle, copy_index, *args, **kwargs)
    180             ds = None
    181             if len(filenames) == 0:
--> 182                 raise IOError('Could not open file: {}, it does not exist'.format(path))
    183             filename_hdf5 = _convert_name(filenames, shuffle=shuffle)
    184             filename_hdf5_noshuffle = _convert_name(filenames, shuffle=False)

OSError: Could not open file: gs://vaex-data/airlines/us_airline_data_1988_2019.hdf5?token=anon, it does not exist
```

**Software information**
Vaex version : 3
Vaex was installed via: pip
OS: Ubuntu 18.04.3 LTS

**Comment by JovanVeljanoski** [comment]
Hi @xinnyuann 

Thanks for reaching out. 
Actually, this is a feature was not available in vaex 3. If you can to try it out, you can install the latest alpha:
`pip install vaex-core=4.0.0a4`

We are getting closer to the release of the next major version of vaex, so part of the docs are already updated with what is available in the alpha (but not everything - we understand that this might be confusing). 

Try it out with the alpha if you can, it should work!

Cheers, 
J.

**Comment by xinnyuann** [comment]
Thanks for your help Jovan. This is the most exciting news for me today!!!  Looking forward to the next release.
I'm able to open the h5 files after install the alpha version but not able to do **df.describe()**. Not sure if the error message would be helpful, but please ignore it if you're already aware of this:

When running **df.describe()**
```
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "/home/jupyter/vaex/packages/vaex-core/vaex/execution.py", line 168, in execute_async
    cancel=lambda: self._cancel(run), unpack=True, run=run):
  File "/home/jupyter/vaex/packages/vaex-core/vaex/multithreading.py", line 68, in map_async
    value = await value
  File "/opt/conda/lib/python3.7/asyncio/futures.py", line 263, in __await__
    yield self  # This tells Task to wait for completion.
  File "/opt/conda/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup
    future.result()
  File "/opt/conda/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/multithreading.py", line 64, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/multithreading.py", line 56, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/execution.py", line 232, in process_part
    task._parts[thread_index].process(thread_index, i1, i2, filter_mask, *blocks)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/cpu.py", line 338, in process
    blocks = [array_types.to_numpy(block, strict=False) for block in blocks]
  File "/home/jupyter/vaex/packages/vaex-core/vaex/cpu.py", line 338, in <listcomp>
    blocks = [array_types.to_numpy(block, strict=False) for block in blocks]
  File "/home/jupyter/vaex/packages/vaex-core/vaex/array_types.py", line 89, in to_numpy
    return x.to_arrow()
  File "/home/jupyter/vaex/packages/vaex-core/vaex/column.py", line 25, in to_arrow
    return pa.array(self, type=type)
  File "pyarrow/array.pxi", line 195, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 107, in pyarrow.lib._handle_arrow_array_protocol
  File "/home/jupyter/vaex/packages/vaex-core/vaex/column.py", line 531, in __arrow_array__
    buffers[0] = pa.py_buffer(self.null_bitmap.copy())
AttributeError: 'ColumnFile' object has no attribute 'copy'
ERROR:MainThread:asyncio:Future exception was never retrieved
future: <Future finished exception=AttributeError("'ColumnFile' object has no attribute 'copy'")>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/multithreading.py", line 64, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/multithreading.py", line 56, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/execution.py", line 232, in process_part
    task._parts[thread_index].process(thread_index, i1, i2, filter_mask, *blocks)
  File "/home/jupyter/vaex/packages/vaex-core/vaex/cpu.py", line 338, in process
    blocks = [array_types.to_numpy(block, strict=False) for block in blocks]
  File "/home/jupyter/vaex/packages/vaex-core/vaex/cpu.py", line 338, in <listcomp>
    blocks = [array_types.to_numpy(block, strict=False) for block in blocks]
  File "/home/jupyter/vaex/packages/vaex-core/vaex/array_types.py", line 89, in to_numpy
    return x.to_arrow()
  File "/home/jupyter/vaex/packages/vaex-core/vaex/column.py", line 25, in to_arrow
    return pa.array(self, type=type)
  File "pyarrow/array.pxi", line 195, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 107, in pyarrow.lib._handle_arrow_array_protocol
  File "/home/jupyter/vaex/packages/vaex-core/vaex/column.py", line 531, in __arrow_array__
    buffers[0] = pa.py_buffer(self.null_bitmap.copy())
AttributeError: 'ColumnFile' object has no attribute 'copy'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed eval> in <module>

~/vaex/packages/vaex-core/vaex/dataframe.py in describe(self, strings, virtual, selection)
   3530                 if data_type in array_types.string_types:
   3531                     count = self.count(feature, selection=selection, delay=True)
-> 3532                     self.execute()
   3533                     count = count.get()
   3534                     columns[feature] = ((data_type, count, N-count, '--', '--', '--', '--'))

~/vaex/packages/vaex-core/vaex/dataframe.py in execute(self)
    342         '''Execute all delayed jobs.'''
    343         from .asyncio import just_run
--> 344         just_run(self.execute_async())
    345 
    346     async def execute_async(self):

~/vaex/packages/vaex-core/vaex/asyncio.py in just_run(coro)
     33             nest_asyncio.apply()
     34             check_patch_tornado()
---> 35         return loop.run_until_complete(coro)
     36     finally:
     37         if not had_loop:  # remove loop if we did not have one

/opt/conda/lib/python3.7/site-packages/nest_asyncio.py in run_until_complete(self, future)
     93                 raise RuntimeError(
     94                     'Event loop stopped before Future completed.')
---> 95             return f.result()
     96         finally:
     97             events._set_running_loop(old_running_loop)

/opt/conda/lib/python3.7/asyncio/futures.py in result(self)
    179         self.__log_traceback = False
    180         if self._exception is not None:
--> 181             raise self._exception
    182         return self._result
    183 

/opt/conda/lib/python3.7/asyncio/tasks.py in __step(***failed resolving arguments***)
    249                 result = coro.send(None)
    250             else:
--> 251                 result = coro.throw(exc)
    252         except StopIteration as exc:
    253             if self._must_cancel:

~/vaex/packages/vaex-core/vaex/dataframe.py in execute_async(self)
    347         '''Async version of execute'''
    348         # no need to clear _task_aggs anymore, since they will be removed for the executors' task list
--> 349         await self.executor.execute_async()
    350 
    351     @property

~/vaex/packages/vaex-core/vaex/execution.py in execute_async(self)
    166                                                     all([all(task.signal_progress.emit(p)) for task in tasks]) and
    167                                                     all([not task.cancelled for task in tasks]),
--> 168                                                     cancel=lambda: self._cancel(run), unpack=True, run=run):
    169                     pass  # just eat all element
    170                 logger.debug("executing took %r seconds" % (time.time() - t0))

~/vaex/packages/vaex-core/vaex/multithreading.py in map_async(self, callable, iterator, count, on_error, progress, cancel, unpack, **kwargs_extra)
     66         total = 0
     67         for i, value in buffer(enumerate(iterator), self._max_workers + 3):
---> 68             value = await value
     69             if value != None:
     70                 total += value

/opt/conda/lib/python3.7/asyncio/futures.py in __await__(self)
    261         if not self.done():
    262             self._asyncio_future_blocking = True
--> 263             yield self  # This tells Task to wait for completion.
    264         if not self.done():
    265             raise RuntimeError("await wasn't used with future")

/opt/conda/lib/python3.7/asyncio/tasks.py in __wakeup(self, future)
    316     def __wakeup(self, future):
    317         try:
--> 318             future.result()
    319         except Exception as exc:
    320             # This may also be a cancellation.

/opt/conda/lib/python3.7/asyncio/futures.py in result(self)
    179         self.__log_traceback = False
    180         if self._exception is not None:
--> 181             raise self._exception
    182         return self._result
    183 

/opt/conda/lib/python3.7/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

~/vaex/packages/vaex-core/vaex/multithreading.py in <lambda>(value)
     62         else:
     63             loop = asyncio.get_event_loop()
---> 64             iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
     65 
     66         total = 0

~/vaex/packages/vaex-core/vaex/multithreading.py in wrapped(*args, **kwargs)
     54                     # print("SLEEP", self._debug_sleep)
     55                     time.sleep(self._debug_sleep)
---> 56                 return callable(self.local.index, *args, **kwargs, **kwargs_extra)
     57         # convert to list so we can count
     58         time_last = time.time() - 100

~/vaex/packages/vaex-core/vaex/execution.py in process_part(self, thread_index, i1, i2, chunks, run)
    230                 if not run.cancelled:
    231                     try:
--> 232                         task._parts[thread_index].process(thread_index, i1, i2, filter_mask, *blocks)
    233                     except Exception as e:
    234                         task.reject(e)

~/vaex/packages/vaex-core/vaex/cpu.py in process(self, thread_index, i1, i2, filter_mask, *blocks)
    336         if filter_mask is not None:
    337             N = filter_mask.astype(np.uint8).sum()
--> 338         blocks = [array_types.to_numpy(block, strict=False) for block in blocks]
    339         for block in blocks:
    340             assert len(block) == N, f'Oops, got a block of length {len(block)} while it is expected to be of length {N} (at {i1}-{i2}, filter={filter_mask is not None})'

~/vaex/packages/vaex-core/vaex/cpu.py in <listcomp>(.0)
    336         if filter_mask is not None:
    337             N = filter_mask.astype(np.uint8).sum()
--> 338         blocks = [array_types.to_numpy(block, strict=False) for block in blocks]
    339         for block in blocks:
    340             assert len(block) == N, f'Oops, got a block of length {len(block)} while it is expected to be of length {N} (at {i1}-{i2}, filter={filter_mask is not None})'

~/vaex/packages/vaex-core/vaex/array_types.py in to_numpy(x, strict)
     87             return x.to_numpy()
     88         else:
---> 89             return x.to_arrow()
     90     elif isinstance(x, np.ndarray):
     91         return x

~/vaex/packages/vaex-core/vaex/column.py in to_arrow(self, type)
     23 
     24     def to_arrow(self, type=None):
---> 25         return pa.array(self, type=type)
     26 
     27 

/opt/conda/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib.array()

/opt/conda/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib._handle_arrow_array_protocol()

~/vaex/packages/vaex-core/vaex/column.py in __arrow_array__(self, type)
    529         if self.null_bitmap is not None:
    530             assert self.null_offset == 0 #self.offset
--> 531             buffers[0] = pa.py_buffer(self.null_bitmap.copy())
    532         arrow_array = pa.Array.from_buffers(type, self.length, buffers=buffers)
    533         return arrow_array

AttributeError: 'ColumnFile' object has no attribute 'copy'
```

Vaex alpha version below:

```
'vaex': '4.0.0.dev0',
 'vaex-core': '4.0.0a3',
 'vaex-viz': '0.5.0.dev0',
 'vaex-hdf5': '0.7.0a1',
 'vaex-server': '0.4.0.dev0',
 'vaex-astro': '0.8.0.dev0',
 'vaex-ui': '0.3.0',
 'vaex-jupyter': '0.6.0.dev0',
 'vaex-ml': '0.11.0a3',
 'vaex-arrow': '0.5.1',
 'vaex-graphql': '0.2.0.dev0'
```

Thank you again for the prompt reply and efforts in development.

**Comment by JovanVeljanoski** [comment]
Hi @xinnyuann 

Thanks for raising this. It is indeed a bug related to some methods not fully working on masked string arrays when the data is cached from GCS or S3. Other types should be fine. 

We are aware and have isolated the problem. We expect the fix for this to be in the next alpha and for sure in the next release. 

Thank you!

**Comment by maartenbreddels** [comment]
thanks for the quick feedback @xinnyuann !

**Comment by maartenbreddels** [comment]
Should be fixed in https://github.com/vaexio/vaex/pull/1032 which includes a test.
