### ISSUE TITLE
[BUG-REPORT] Install vaex V4 error?

### ISSUE THREAD

**Issue by pjgao** [vaexio/vaex#1051]
Thank you for reaching out and helping us improve Vaex!

after clone all files to local, I install by `pip install -e .`, but error ocurred as follow

```
Looking in indexes: xxxxx
Obtaining file:///mnt/d/Download/vaex-master
Requirement already satisfied: pip in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-meta==0.1.0) (20.0.2)
Installing collected packages: vaex-meta
  Running setup.py develop for vaex-meta
    ERROR: Command errored out with exit status 1:
     command: /home/linux/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/d/Download/vaex-master/setup.py'"'"'; __file__='"'"'/mnt/d/Download/vaex-master/setup.py'"'"';f=ge                         tattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/d/Download/vaex-master/
    Complete output (85 lines):
    running develop
    Looking in indexes: xxxx
    Obtaining file:///mnt/d/Download/vaex-master/packages/vaex-core
    Requirement already satisfied: numpy>=1.16 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (1.19.1)
    Requirement already satisfied: astropy>=2 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (4.0.1.post1)
    Requirement already satisfied: aplus in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (0.11.0)
    Requirement already satisfied: tabulate>=0.8.3 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (0.8.7)
    Requirement already satisfied: future>=0.15.2 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (0.18.2)
    Requirement already satisfied: pyyaml in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (5.3.1)
    Requirement already satisfied: progressbar2 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (3.53.1)
    Requirement already satisfied: psutil>=1.2.1 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (5.6.7)
    Requirement already satisfied: requests in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (2.23.0)
    Requirement already satisfied: six in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (1.14.0)
    Requirement already satisfied: cloudpickle in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (1.5.0)
    Requirement already satisfied: pandas in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (1.1.2)
    Requirement already satisfied: dask[array] in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (2.30.0)
    Requirement already satisfied: nest-asyncio>=1.3.3 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (1.4.0)
    Requirement already satisfied: pyarrow>=1.0 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (2.0.0)
    Requirement already satisfied: frozendict in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (1.2)
    Requirement already satisfied: blake3 in /home/linux/miniconda3/lib/python3.7/site-packages (from vaex-core==4.0.0a5) (0.1.7)
    Requirement already satisfied: python-utils>=2.3.0 in /home/linux/miniconda3/lib/python3.7/site-packages (from progressbar2->vaex-core==4.0.0a5) (2.4.0)
    Requirement already satisfied: idna<3,>=2.5 in /home/linux/miniconda3/lib/python3.7/site-packages (from requests->vaex-core==4.0.0a5) (2.9)
    Requirement already satisfied: certifi>=2017.4.17 in /home/linux/miniconda3/lib/python3.7/site-packages (from requests->vaex-core==4.0.0a5) (2020.6.20)
    Requirement already satisfied: chardet<4,>=3.0.2 in /home/linux/miniconda3/lib/python3.7/site-packages (from requests->vaex-core==4.0.0a5) (3.0.4)
    Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/linux/miniconda3/lib/python3.7/site-packages (from requests->vaex-core==4.0.0a5) (1.25.11)
    Requirement already satisfied: pytz>=2017.2 in /home/linux/miniconda3/lib/python3.7/site-packages (from pandas->vaex-core==4.0.0a5) (2020.1)
    Requirement already satisfied: python-dateutil>=2.7.3 in /home/linux/miniconda3/lib/python3.7/site-packages (from pandas->vaex-core==4.0.0a5) (2.8.1)
    Requirement already satisfied: toolz>=0.8.2; extra == "array" in /home/linux/miniconda3/lib/python3.7/site-packages (from dask[array]->vaex-core==4.0.0a5) (0.10.0)
    Installing collected packages: vaex-core
      Attempting uninstall: vaex-core
        Found existing installation: vaex-core 4.0.0a5
        Can't uninstall 'vaex-core'. No files were found to uninstall.
      Running setup.py develop for vaex-core
        ERROR: Command errored out with exit status 1:
         command: /home/linux/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/d/Download/vaex-master/packages/vaex-core/setup.py'"'"'; __file__='"'"'/mnt/d/Download/vaex-ma                         ster/packages/vaex-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop -                         -no-deps
             cwd: /mnt/d/Download/vaex-master/packages/vaex-core/
        Complete output (30 lines):
        我开始安装了core!
        running develop
        running egg_info
        writing vaex_core.egg-info/PKG-INFO
        writing dependency_links to vaex_core.egg-info/dependency_links.txt
        writing entry points to vaex_core.egg-info/entry_points.txt
        writing requirements to vaex_core.egg-info/requires.txt
        writing top-level names to vaex_core.egg-info/top_level.txt
        /mnt/d/Download/vaex-master/packages/vaex-core/setup.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
          import imp
        /home/linux/miniconda3/lib/python3.7/site-packages/setuptools/dist.py:454: UserWarning: Normalizing '4.0.0-alpha.5' to '4.0.0a5'
          warnings.warn(tmpl.format(**locals()))
        package init file 'vaex/arrow/__init__.py' not found (or not a regular file)
        reading manifest file 'vaex_core.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no files found matching '*.cpp' under directory 'vendor'
        warning: no files found matching '*.c' under directory 'vendor'
        warning: no files found matching '*.h' under directory 'src'
        warning: no files found matching '*.c' under directory 'src'
        writing manifest file 'vaex_core.egg-info/SOURCES.txt'
        running build_ext
        building 'vaex.superstrings' extension
        gcc -pthread -B /home/linux/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/linux/miniconda3/lib/python3.7/site-packages/numpy                         /core/include -Ivendor/pybind11/include -Ivendor/pybind11/include -Ivendor/string-view-lite/include -Ivendor/boost -I/home/linux/miniconda3/include -I/home/linux/miniconda3/Library/include -I/mnt/d/Download/v                         aex-master/packages/vaex-core/vendor/pcre/Library/include -I/home/linux/miniconda3/include/python3.7m -c src/strings.cpp -o build/temp.linux-x86_64-3.7/src/strings.o -std=c++11 -mfpmath=sse -O3 -funroll-loops                          -g
        cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
        In file included from src/strings.cpp:13:
        src/superstring.hpp:4:10: fatal error: nonstd/string_view.hpp: No such file or directory
            4 | #include <nonstd/string_view.hpp>
              |          ^~~~~~~~~~~~~~~~~~~~~~~~
        compilation terminated.
        error: command 'gcc' failed with exit status 1
        ----------------------------------------
      ERROR: Can't roll back vaex-core; was not uninstalled
    ERROR: Command errored out with exit status 1: /home/linux/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/d/Download/vaex-master/packages/vaex-core/setup.py'"'"'; __fi                         le__='"'"'/mnt/d/Download/vaex-master/packages/vaex-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __fi                         le__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/d/Download/vaex-master/setup.py", line 73, in <module>
        'develop': DevelopCmd,
      File "/home/linux/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/linux/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/linux/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/linux/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/mnt/d/Download/vaex-master/setup.py", line 32, in run
        raise RuntimeError(f'Oops, failed to install {package}')
    RuntimeError: Oops, failed to install vaex-core
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/linux/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/d/Download/vaex-master/setup.py'"'"'; __file__='"'"'/mnt/d/Downlo                         ad/vaex-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps                          Check the logs for full command output.

```

**Software information**
 - OS: WSL1.0
 - conda python3.7.3

**Comment by JovanVeljanoski** [comment]
Did you use `--recursive` option when pulled ? Looks like stuff are missing...

**Comment by pjgao** [comment]
I download as zip directly, Maybe I did not install `pcre`？
after  `conda install -c conda-forge pcre` and a lot operations and reboots，finally install it successfuly

**Comment by maartenbreddels** [comment]
Good to hear!
