### ISSUE TITLE
Error importing in Jupyter

### ISSUE THREAD

**Issue by pkerpedjiev** [vaexio/vaex#107]
I installed vaex using conda, but when I try to import it into a Jupyter notebook I get the following error:

```
[autoreload of ipywidgets.widgets failed: Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 368, in superreload
    module = reload(module)
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 608, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/peter/miniconda3/envs/cenv3/lib/python3.6/site-packages/ipywidgets/widgets/__init__.py", line 13, in <module>
    from .widget_box import Box, HBox, VBox, GridBox
ImportError: cannot import name 'GridBox'
]
```

Any ideas?

**Comment by maartenbreddels** [comment]
It seems to be a problem with ipywidgets, but it is quite strange. But it seems to be something with the autoreload extension and/or ipywidgets, not vaex.
