### ISSUE TITLE
[BUG-REPORT] Can't Replace na Values in Vaex 4.0.0a5

### ISSUE THREAD

**Issue by kmcentush** [vaexio/vaex#1095]
**Description**
After the fix for #1081, I encountered another replace edge case. If the condition for the where is based on isna(), I get: `AttributeError("module 'pyarrow.compute' has no attribute 'invert'")`. The full traceback can be found below.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
'vaex': '4.0.0a5',
 'vaex-core': '4.0.0a10',
 'vaex-viz': '0.5.0.dev1',
 'vaex-hdf5': '0.7.0a4',
 'vaex-server': '0.4.0a1',
 'vaex-astro': '0.8.0.dev1',
 'vaex-jupyter': '0.6.0.dev1',
 'vaex-ml': '0.11.0a4'
 - Vaex was installed via: pip / conda-forge / from source: pip install vaex=4.0.0a5
 - OS: Windows 10

**Additional information**
```
import numpy as np
import vaex

dt = vaex.from_arrays(
    col1 = np.ma.array(['test', 'test2', '', ''], mask=[False, False, True, True], dtype=str)
)

dt['col1'].isna()  # works by itself
dt.func.where(dt['col1'].isna(), 'fill', dt['col1'])  # errors here
```

<details>
<summary>Traceback</summary>

```
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\scopes.py", line 102, in evaluate
    result = self[expression]
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\scopes.py", line 161, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: 'Unknown variables or column: "where(isna(col1), \'fill\', col1)"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\execution.py", line 182, in execute_async
    cancel=lambda: self._cancel(run), unpack=True, run=run):
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\multithreading.py", line 88, in map_async
    value = await value
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\asyncio\futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\asyncio\tasks.py", line 318, in __wakeup
    future.result()
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\execution.py", line 239, in process_part
    block_dict = {expression: block_scope.evaluate(expression) for expression in run.expressions}
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\execution.py", line 239, in <dictcomp>
    block_dict = {expression: block_scope.evaluate(expression) for expression in run.expressions}
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\scopes.py", line 108, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 149, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\functions.py", line 166, in wrapper
    result = arg.add_missing(result)
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 41, in add_missing
    ar = combine_missing(ar, self._array)
  File "C:\Users\kmcentush\Miniconda3\envs\api\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 12, in combine_missing
    nulls = pc.invert(pc.or_(a.is_null(), b.is_null()))
AttributeError: module 'pyarrow.compute' has no attribute 'invert'
```
</details>

**Comment by JovanVeljanoski** [comment]
Hi @kmcentush 

I tried your code example but I can not reproduce your error (on mac/linux tho, i don't have an access to a Windows machine). 

On my systems the your code example does not crash, but there is no effect (i.e the masked values are no filled). I am not sure if this is a bug or not (@maartenbreddels), but in any case I think you should be using `fillna` or `fillmissing` to fill missing/masked values. I do not think `where` will modify the mask, but maybe just change the hidden/underlying value, which is not what you want I guess...

**Comment by maartenbreddels** [comment]
We didn't bump the pyarrow requirements to 2.0.0 yet, if you upgrade pyarrow, it should work. Indeed, use fillna instead.

**Comment by kmcentush** [comment]
Hi Jovan and Maarten,

I was able to bypass the error using fillna() as you suggested. Funny how when you do something one way for so long you forget the obvious... I did not try the pyarrow upgrade, but it sounds like you'll be incrementing that soon anyways.

Feel free to close this issue if you think the behavior that Jovan found (with the proper pyarrow installed) is expected.
