### ISSUE TITLE
[BUG-REPORT] type error in pyarrow.chunked_array() after filtering with mask

### ISSUE THREAD

**Issue by Jbollenbacher** [vaexio/vaex#1098]
Hi all, I've been using vaex==4.0.0a5 (installed with pip) this week, and I think I've found a bug.  After filtering a vaex_df with a mask, I get a type error from pyarrow.chunked_array(). This code snippet

```
likes = vaex.open('likes.parquet')  # error also occurs when opening hdf5 files
test_events = vaex.open('test_events.parquet')

mask = likes['id'].isin(test_events['id'].evaluate()).evaluate()   #mask is just a numpy array with shape=(len(likes), )
likes_subset = likes[mask]

print(likes_subset)
```

where likes.to_pandas_df().info() is:

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63415956 entries, 0 to 63415955
Data columns (total 4 columns):
 #   Column          Dtype         
---  ------          -----         
 0   like_time       datetime64[ns]
 1   liking_user_id  int64         
 2   liked_user_id   int64         
 3   liked_tweet_id  int64         
dtypes: datetime64[ns](1), int64(3)
memory usage: 1.9 GB
```

results in the following error:

```
ERROR:MainThread:vaex:error evaluating: like_time at rows 0-5
Traceback (most recent call last):
  File "/Users/jmbollen/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 3535, in table_part
    values = dict(zip(column_names, df.evaluate(column_names)))
  File "/Users/jmbollen/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 2604, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/Users/jmbollen/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 5521, in _evaluate_implementation
    result = [finalize_result(k) for k in expressions]
  File "/Users/jmbollen/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 5521, in <listcomp>
    result = [finalize_result(k) for k in expressions]
  File "/Users/jmbollen/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 5517, in finalize_result
    values = array_types.convert(chunks, array_type)
  File "/Users/jmbollen/opt/miniconda3/lib/python3.8/site-packages/vaex/array_types.py", line 140, in convert
    return convert(chunks, "arrow")
  File "/Users/jmbollen/opt/miniconda3/lib/python3.8/site-packages/vaex/array_types.py", line 129, in convert
    return pa.chunked_array([convert(k, type) for k in x])
  File "pyarrow/table.pxi", line 447, in pyarrow.lib.chunked_array
  File "pyarrow/array.pxi", line 296, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert 2019-01-01 00:28:36+00:00 with type pyarrow.lib.TimestampScalar: did not recognize Python value type when inferring an Arrow data type
```

This error is not about the pyarrow.lib.TimestampScalar data type specifically. I also get similar errors for pyarrow.lib.Int64Scalar and pyarrow.lib.StringScalar.  I believe pyarrow is expecting a bytes datatype for the chunked_array() function. 

When I try to export likes_subset, I get similar errors:

```
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
<ipython-input-106-749b2eb60c91> in <module>
----> 1 likes_subset.export('likes_subset.parquet')

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in export(self, path, progress, chunk_size, parallel, fs_options)
   5872             self.export_fits(path, progress=progress)
   5873         elif naked_path.endswith('.parquet'):
-> 5874             self.export_parquet(path, progress=progress, parallel=parallel, chunk_size=chunk_size, fs_options=fs_options)
   5875         elif naked_path.endswith('.csv'):
   5876             self.export_csv(path, progress=progress, parallel=parallel, chunk_size=chunk_size)

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in export_parquet(self, path, progress, chunk_size, parallel, fs_options, **kwargs)
   5937         with vaex.file.open(path=path, mode='wb', fs_options=fs_options) as sink:
   5938             with pq.ParquetWriter(sink, schema, **kwargs) as writer:
-> 5939                 self.export_arrow(writer, progress=progress, chunk_size=chunk_size, parallel=parallel, reduce_large=True)
   5940 
   5941     @docsubst

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in export_arrow(self, to, progress, chunk_size, parallel, reduce_large, fs_options, as_stream)
   5916                         write(writer)
   5917         else:
-> 5918             write(to)
   5919 
   5920     @docsubst

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in write(writer)
   5897             N = len(self)
   5898             if chunk_size:
-> 5899                 for i1, i2, table in self.to_arrow_table(chunk_size=chunk_size, parallel=parallel, reduce_large=reduce_large):
   5900                     writer.write_table(table)
   5901                     progressbar(i2/N)

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in iterator()
   2816         if chunk_size is not None:
   2817             def iterator():
-> 2818                 for i1, i2, chunks in self.evaluate_iterator(column_names, selection=selection, parallel=parallel, chunk_size=chunk_size):
   2819                     chunks = list(map(vaex.array_types.to_arrow, chunks))
   2820                     if reduce_large:

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in evaluate_iterator(self, expression, s1, s2, out, selection, filtered, array_type, parallel, chunk_size, prefetch)
   2646                     previous = current
   2647                     previous_l1, previous_l2 = l1, l2
-> 2648                 previous_chunk = previous.result()
   2649                 yield previous_l1, previous_l2, previous_chunk
   2650 

~/opt/miniconda3/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~/opt/miniconda3/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

~/opt/miniconda3/lib/python3.8/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in f(i1, i2)
   2634                 iter = self._unfiltered_chunk_slices(chunk_size)
   2635                 def f(i1, i2):
-> 2636                     return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, raw=True)
   2637                 previous_l1, previous_l2, previous_i1, previous_i2 = next(iter)
   2638                 # we submit the 1st job

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in _evaluate_implementation(self, expression, i1, i2, out, selection, filtered, array_type, parallel, chunk_size, raw)
   5519                 else:
   5520                     return array_types.convert(arrays[expression], array_type)
-> 5521             result = [finalize_result(k) for k in expressions]
   5522             if not was_list:
   5523                 result = result[0]

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in <listcomp>(.0)
   5519                 else:
   5520                     return array_types.convert(arrays[expression], array_type)
-> 5521             result = [finalize_result(k) for k in expressions]
   5522             if not was_list:
   5523                 result = result[0]

~/opt/miniconda3/lib/python3.8/site-packages/vaex/dataframe.py in finalize_result(expression)
   5515                         values = array_types.convert(chunks[0], array_type)
   5516                     else:
-> 5517                         values = array_types.convert(chunks, array_type)
   5518                     return values
   5519                 else:

~/opt/miniconda3/lib/python3.8/site-packages/vaex/array_types.py in convert(x, type, default_type)
    138             chunks = [convert(k, type) for k in x]
    139             if isinstance(chunks[0], (pa.Array, pa.ChunkedArray, vaex.column.ColumnStringArrow)):
--> 140                 return convert(chunks, "arrow")
    141             elif isinstance(chunks[0], np.ndarray):
    142                 return convert(chunks, "numpy")

~/opt/miniconda3/lib/python3.8/site-packages/vaex/array_types.py in convert(x, type, default_type)
    127     elif type == "arrow":
    128         if isinstance(x, (list, tuple)):
--> 129             return pa.chunked_array([convert(k, type) for k in x])
    130         else:
    131             return to_arrow(x)

~/opt/miniconda3/lib/python3.8/site-packages/pyarrow/table.pxi in pyarrow.lib.chunked_array()
~/opt/miniconda3/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib.array()
~/opt/miniconda3/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib._sequence_to_array()
~/opt/miniconda3/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.pyarrow_internal_check_status()
~/opt/miniconda3/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: Could not convert 2019-01-01 00:28:36+00:00 with type pyarrow.lib.TimestampScalar: did not recognize Python value type when inferring an Arrow data type
```

I have so far been unable to reproduce this error with an artificial dataset.  Something like the following does not produce the error:

```
ids = [i for i in range(0,150)]
col1 = [i**2 for i in range(0,len(ids))]
col2 = ['h'+'i'*i for i in range(0,len(ids))]

a = vaex.from_pandas(pd.DataFrame(list(zip(ids, col1)), columns = ['id','col1']))
b = vaex.from_pandas(pd.DataFrame(list(zip(ids, col2))[0:3], columns = ['id','col2']))

a_subset = a[a['id'].isin(b['id'].evaluate())] #select relevant subset of likes

a_subset
```
 
I wish I could be more specific, but I'm not having much luck tracking this bug down.  If you have specific questions, I'm happy to help if I can.

**Comment by dkipping** [comment]
I am facing a similar issue.
After filtering a vaex dataframe and trying to export the result to csv:

```
df = df[df['column_to_filter'].isin(filter_list)]
# I tried chaining to_pandas_df().to_csv() as I also got the error with .export_csv() already
df.to_pandas_df().to_csv(dump_path)
```

I get the following error trace (sadly I can only see the last part due to some terminal issues):

```
return create_pdf(self.to_dict(column_names=column_names, selection=selection, parallel=parallel))
  File "/datadrive/dennis.kipping/anaconda3/envs/thesis/lib/python3.8/site-packages/vaex/dataframe.py", line 2720, in to_dict
    return dict(list(zip(column_names, [array_types.convert(chunk, array_type) for chunk in self.evaluate(column_names, selection=selection, parallel=parallel)])))
  File "/datadrive/dennis.kipping/anaconda3/envs/thesis/lib/python3.8/site-packages/vaex/dataframe.py", line 2608, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/datadrive/dennis.kipping/anaconda3/envs/thesis/lib/python3.8/site-packages/vaex/dataframe.py", line 5525, in _evaluate_implementation
    result = [finalize_result(k) for k in expressions]
  File "/datadrive/dennis.kipping/anaconda3/envs/thesis/lib/python3.8/site-packages/vaex/dataframe.py", line 5525, in <listcomp>
    result = [finalize_result(k) for k in expressions]
  File "/datadrive/dennis.kipping/anaconda3/envs/thesis/lib/python3.8/site-packages/vaex/dataframe.py", line 5521, in finalize_result
    values = array_types.convert(chunks, array_type)
  File "/datadrive/dennis.kipping/anaconda3/envs/thesis/lib/python3.8/site-packages/vaex/array_types.py", line 140, in convert
    return convert(chunks, "arrow")
  File "/datadrive/dennis.kipping/anaconda3/envs/thesis/lib/python3.8/site-packages/vaex/array_types.py", line 129, in convert
    return pa.chunked_array([convert(k, type) for k in x])
  File "pyarrow/table.pxi", line 447, in pyarrow.lib.chunked_array
  File "pyarrow/array.pxi", line 296, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert 724.2 with type pyarrow.lib.StringScalar: did not recognize Python value type when inferring an Arrow data type
```

The values in filter_list are strings, the dtype of the column_to_filter is also string.
However both can contain a mix of numeric values like the pointed out 724.2 as well as alphanumeric values like "L234".

The error seems to come from the evaluation of the dataframe after the filtering.

**Comment by dkipping** [comment]
After updating to vaex 4.0.0a7 and assuring once again to set the string type on the column as following:

```
df['column_to_filter'] = df['column_to_filter'].astype('string')
```

I am seeing a different Exception now:

```
df.to_pandas_df().to_csv(dump_path)
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/dataframe.py", line 2802, in to_pandas_df
    return create_pdf(self.to_dict(column_names=column_names, selection=selection, parallel=parallel))
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/dataframe.py", line 2720, in to_dict
    return dict(list(zip(column_names, [array_types.convert(chunk, array_type) for chunk in self.evaluate(column_names, selection=selection, parallel=parallel)])))
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/dataframe.py", line 2608, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/dataframe.py", line 5525, in _evaluate_implementation
    result = [finalize_result(k) for k in expressions]
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/dataframe.py", line 5525, in <listcomp>
    result = [finalize_result(k) for k in expressions]
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/dataframe.py", line 5521, in finalize_result
    values = array_types.convert(chunks, array_type)
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/array_types.py", line 140, in convert
    return convert(chunks, "arrow")
  File "/mylocation/anaconda3/envs/myenv/lib/python3.8/site-packages/vaex/array_types.py", line 129, in convert
    return pa.chunked_array([convert(k, type) for k in x])
  File "pyarrow/table.pxi", line 447, in pyarrow.lib.chunked_array
  File "pyarrow/array.pxi", line 296, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 107, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Expected bytes, got a 'pyarrow.lib.StringScalar' object
```
