### ISSUE TITLE
module 'vaex' has no attribute **

### ISSUE THREAD

**Issue by lemonlife2333** [vaexio/vaex#1112]
when i start veax in my docker environment with centos 7.7 .
i got the reply that `AttributeError: module 'vaex' has no attribute 'open'  `,and all of api is similar to it.what should i do ?

**Comment by maartenbreddels** [comment]
I think something went wrong with the installation (upgrade pip and setuptools first using `pip install -U pip setuptools`). Another thing is that you could be in a directory which has a vaex directory, did you check?

**Comment by lemonlife2333** [comment]
thanks,I find that vaex_core and vaex-server are missed.I think reinstallation is a good idea.

**Comment by maartenbreddels** [comment]
That might be an old pip or setuptools not supporting namespace packages, installing vaex-viz for instance would overwrite vaex-core.

**Comment by lemonlife2333** [comment]
Yeah,I need to update pip and setuptools

**Comment by maartenbreddels** [comment]
does it work now?

**Comment by maartenbreddels** [comment]
and can I ask which versions you had?

**Comment by lemonlife2333** [comment]
great,works very well ,thanks

**Comment by maartenbreddels** [comment]
> and can I ask which versions you had?

**Comment by lemonlife2333** [comment]
pip 20.0.2
setuptools 46.4.0

**Comment by lemonlife2333** [comment]
I have reinstall that package and cover the file without backup ,I am sorry

**Comment by maartenbreddels** [comment]
Next time someone finds this issue, please share the version number before upgrading, maybe we can put in a check.

**Comment by SaiSooriya2003** [comment]
When i am using jupyter notebook, I got this error

**Comment by JovanVeljanoski** [comment]
@SaiSooriya2003 

Can you paste the code that lead to this error?

**Comment by SaiSooriya2003** [comment]
Thanks for reply but i rectified that error but i am getting some other errors now.

Code:
import vaex
ds = vaex.datasets.helmi_de_zeeuw.fetch()

OSError: Cannot open C:\Users\saiso/.vaex\data\helmi-dezeeuw-2000-FeH-v2.hdf5, failures: 
-----hdf5 = vaex.hdf5.dataset:Hdf5MemoryMapped-----
:Traceback (most recent call last):
  File "D:\Drivers\anaconda3\lib\site-packages\vaex\dataset.py", line 35, in open
    opener = entry.load()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.hdf5'


-----hdf5-amuse = vaex.hdf5.dataset:AmuseHdf5MemoryMapped-----
:Traceback (most recent call last):
  File "D:\Drivers\anaconda3\lib\site-packages\vaex\dataset.py", line 35, in open
    opener = entry.load()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.hdf5'


-----hdf5-gadget = vaex.hdf5.dataset:Hdf5MemoryMappedGadget-----
:Traceback (most recent call last):
  File "D:\Drivers\anaconda3\lib\site-packages\vaex\dataset.py", line 35, in open
    opener = entry.load()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.hdf5'


-----fits = vaex.astro.fits:FitsBinTable-----
:Traceback (most recent call last):
  File "D:\Drivers\anaconda3\lib\site-packages\vaex\dataset.py", line 35, in open
    opener = entry.load()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.astro'


-----gadget = vaex.astro.gadget:MemoryMappedGadget-----
:Traceback (most recent call last):
  File "D:\Drivers\anaconda3\lib\site-packages\vaex\dataset.py", line 35, in open
    opener = entry.load()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.astro'


-----tap = vaex.astro.tap:DatasetTap-----
:Traceback (most recent call last):
  File "D:\Drivers\anaconda3\lib\site-packages\vaex\dataset.py", line 35, in open
    opener = entry.load()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.astro'


-----votable = vaex.astro.votable:VOTable-----
:Traceback (most recent call last):
  File "D:\Drivers\anaconda3\lib\site-packages\vaex\dataset.py", line 35, in open
    opener = entry.load()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "D:\Drivers\anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.astro'
.

**Comment by SaiSooriya2003** [comment]
I downloaded that hdf5 file from internet may be they would have done any mistake, i will try to create an hdf5 file. Thanks for your reply
