### ISSUE TITLE
[BUG-REPORT] Can't start vaex application in Anaconda Navigator: No module named 'vaex.remote'

### ISSUE THREAD

**Issue by mrgou** [vaexio/vaex#1132]
When attempting to start the vaex application from Anaconda navigator, the following error is displayed:

```
Traceback (most recent call last):
File "/home/raphael/anaconda3/envs/vaex_env/bin/vaex", line 11, in 
sys.exit(main())
File "/home/raphael/anaconda3/envs/vaex_env/lib/python3.7/site-packages/vaex/__main__.py", line 128, in main
import vaex.ui.main
File "/home/raphael/anaconda3/envs/vaex_env/lib/python3.7/site-packages/vaex/ui/main.py", line 13, in 
import vaex.remote
ModuleNotFoundError: No module named 'vaex.remote'
```

This happens even though vaex is installed in its own environment, with all dependencies.

**Comment by JovanVeljanoski** [comment]
Hi,

The Vaex application (the GUI interface) is no longer supported or actively maintained. You might be able to get it working, but you would need to play a bit with the source code to remove things that were deprecated or removed from vaex-core. 

Is there a particular reason why you would prefer to use the Vaex GUI application compared to the python library?

Thanks!

**Comment by mrgou** [comment]
Not really, I just wanted to try it out since it's available as an Anaconda application and it's still documented. I guess it would be worth cleaning up.
