### ISSUE TITLE
Can't drop column using df.drop('column_name', inplace=True) AssertionError: not an expression

### ISSUE THREAD

**Issue by serega-upgini** [vaexio/vaex#1140]
**Description**
Trying to add new column and drop existing

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
  ```pyton
version = {'vaex': '4.0.0a6', 'vaex-core': '4.0.0a11', 'vaex-viz': '0.5.0.dev1', 'vaex-hdf5': '0.7.0a5', 'vaex-server': '0.4.0a1', 'vaex-astro': '0.8.0.dev1', 'vaex-jupyter': '0.6.0.dev1', 'vaex-ml': '0.11.0a4', 'vaex-arrow': '0.5.1'}

```
 - Vaex was installed via: pip 
 - OS: MacOs 0.14.6 Mojave

```python
 csv_df = vaex.from_csv(big_tds_50000_diff_targets_csv, copy_index=False, delimiter=',', header='infer')

  def to_millis(dd_mm_yyyy):
      return datetime.strptime(dd_mm_yyyy, '%d.%m.%Y').timestamp() * 1000

  csv_df['date_millis'] = csv_df['rep_date'].apply(to_millis)
  print(csv_df.head(1))
  csv_df.drop('rep_date', inplace=True)
```

Outputs:
```
#    Unnamed: 0  rep_date            date_millis
  0                        '28.10.2018'       1.54068e+12

File "/Users/me/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex/dataframe.py", line 4632, in drop
   depending_columns = df._depending_columns(columns_exclude=columns)
 File "/Users/me/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex/dataframe.py", line 4659, in _depending_columns
   depending_columns |= expression.variables()
 File "/Users/me/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex/expression.py", line 405, in variables
   expresso.translate(self.ast, record)
 File "/Users/me/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex/expression.py", line 227, in ast
   self._ast = expresso.parse_expression(self.expression)
 File "/Users/me/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex/expresso.py", line 619, in parse_expression
   assert isinstance(expr, ast.Expr), "not an expression"
AssertionError: not an expression
```

why?

**Comment by serega-upgini** [comment]
I found the problem. There is some issue with "unnamed" columns.
Input CSV looks this way:
```
,    rep_date
1,  28.10.2018
2,  28.10.2019
```
First column doesn't have name (odd case, but happens...). I gave name to column in source CSV and drop started to work
Inspired by this post: https://stackoverflow.com/questions/62295466/vaex-column-name-change

**Comment by JovanVeljanoski** [comment]
It should work.. but be careful how the columns are named :)
I see a lot of spaces between that coma and the `rep_date` in the header. 

You can check with 

`df.column_names`

I will close this, but please feel free to reopen if needed.

**Comment by hermidalc** [comment]
```python
import vaex

df = vaex.example()
tgas = vaex.datasets.tgas(full=True)

f_df = df[df.x < 10]
f_df.join(tgas, how="inner", left_on="id", right_on="astrometric_n_good_obs_ac", allow_duplication=True)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In [1], line 7
      4 tgas = vaex.datasets.tgas(full=True)
      6 f_df = df[df.x < 10]
----> 7 f_df.join(tgas, how="inner", left_on="id", right_on="astrometric_n_good_obs_ac", allow_duplication=True)

File ~/soft/mambaforge/envs/vaex/lib/python3.10/site-packages/vaex/dataframe.py:6705, in DataFrameLocal.join(self, other, on, left_on, right_on, lprefix, rprefix, lsuffix, rsuffix, how, allow_duplication, prime_growth, cardinality_other, inplace)
   6703 kwargs['df'] = kwargs.pop('self')
   6704 del kwargs['vaex']
-> 6705 return vaex.join.join(**kwargs)

File ~/soft/mambaforge/envs/vaex/lib/python3.10/site-packages/vaex/join.py:214, in join(df, other, on, left_on, right_on, lprefix, rprefix, lsuffix, rsuffix, how, allow_duplication, prime_growth, cardinality_other, inplace)
    212     lookup_left = np.concatenate([k[0] for k in lookup_extra_chunks])
    213     lookup_right = np.concatenate([k[1] for k in lookup_extra_chunks])
--> 214     left = left.concat(left.take(lookup_left))
    215     lookup = np.concatenate([lookup, lookup_right])
    217 if inner:

File ~/soft/mambaforge/envs/vaex/lib/python3.10/site-packages/vaex/dataframe.py:4461, in DataFrame.take(self, indices, filtered, dropfilter)
   4459     mask = df._selection_masks[FILTER_SELECTION_NAME]
   4460     filtered_indices = mask.first(max_index+1)
-> 4461     indices = filtered_indices[indices]
   4462 df.dataset = df.dataset.take(indices)
   4463 if dropfilter:
   4464     # if the indices refer to the filtered rows, we can discard the
   4465     # filter in the final dataframe

IndexError: index 309375 is out of bounds for axis 0 with size 306607
```
