### ISSUE TITLE
[BUG-REPORT] Columns with spaces throw error with from_dict

### ISSUE THREAD

**Issue by foooooooooooooooobar** [vaexio/vaex#1229]
**Description**
There seems to be a problem with columns that have spaces in them. I provided an example below that clearly demonstrates it.

````
        df_pd = {}
        df_pd['A'] = [0]
        df_pd['SHORT VOLUME'] = ['4563']
        df_pd['SHORT_VOLUME'] = ['4563']
        df = vaex.from_dict(df_pd)
        display(df)
````

Result:
![image](https://user-images.githubusercontent.com/79293114/109177649-e2b22180-773c-11eb-9f08-2f696f804ccc.png)

What I would expect:
Both "short volume columns" would have values in them.

Let me know if you have any questions

**Software information**
 - Vaex version v4.0.0-alpha.13 
 - Vaex was installed via:  pip
 - OS: Mac OSX

**Comment by maartenbreddels** [comment]
I cannot see your image, this is what I get:
![image](https://user-images.githubusercontent.com/1765949/109812481-66cc4380-7c2c-11eb-9427-8eb960dc82d0.png)

Looks fine, am I missing something?

**Comment by foooooooooooooooobar** [comment]
I'm on Python 3.9.1, does that have to do with it?

I also installed vaex 4.0.0 and it's now throwing another error

```
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vaex/execution.py", line 171, in execute_async
    variables |= run.df._expr(expression).expand().variables(ourself=True)
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vaex/expression.py", line 381, in expand
    expr = expresso.translate(self.ast, translate)
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vaex/expresso.py", line 594, in translate
    return node_to_string(node)
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vaex/expresso.py", line 624, in node_to_string
    return ExpressionString(pretty=pretty).visit(node)
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/site-packages/vaex/expresso.py", line 439, in visit_Subscript
    v = self.visit(node.slice.value)
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 411, in generic_visit
    for field, value in iter_fields(node):
  File "/home/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 249, in iter_fields
    for field in node._fields:
AttributeError: 'str' object has no attribute '_fields'
```

Also same thing happens parsing this CSV
```
DATE|SYMBOL|SHORT VOLUME|TOTAL VOLUME|MARKET
20100104|A|172058|257658|B
20100104|AA|555721|1155435|B
20100104|AACC|200|200|B
20100104|AAI|244480|345190|B
20100104|AAN|1700|2300|B
20100104|AAON|0|200|B
20100104|AAP|51660|95350|B
```

**Comment by foooooooooooooooobar** [comment]
For the csv bug if I add ```
    header=0,
    names=['DATE','SYMBOL','SHORT VOLUME','TOTAL_VOLUME','MARKET'],
``` it no longer throws the error
