### ISSUE TITLE
Trying to build py app with vaex 4.1.0 using PyInstaller

### ISSUE THREAD

**Issue by serega-upgini** [vaexio/vaex#1276]
**Description**
Hi, I'm trying to use https://pyinstaller.readthedocs.io/en/stable/index.html to build python package
Here a snippet that builds binary package
```shell script

RUN pyinstaller --noconfirm --log-level=DEBUG \
    --onefile --nowindow \
    --distpath=/build/ \
    --hidden-import="sklearn.utils._cython_blas" \
    --hidden-import="sklearn.neighbors.typedefs" \
    --hidden-import="sklearn.neighbors.quad_tree" \
    --hidden-import="sklearn.tree._utils" \
    --hidden-import="vaex" \
    --hidden-import="vaex.dataset" \
    --hidden-import="vaex.arrow" \
    --hidden-import="pyarrow" \
    --hidden-import="pillow" \
    --hidden-import="astropy" \
    --hidden-import="matplotlib" \
    --hidden-import="vaex_arrow" \
    --hidden-import="vaex.file" \
    --hidden-import="vaex_hdf5" \
    --hidden-import="vaex.hdf5" \
    --exclude-module matplotlib \
    --key "$(openssl rand -base64 16)" \
    app.py
```

**Software information**
```properties
catboost==0.20.2
vaex==4.1.0
pytest==6.2.2
pytest-datafiles
typing_json==0.1.3
scikit-learn==0.22.1
pydantic==1.8.1
unittest-xml-reporting==3.0.4
pyinstaller[encryption]
```
 - OS: `gcr.io/distroless/java:8`

**Additional information**
app works w/o packaging. Packaged app throws exception when trying to open path '/data/*.arrow' ( I feed a dir with many arrow files)
```
ERROR:MainThread:vaex:error opening '/data/1.arrow'
[115] Failed to execute script app
Traceback (most recent call last):
File "app.py", line 63, in <module>
File "app.py", line 55, in main
File "train.py", line 35, in train
File "vaex/__init__.py", line 222, in open
File "vaex/dataset.py", line 59, in open
OSError: Cannot open /data/1.arrow nobody knows how to read it.

```

**Some tracing info**
I've tried to debug it and I think the problem is here:
https://github.com/vaexio/vaex/blob/master/packages/vaex-core/setup.py#L154
It sets entry points.
They are empty when using vaex from packaged python app. What is the right way to fix it?
```
def open(path, *args, **kwargs):
    failures = []
    if not opener_classes:
        print("f not opener_classes:")
        print(f"pkg_resources: {pkg_resources}, "
              f"pkg_resources.iter_entry_points(group='vaex.dataset.opener'): "
              f"{pkg_resources.iter_entry_points(group='vaex.dataset.opener')}")
        for entry in pkg_resources.iter_entry_points(group='vaex.dataset.opener'):
            logger.info('trying opener: ' + entry.name)
            print('trying opener: ' + entry.name)
            try:
```

**What I've tried**
I'm trying to monkey-patch vaex and read arrow directly since I need to read only arrow files.

```python

def open_arrow(path, *args, **kwargs):
    ArrowOpener.open(path, *args, **kwargs)


# in my main method
vaex.dataset.open = open_arrow
df = vaex.open(run_config.data_def.data_path).as_numpy()
```
It fails with
```
  File "my_project/train.py", line 44, in train
    df = vaex.open(data_path).as_numpy()
  File "my_home/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex/__init__.py", line 222, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "my_project/dummy_opener.py", line 24, in open_arrow
    ArrowOpener.open(path, *args, **kwargs)
  File "my_home/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex_arrow/opener.py", line 10, in open
    from .dataset import DatasetArrow
  File "my_home/.pyenv/versions/3.7.3/lib/python3.7/site-packages/vaex_arrow/dataset.py", line 8, in <module>
    import vaex.file.other
ModuleNotFoundError: No module named 'vaex.file.other'
```

I think I've found smth:
```python
from vaex.arrow.opener import ArrowOpener

# omitted for brevity
vaex.dataset.opener_classes = [ArrowOpener()]
df = vaex.open("/data/*.arrow").as_numpy()
logging.info(f"input shape: {df.shape}")

```
Now it fails with
```
ERROR:MainThread:vaex:error opening '/data/1.arrow'
[94] Failed to execute script app
Traceback (most recent call last):
  File "app.py", line 62, in <module>
  File "app.py", line 54, in main
  File "train.py", line 51, in train
  File "vaex/__init__.py", line 222, in open
  File "vaex/dataset.py", line 45, in open
  File "vaex/arrow/opener.py", line 14, in open
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "vaex/arrow/dataset.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "pyarrow/dataset.py", line 23, in <module>
  File "pyarrow/_dataset.pyx", line 1, in init pyarrow._dataset
ModuleNotFoundError: No module named 'pyarrow._csv'

```

**Comment by maartenbreddels** [comment]
Hi,

great, you seem to have come pretty far! I think the last issue now is to add `pyarrow._csv`  to hidden import. Note that the related issues are not related to vaex, but pyinstaller/pyarrow, so closing this for now.
But please follow up on how you solved this, since it might be valuable for others, thanks for sharing this.

Regards,

Maarten

**Comment by serega-upgini** [comment]
Hi, sure, for now we decided to abandon it, way too complex and didn't work
:) Will try again later.

**Comment by SyureNyanko** [comment]
I was able to solve the problem for arrow as well. (Including hidden import, as @maartenbreddels mentioned.)
main.py
```python
import vaex
# from vaex.hdf5.dataset import Hdf5MemoryMapped
from vaex.arrow.opener import ArrowOpener

if __name__ == '__main__':
    vaex.dataset.opener_classes = [ArrowOpener]
    df = vaex.open('testdf.arrow')
    print(df)

#  create file for test
#     df = vaex.from_dict({'A':[1,2,3],'B':['a','b','c']})
#    df.export('testdf.arrow')
```

 in main.spec
```python
...

a = Analysis(['main.py'],
             pathex=['C:\\Users\\naohiro.heya\\desktop-proto'],
             binaries=[],
             datas=[],
             hiddenimports=['pandas._libs.tslibs.base', 'pyarrow._csv'],
             hookspath=[],
...

```

```
> pyinstaller main.spec --onefile --clean
```

Thanks!

**Comment by maartenbreddels** [comment]
Nice, thanks for sharing this!
Note that our very old spec file can be found here: https://github.com/vaexio/vaex/blob/ecf2b401c5ca93aa86e9fdf56e725673da1564b5/misc/vaex.spec in case that helps
