### ISSUE TITLE
[BUG-REPORT] Calling apply() with multiprocessing on throws an exception

### ISSUE THREAD

**Issue by maxharlow** [vaexio/vaex#1281]
Calling apply() with multiprocessing throws an exception. For example, this:

```python
import vaex

df = vaex.from_arrays(number=['one', 'two', 'three'])

def transform(text):
    return '_'.join([char for char in text])

df['number_underscore'] = df['number'].apply(transform)

print(df)
```

Throws this huge error:

```
ERROR:MainThread:vaex:error evaluating: number_underscore at rows 0-3
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vaex/scopes.py", line 102, in evaluate
    result = self[expression]
  File "/usr/local/lib/python3.9/site-packages/vaex/scopes.py", line 159, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'lambda_function(number)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/vaex/dataframe.py", line 1968, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/usr/local/lib/python3.9/site-packages/vaex/dataframe.py", line 2642, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/usr/local/lib/python3.9/site-packages/vaex/dataframe.py", line 5676, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/usr/local/lib/python3.9/site-packages/vaex/scopes.py", line 102, in evaluate
    result = self[expression]
  File "/usr/local/lib/python3.9/site-packages/vaex/scopes.py", line 152, in __getitem__
    values = self.evaluate(expression)
  File "/usr/local/lib/python3.9/site-packages/vaex/scopes.py", line 108, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/vaex/expression.py", line 1258, in __call__
    return vaex.multiprocessing.apply(self._apply, args, kwargs, self.multiprocessing)
  File "/usr/local/lib/python3.9/site-packages/vaex/multiprocessing.py", line 32, in apply
    result = _get_pool().apply(f, args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/vaex/multiprocessing.py", line 17, in _get_pool
    _pool = Pool(process_count_default)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

This is printed out multiple times, followed by this:

```
  #  number    number_underscore
  0  'one'     o_n_e
  1  'two'     t_w_o
  2  'three'   t_h_r_e_e
  #  number    number_underscore
  0  'one'     error
  1  'two'     error
  2  'three'   error
  #  number    number_underscore
  0  'one'     error
  1  'two'     error
  2  'three'   error
  #  number    number_underscore
  0  'one'     error
  1  'two'     error
  2  'three'   error
  #  number    number_underscore
  0  'one'     error
  1  'two'     error
  2  'three'   error
```

Adding `multiprocessing=False` to the `apply` seems to fix the problem.

Vaex version: `{'vaex': '4.1.0', 'vaex-core': '4.1.0', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.7.0', 'vaex-server': '0.4.0', 'vaex-astro': '0.8.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.11.1'}`

Installed with Pip
Python 3.9.1 on MacOS 10.15.7

**Comment by maartenbreddels** [comment]
Hi Max,

thanks for the report. I managed to reproduce this.
This is a problem with multiprocessing in general, and if I understand correctly, it is because it tried to import your script from the subprocess again, which will execute your code again, and again. To avoid this from happing, put your function in a separate module, or use a guard like this:
```python
import vaex

df = vaex.from_arrays(number=['one', 'two', 'three'])

def transform(text):
    return '_'.join([char for char in text])

if __name__ == "__main__":  # don't run when imported by multiprocessing
    df['number_underscore'] = df['number'].apply(transform)
    print(df)
```

If this does not help, feel free to reopen/

Regards,

Maarten
