### ISSUE TITLE
[BUG-REPORT] column problems after opening parquet from local filesystem with hive-dir-names

### ISSUE THREAD

**Issue by Barry1** [vaexio/vaex#1357]
**Description**
I tried to use the hive-dir-structure, layed down some (fine working) parquet-files and opened them (sametime, one call to open). That seems to produce a problem with those columns generated from the partitioning details.

Here is a _minimal not-working-example_
```python
import os

import numpy
import vaex

x = numpy.arange(2)
y = numpy.array([10, 20])
z = numpy.array(["dog", "cat"])
dirname = "unit=first"
os.mkdir(dirname)
vaex.from_arrays(x=x, y=y, z=z).export_parquet(dirname + os.sep + "first.parquet")
vaex.from_arrays(x=y, y=x, z=z).export_parquet(dirname + os.sep + "second.parquet")
dirname = "unit=second"
os.mkdir(dirname)
vaex.from_arrays(x=x, y=y, z=numpy.array(["bird", "mice"])).export_parquet(
    dirname + os.sep + "third.parquet"
)
test = vaex.open("*/*.parquet")
print(test.shape)
print(test)
print(test.describe())
```
The result is fine including `print(test)` but describe crashed
```
(6, 4)
  #    x    y  z       unit
  0    0   10  'dog'   'first'
  1    1   20  'cat'   'first'
  2   10    0  'dog'   'first'
  3   20    1  'cat'   'first'
  4    0   10  'bird'  'second'
  5    1   20  'mice'  'second'
Traceback (most recent call last):
  File "testproblem.py", line 21, in <module>
    print(test.describe())
  File "C:\Users\BE0011\AppData\Roaming\Python\Python38\site-packages\vaex\dataframe.py", line 5011, in describe
    elif data_type.kind in "SU":
  File "C:\Users\BE0011\AppData\Roaming\Python\Python38\site-packages\vaex\datatype.py", line 103, in kind
    return self.numpy.kind
  File "C:\Users\BE0011\AppData\Roaming\Python\Python38\site-packages\vaex\datatype.py", line 112, in numpy
    return vaex.array_types.to_numpy_type(self.internal)
  File "C:\Users\BE0011\AppData\Roaming\Python\Python38\site-packages\vaex\array_types.py", line 262, in to_numpy_type
    return numpy_dtype_from_arrow_type(data_type, strict=strict)
  File "C:\Users\BE0011\AppData\Roaming\Python\Python38\site-packages\vaex\array_types.py", line 272, in numpy_dtype_from_arrow_type
    return numpy_dtype(data, strict=strict)
  File "C:\Users\BE0011\AppData\Roaming\Python\Python38\site-packages\vaex\array_types.py", line 208, in numpy_dtype
    dtype = arrow_type.to_pandas_dtype()
  File "pyarrow\types.pxi", line 200, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: dictionary<values=string, indices=int32, ordered=0>
```

What I found out is, that if ignoring the column `unit` the rest is working - but that is not, what I expect. For example I'd like to groupby that column or so.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: *{'vaex': '4.1.0', 'vaex-core': '4.1.0', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.7.0', 'vaex-server': '0.4.0', 'vaex-astro': '0.8.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.11.1'}*
 - Vaex was installed via *pip*
 - OS: *Microsoft Windows [Version 10.0.18363.1500]*
 - Python *3.8.5*

**Comment by derekwisong** [comment]
I'm reporting a similar error with hive-partitioned parquet.

```
print(f"{sys.version} pandas={pd.__version__} vaex={vaex.__version__}")

3.8.10 (default, May 12 2021, 15:56:47) 
[GCC 8.3.0] pandas=1.2.4 vaex={'vaex': '4.1.0', 'vaex-core': '4.1.0', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.7.0', 'vaex-server': '0.4.0', 'vaex-astro': '0.8.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.11.1'}
```

My reproducer:

```
import pandas as pd
import vaex
import sys

pandas_df = pd.DataFrame({"id":[1,2,3,1,2,3],"date":(3 * ["2021-01-01"]) + (3 * ["2021-01-02"])})
pandas_df.to_parquet("./my_data", partition_cols="date")

vaex_df = vaex.open("./my_data/")
vaex_df[vaex_df["date"] == "2021-01-01"]
```

Which results repeated occurrences of:

```
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/execution.py", line 232, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 2602, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/scopes.py", line 181, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/scopes.py", line 219, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/selections.py", line 130, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 2588, in _evaluate_selection_mask
    mask = scope.evaluate(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/scopes.py", line 184, in evaluate
    tb.print_stack()
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/scopes.py", line 219, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/selections.py", line 130, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 2588, in _evaluate_selection_mask
    mask = scope.evaluate(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/scopes.py", line 181, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/functions.py", line 130, in decorated
    return f(x, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/functions.py", line 1032, in str_equals
    x = _to_string_sequence(x)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/column.py", line 446, in _to_string_sequence
    return convert.column_from_arrow_array(x).string_sequence
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/arrow/convert.py", line 84, in column_from_arrow_array
    return numpy_array_from_arrow_array(arrow_array)
  File "/home/airflow/.local/lib/python3.8/site-packages/vaex/arrow/convert.py", line 124, in numpy_array_from_arrow_array
    dtype = arrow_array.type.to_pandas_dtype()
  File "pyarrow/types.pxi", line 200, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: dictionary<values=string, indices=int32, ordered=0>
```

**Comment by tdeboer-ilmn** [comment]
Here's my reproducing code for this same issue...Just to get notified when this gets fixed :)

```
d = {
    'CHROM':['1', '1', '1', '2', '2', '12', 'X'],
    'GENPOS':[2217097, 2436407, 12454818, 24920657, 169800441, 9576633, 20820484],
    'REF': ['G', 'C', 'CCT','G', 'A', 'G', 'T'],
    'ALT': ['A', 'T', 'C',  'T', 'T', 'A', 'TG']
}
df = vaex.from_dict(d)
os.makedirs('/tmp/aap/', exist_ok=False)
df.export_partitioned('/tmp/aap/{subdir}/{uuid}.parquet',by='CHROM')
dp = vx.open('/tmp/aap')
dpf = dp[dp.CHROM=='12']
len(dpf)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/vaex/scopes.py in evaluate(self, expression, out)
    112             # logger.debug("try avoid evaluating: %s", expression)
--> 113             result = self[expression]
    114         except KeyError:

~/.local/lib/python3.7/site-packages/vaex/scopes.py in __getitem__(self, variable)
    197             if variable not in self.values:
--> 198                 raise KeyError("Unknown variables or column: %r" % (variable,))
    199 

KeyError: 'Unknown variables or column: "str_equals(CHROM, \'12\')"'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/vaex/array_types.py in numpy_dtype_from_arrow_type(arrow_type, strict)
.
.
NotImplementedError: Cannot convert dictionary<values=string, indices=int32, ordered=0>
```

**Comment by maartenbreddels** [comment]
Note for myself, this might be fixed by https://github.com/vaexio/vaex/pull/1841
