### ISSUE TITLE
[BUG-REPORT] Can not delete virtual_column using delete_virtual_column()

### ISSUE THREAD

**Issue by heyuqi1970** [vaexio/vaex#1382]
**Description**

```
df.add_virtual_column("w", 'Sales_Tax *2')
df.delete_virtual_column(df['w'])
Traceback (most recent call last):
  File "/Users/heyuqi/opt/anaconda3/envs/vaex4/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-90200dca92f9>", line 1, in <module>
    df.delete_virtual_column(df['w'])
  File "/Users/heyuqi/development/vaex/install/vaex/packages/vaex-core/vaex/dataframe.py", line 3368, in delete_virtual_column
    del self.virtual_columns[name]
TypeError: unhashable type: 'Expression'
```

**Software information**
 {'vaex': '4.1.0',
 'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.0',
 'vaex-astro': '0.8.0',
 'vaex-ui': '0.3.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.11.1',
 'vaex-graphql': '0.2.0'}
 - OS:macos big sur

**Comment by SyureNyanko** [comment]
I think the correct usage of delete_virtual_column is as follows.
```python
import vaex
df = vaex.example()

df.add_virtual_column("w", 'x * 2')
df.delete_virtual_column('w')
```
