### ISSUE TITLE
Vaex-server "TypeError: unhashable type: 'KeysView'"

### ISSUE THREAD

**Issue by rahulsingh7** [vaexio/vaex#1392]
I am trying to start my own vaex server 
my dataset is a partitioned parquet file having the hive format:
partitioned
      |
      country==Africa
      |          |
      |          week==9
      |          |      | 
      |          |       <uuid>.parquet
      |          week==10
      |          |       |
      |          |       <uuid>.parquet
      |          | ..... 
      country==India
      |          |
      |          week==9
      |          |      | 
      |          |       <uuid>.parquet
      |          week==10
      |          |       |
      |          |       <uuid>.parquet
      |          | ..... 
      |......

I am trying to run the server from the same folder where my partitioned parquet file "partitioned" is located
using the command:
$ vaex webserver ./partitioned

this gives me an error saying:
$ vaex webserver ./partitioned

INFO:MainThread:vaex.webserver:datasets:
INFO:MainThread:vaex.webserver: http://0.0.0.0:9000/KeysView(<vaex.arrow.dataset.DatasetParquet object at 0x000001448F15D198>) or ws://0.0.0.0:9000/KeysView(<vaex.arrow.dataset.DatasetParquet object at 0x000001448F15D198>)
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\vaex.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\lib\site-packages\vaex\__main__.py", line 66, in main
    vaex.server.tornado_server.main([os.path.basename(args[0]) + " " + args[1]] + args[2:])
  File "d:\anaconda3\lib\site-packages\vaex\server\tornado_server.py", line 329, in main
    threads_per_job=config.threads_per_job)
  File "d:\anaconda3\lib\site-packages\vaex\server\tornado_server.py", line 193, in __init__
    self.set_datasets(datasets)
  File "d:\anaconda3\lib\site-packages\vaex\server\tornado_server.py", line 214, in set_datasets
    self.datasets_map = dict([(ds.name, ds) for ds in self.datasets])
TypeError: unhashable type: 'KeysView'

**Comment by maartenbreddels** [comment]
That should be fixed with a new release, let us know!
