### ISSUE TITLE
[FEATURE-REQUEST] Apply to accept partial function?

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1428]
**Description**
Hi there!
I am a complete newbie to Vaex. I have started coding a lib with a mix of pandas and 'numba-boosted' functions. This is all very nice, but Dataframes are too big, and it simply does not work because not fitting in memory...
I am having a look at Vaex, and I would like to know if there is a way to use custom functions to operate on a Dataframe content?
Such a function basically operates row per row, with a buffer to keep track of previous computations that impact current one (current row).

Thinking that I could try to use vaex's `apply` to answer this need, and reading in the documentation...
_Apply a function on a per row basis across the entire DataFrame._
...I tried this simplified example, making use of `partial` from `functools`.

```python
import vaex as vx
import numpy as np
from functools import partial

vd = vx.from_arrays(a=np.array([1,2,3,4]))
# Crazily complex function operating on individual cells.
def crazy(data: float, buffer: np.ndarray):
    data += buffer[0]
    buffer[0] = data
    return data

buffer = np.zeros(1)
crazy_ = partial(crazy, buffer=buffer)

vd.apply(crazy_, arguments = [vd.a])
```

When running this code, it does not appear to be the proper way however.
```pyhton
Traceback (most recent call last):

  File "<ipython-input-1-d76879173f2c>", line 15, in <module>
    vd.apply(crazy_, arguments = [vd.a])

  File "/home/pierre/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 427, in apply
    name = f.__name__

AttributeError: 'functools.partial' object has no attribute '__name__'
```

**Additional context**
Here is an example of the 'original' implementation. It is 'vectorized' thanks to Numba's 'guvectorize' also I am not so sure word 'vectorized' is appropriate here.

```python
import numpy as np
import pandas as pd
from numba import guvectorize

df = pd.DataFrame({'a':[1,2,3,4]})
# Crazily complex function operating on individual cells.
@guvectorize('void(float64[:], float64[:])', '(m)->(m)', nopython=True)
def crazy(data: np.ndarray, res: np.ndarray):
    buffer = 0
    for idx, val in np.ndenumerate(data):
        idx, = idx
        res[idx] = val+buffer
        buffer = res[idx]

result = np.zeros(len(df))
crazy(df['a'].to_numpy(), result)
```

Maybe a Numba pseudo vectorized function like the one above might be easier to directly use with Vaex?
My trouble being DataFrame not fitting into memory, I would ideally read the data from a Vaex DataFrame, and output results only when writing them to disk (or after a subsequent filtering operation that makes the remaining results fit in memory).

Please, any advice on how achieving this?

Thanks a lot for any help,
Bests

**Comment by maartenbreddels** [comment]
Hi,

good question, and I think they are two in one, let me start with the first and simplest one (If I misunderstood, let me know!):
## 1) Can vaex use partial?

Not out of the box, since partial doesn't add a `__name__` attribute, however, you can do:
```python
import vaex
from functools import partial
df = vaex.example()

def test(x, a):
    return x + a
test_fix = partial(test, a=1e6)
test_fix.__name__ = 'test_fix'
df.apply(test_fix, [df.x])
```
```
Expression = test_fix(x)
Length: 330,000 dtype: float64 (expression)
-------------------------------------------
     0        1e+06
     1        1e+06
     2       999998
     3        1e+06
     4  1.00001e+06
        ...        
329995        1e+06
329996        1e+06
329997        1e+06
329998        1e+06
329999  1.00002e+06
```

I consider this a bug in vaex btw, we should be able to accept the partial function
 
## 2) Can vaex row results depend on previous results?
Not yet, we _do_ have https://vaex.io/docs/api.html#vaex.dataframe.DataFrame.diff and https://vaex.io/docs/api.html#vaex.dataframe.DataFrame.shift now, which basically lay the foundation to enable what you want, but we are not exposing it yet.
Note that the fundamental issue in vaex to support this is that you need the chunks that are processed to overlap and vary its results to the next chunk (like in cumulative min/max)

This may come one day for sure, but with no direct funding for this, we cannot give a timeline for it.

I hope this answers your question.

**Comment by yohplala** [comment]
Hi @maartenbreddels,
Thank you very much for your detailed answer!
I have a last question regarding the 1st topic.
Would you unadvise using Vaex as per this use case (applying a function like this, row per row)?
Are there bottlenecks in the way Vaex performs in such situation and you would recommend studying alternatives? (I don't see that many at the moment, but if no other solutions, I could stick to pandas, and batch my calculations)

The `apply` solution with Vaex appears to me 'convenient' (from an implementation point of view) so i would be tempted to follow this direction. Before going further this way, I am curious to hear your general thoughs on the topic.
Thanks again,
Bests,

**Comment by maartenbreddels** [comment]
We've written on apply in the tutorial https://vaex.io/docs/tutorial.html#The-escape-hatch:-apply let us know if you still have questions after that

**Comment by yohplala** [comment]
Hi, should this ticket be kept open till `apply` accept partial? (just not to forgot it?) Thanks, Bests

**Comment by maartenbreddels** [comment]
yes :) thanks

**Comment by yohplala** [comment]
For those interested in the 2nd question of the ticket (Can vaex row results depend on previous results?) , I am attempting to dig deeper in discussion #1458.
