### ISSUE TITLE
[BUG-REPORT] Unable to export dataframe to hdf5 when it includes multibyte named column (on Windows OS)

### ISSUE THREAD

**Issue by SyureNyanko** [vaexio/vaex#1478]
Hi, everyone

**Description**

Runtime Error at h5py when saving dataframe includes many columns, and one of them contains Multibyte string.
It might only happen on Windows. (It didn't happen when I tried it on MacOS and Ubuntu )

```python
import vaex
source_dict = {"東京": [1, 2, 3], "a": [1, 2, 3], "b": [1,2,3], "c": [1, 2, 3], "d": [1, 2, 3], "a1": [1, 2, 3], "b2": [1,2,3], "c3": [1, 2, 3], "d4": [1, 2, 3]}
df = vaex.from_dict(source_dict)
df.export_hdf5("testfile.hdf5")
```
```
Traceback (most recent call last):
  File ".\main.py", line 8, in <module>
    df.export_hdf5("testfile.hdf5")
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\vaex\dataframe.py", line 6486, in export_hdf5
    writer.write(self, chunk_size=chunk_size, progress=progress, column_count=column_count)
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\vaex\hdf5\writer.py", line 40, in __exit__   
    self.close()
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\vaex\hdf5\writer.py", line 31, in close      
    self.h5.close()
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\h5py\_hl\files.py", line 457, in close       
    h5i.dec_ref(id_)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5i.pyx", line 153, in h5py.h5i.dec_ref
RuntimeError: Can't decrement id ref count (unable to extend file properly)
```

**Software information**
 - Vaex version : {'vaex': '4.1.0', 'vaex-core': '4.3.0.post1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.7.0', 'vaex-server': '0.4.1', 'vaex-astro': '0.8.2', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.11.1', 'vaex-arrow': '0.5.1'}
 - Vaex was installed via: pip
 - OS:  Windows 10 Pro (10.0.19042 build 19042)

Thanks!

**Comment by JovanVeljanoski** [comment]
Hi, can you tell us which version of h5py do you have?
(can you perhaps try with a older/newer version of h5py, in case it an issue on that end - but I am just guessing here).

**Comment by SyureNyanko** [comment]
Thank you for your reply. h5py version is 3.1.0
```
>>> import h5py; h5py.__version__ 
'3.1.0'
```

**Comment by JovanVeljanoski** [comment]
Can you try with 2.9.0 please?

**Comment by SyureNyanko** [comment]
h5py==2.10.0,  the same result
```
import vaex
import h5py
print(h5py.__version__) 
source_dict = {"φa": [1, 2, 3], "a": [1, 2, 3], "b": [1,2,3], "c": [1, 2, 3], "d": [1, 2, 3], "a1": [1, 2, 3], "b2": [1,2,3], "c3": [1, 2, 3], "d4": [1, 2, 3]}
df = vaex.from_dict(source_dict)
df.export_hdf5("testfile.hdf5")
```
```
2.10.0
Traceback (most recent call last):
  File ".\main.py", line 9, in <module>
    df.export_hdf5("testfile.hdf5")
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\vaex\dataframe.py", line 6486, in export_hdf5
    writer.write(self, chunk_size=chunk_size, progress=progress, column_count=column_count)
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\vaex\hdf5\writer.py", line 40, in __exit__   
    self.close()
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\vaex\hdf5\writer.py", line 31, in close      
    self.h5.close()
  File "C:\Users\naohiro.heya\.pyenv\pyenv-win\versions\3.8.7\lib\site-packages\h5py\_hl\files.py", line 443, in close       
    h5i.dec_ref(id_)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5i.pyx", line 150, in h5py.h5i.dec_ref
RuntimeError: Can't decrement id ref count (unable to extend file properly)
```

**Comment by JovanVeljanoski** [comment]
Thanks

**Comment by SyureNyanko** [comment]
I submitted a pull request about this issue. I'd be happy review or check it. @JovanVeljanoski

**Comment by maartenbreddels** [comment]
Fixed by https://github.com/vaexio/vaex/pull/1479
