### ISSUE TITLE
[BUG-REPORT] Trouble joining vaex DataFrames on timestamps when they are read from parquet files

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1518]
**Description**
- step1 / When trying to join vaex DataFrames read from parquet files written with fastparquet lib, an exception is raised.
- From the exception raised, and doing test when joining on timestamps or not, I understand that joining on timestamps seems to be a cause, and perhaps timestamp encoding might be the root cause here?
- step2 / But if I join the 'same' DataFrames (pandas DataFrames before they are written as parquet files with fastparquet), join works.
- step3 / And even more disturbing, if with vaex I transform the DataFrames read from parquet files into pandas DataFrames, and I compare them with intial ones using `pd.testing.assert_frame_equals()`, no difference is reported.

Let's review this in python.

```python
import fastparquet as fp
import pandas as pd
import vaex as vx
from os import path as os_path

# Test data (with timestamps...)
ts = pd.date_range(start='2021/01/01 08:00', periods=2, freq='1h')
time = 'time'
val_left = [1, 4]
val_right = [10,40]
df_left = pd.DataFrame({time: ts, 'val': val_left})
df_right = pd.DataFrame({time: ts, 'val': val_right})

# Step 1: writing fastparquet file.
to_file_l = os_path.expanduser('~/Documents/code/data/join_test_l')
fp.write(to_file_l, df_left)
to_file_r = os_path.expanduser('~/Documents/code/data/join_test_r')
fp.write(to_file_r, df_right)

# vaex world: open and join on timestamps.
vdf_l = vx.open(to_file_l)
vdf_r = vx.open(to_file_r)
res = vdf_l.join(vdf_r, rprefix='r_', left_on=time, right_on=time)
```
Error message
```python
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/execution.py", line 194, in execute_async
    async for element in self.thread_pool.map_async(self.process_part, dataset.chunk_iterator(columns, chunk_size),
  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/multithreading.py", line 88, in map_async
    value = await value
  File "/home/yoh/anaconda3/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/home/yoh/anaconda3/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/home/yoh/anaconda3/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/yoh/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/execution.py", line 281, in process_part
    task._parts[thread_index].process(thread_index, i1, i2, filter_mask, *blocks)
  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/cpu.py", line 235, in process
    self.values.append(self._map(thread_index, i1, i2, *blocks))
  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/join.py", line 191, in map
    ar = ar.view(np.uint64)
  File "pyarrow/array.pxi", line 827, in pyarrow.lib.Array.view
  File "pyarrow/types.pxi", line 2530, in pyarrow.lib.ensure_type
TypeError: DataType expected, got <class 'type'>
Traceback (most recent call last):

  File "<ipython-input-13-11f1600b7d2a>", line 3, in <module>
    res = vdf_l.join(vdf_r, rprefix='r_', left_on=time, right_on=time)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 6255, in join
    return vaex.join.join(**kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/join.py", line 207, in join
    left.map_reduce(map, reduce, [left_on], delay=False, name='fill looking', info=True, to_numpy=False, ignore_filter=True)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 393, in map_reduce
    return self._delay(delay, task)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 1537, in _delay
    self.execute()

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 375, in execute
    just_run(self.execute_async())

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()

  File "/home/yoh/anaconda3/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception

  File "/home/yoh/anaconda3/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/dataframe.py", line 380, in execute_async
    await self.executor.execute_async()

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/execution.py", line 194, in execute_async
    async for element in self.thread_pool.map_async(self.process_part, dataset.chunk_iterator(columns, chunk_size),

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/multithreading.py", line 88, in map_async
    value = await value

  File "/home/yoh/anaconda3/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.

  File "/home/yoh/anaconda3/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()

  File "/home/yoh/anaconda3/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception

  File "/home/yoh/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/execution.py", line 281, in process_part
    task._parts[thread_index].process(thread_index, i1, i2, filter_mask, *blocks)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/cpu.py", line 235, in process
    self.values.append(self._map(thread_index, i1, i2, *blocks))

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/vaex/join.py", line 191, in map
    ar = ar.view(np.uint64)

  File "pyarrow/array.pxi", line 827, in pyarrow.lib.Array.view

  File "pyarrow/types.pxi", line 2530, in pyarrow.lib.ensure_type

TypeError: DataType expected, got <class 'type'>
```

Other tests:
- joining directly pandas DataFrames when they are 'converted' to vaex DataFrames is ok.
```python
vdf_l_ = vx.from_pandas(df_left)
vdf_r_ = vx.from_pandas(df_right)    
res = vdf_l_.join(vdf_r_, rprefix='r_', left_on=time, right_on=time)
```

- checking if there might be difference between initial pandas DataFrames and pandas DataFrames derived by vaex from parquet files issues no difference.

```python
vdf_l_p = vdf_l_.to_pandas_df()
pd.testing.assert_frame_equal(df_left, vdf_l_p)
vdf_r_p = vdf_r_.to_pandas_df()
pd.testing.assert_frame_equal(df_right, vdf_r_p)
```

Please, any idea what could be wrong?

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
 {'vaex-core': '4.3.0.post1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.8.0',
 'vaex-server': '0.5.0',
 'vaex-astro': '0.8.2',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.12.0'}

 - Vaex was installed via: conda-forge
 - OS: Ubuntu 20.04

**Comment by yohplala** [comment]
Hi there,
While the bug is still standing, a possible workaround is to force vaex reassessing dtype of timestamps as datetime64.

Doing so, joining works. Here is implemented workaround.
Bests,

```python
    import fastparquet as fp
    import pandas as pd
    import vaex as vx
    from os import path as os_path

    ts = pd.date_range(start='2021/01/01 08:00', periods=2, freq='1h')
    time = 'time'
    val_left = [1, 4]
    val_right = [10,40]
    df_left = pd.DataFrame({time: ts, 'val': val_left})
    df_right = pd.DataFrame({time: ts, 'val': val_right})
    
    # Recording & reading to/from parquet with fastparquet as pandas DataFrame.
    to_file_l = os_path.expanduser('~/Documents/code/data/join_test_l')
    fp.write(to_file_l, df_left)
    to_file_r = os_path.expanduser('~/Documents/code/data/join_test_r')
    fp.write(to_file_r, df_left)
    # vaex world.
    vdf_l = vx.open(to_file_l)
    vdf_l[time] = vdf_l[time].astype('datetime64[ns]')      # /!\ force dtype
    vdf_r = vx.open(to_file_r)
    vdf_r[time] = vdf_r[time].astype('datetime64[ns]')      # /!\ force dtype
    res = vdf_l.join(vdf_r, rprefix='r_', left_on=time, right_on=time)
```

**Comment by JovanVeljanoski** [comment]
I am not near my dev machine today, but out of curiosity, what is `vdf_l[time].dtype`  before you explicitly do `.astype('datetime64[ns]') ?`

If it is something like `object`.. that's the problem. I dont know from the top of my head how the pandas to vaex handles the conversion of datetime or timedelta, but something to look into for sure! 

Thank you!

**Comment by yohplala** [comment]
> I am not near my dev machine today, but out of curiosity, what is `vdf_l[time].dtype` before you explicitly do `.astype('datetime64[ns]') ?`

It seems to confirm a 'real' bug, or I have done something wrong. I get:
```python
vdf_l[time].dtype
Out[3]: datetime64[ns]
```
