### ISSUE TITLE
[Q] Assigning expression.TimeDelta.total_seconds() to a variable resulting AttributeError 

### ISSUE THREAD

**Issue by scicode-zero** [vaexio/vaex#1521]
**Problem** I tried to assign a variable with `expression.TimeDelta.total_seconds()` and the error message says the following: 

`AttributeError: 'pyarrow.lib.DurationArray' object has no attribute 'flags'`

However just printing the object is fine. 
In the full error message there are several times it shows that `During handling of the above exception, another exception occurred:....`. 

**Code** 
```python
import vaex
import numpy as np

df_dict = {"datetime_1": np.array(["2021-01-11T04:05:43",
                                   "2009-03-22T00:54:37",
                                   "2017-12-22T14:46:27"]),
           "datetime_2": np.array(["2011-01-11T04:05:43",
                                   "2019-03-22T00:54:37",
                                   "2037-12-22T14:46:27"])}

df = vaex.from_dict(df_dict)

df["datetime_1"] = df.datetime_1.astype("datetime64")
df["datetime_2"] = df.datetime_2.astype("datetime64")

df["delta"] = df.datetime_2 - df.datetime_1

print(df.delta.td.total_seconds())
print(df.delta.td)

print("\n-------\n")

df["seconds"] = df.delta.td.total_seconds()
print(df)
```

**Output**(The full error message is very long so I put it at the end)
```
td_total_seconds(delta)
<vaex.expression.TimeDelta object at 0x12247c250>

-------

ERROR:MainThread:vaex:error evaluating: seconds at rows 0-3
...
AttributeError: 'pyarrow.lib.DurationArray' object has no attribute 'flags'
  #  datetime_1           datetime_2           delta                 seconds
  0  2021-01-11 04:05:43  2011-01-11 04:05:43  -3653 days +00:00:00  error
  1  2009-03-22 00:54:37  2019-03-22 00:54:37  3652 days 00:00:00    error
  2  2017-12-22 14:46:27  2037-12-22 14:46:27  7305 days 00:00:00    error
```

**Vaex version** (installed via anaconda)
```
{'vaex-core': '4.4.0', 
'vaex-viz': '0.5.0', 
'vaex-hdf5': '0.8.0', 
'vaex-server': '0.5.0', 
'vaex-astro': '0.8.3', 
'vaex-jupyter': '0.6.0', 
'vaex-ml': '0.12.0'}
```

OS system: macOS High Sierra 

**The full error message**
```
ERROR:MainThread:vaex:error evaluating: seconds at rows 0-3
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'td_total_seconds(delta)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2002, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 941, in td_total_seconds
    return _to_pandas_series(x).dt.total_seconds().values
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 284, in _to_pandas_series
    return pd.Series(_pandas_dt_fix(x), dtype=x.dtype)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 277, in _pandas_dt_fix
    if not x.flags['WRITEABLE']:
AttributeError: 'pyarrow.lib.DurationArray' object has no attribute 'flags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'td_total_seconds(delta)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 3815, in table_part
    values = dict(zip(column_names, df.evaluate(column_names)))
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 6022, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2004, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 941, in td_total_seconds
    return _to_pandas_series(x).dt.total_seconds().values
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 284, in _to_pandas_series
    return pd.Series(_pandas_dt_fix(x), dtype=x.dtype)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 277, in _pandas_dt_fix
    if not x.flags['WRITEABLE']:
AttributeError: 'pyarrow.lib.DurationArray' object has no attribute 'flags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'td_total_seconds(delta)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2002, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 941, in td_total_seconds
    return _to_pandas_series(x).dt.total_seconds().values
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 284, in _to_pandas_series
    return pd.Series(_pandas_dt_fix(x), dtype=x.dtype)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 277, in _pandas_dt_fix
    if not x.flags['WRITEABLE']:
AttributeError: 'pyarrow.lib.DurationArray' object has no attribute 'flags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'td_total_seconds(delta)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 3820, in table_part
    values[name] = df.evaluate(name)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 6022, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2004, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 941, in td_total_seconds
    return _to_pandas_series(x).dt.total_seconds().values
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 284, in _to_pandas_series
    return pd.Series(_pandas_dt_fix(x), dtype=x.dtype)
  File "/opt/anaconda3/envs/ADS/lib/python3.8/site-packages/vaex/functions.py", line 277, in _pandas_dt_fix
    if not x.flags['WRITEABLE']:
```

**Comment by JovanVeljanoski** [comment]
Can you create a reproducible example, and answer the questions in the issue form?

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks @scicode-zero for raising this. An interesting issue. Actually I am not sure if this is a bug or a feature :D, but it looks like a bug to me :)

The workaround for now is to make sure that the data you are using to create a vaex dataframe is already has the right data type, rather then casting it once in the dataframe. For you that means making this adjustment:

```python
df_dict = {"datetime_1": np.array(["2021-01-11T04:05:43",
                                   "2009-03-22T00:54:37",
                                   "2017-12-22T14:46:27"], dtype=np.timedelta64),
           "datetime_2": np.array(["2011-01-11T04:05:43",
                                   "2019-03-22T00:54:37",
                                   "2037-12-22T14:46:27"], dtype=np.timedelta64)}
```

@maartenbreddels This is an interesting case, but I don't know if my interpretation is correct. 
So what happens here, we have a initially a string (handled by arrow internally), that is cast to `datetime64` handled by numpy. 

So then when one does: `df["delta"] = df.datetime_2 - df.datetime_1`, `df.delta.dtype` is not `timedelta64` but something called `duration[ns]` which i think (but not sure) is an arrow data type. Thus `df.delta.td.total_seconds()` does not work (or any other timedelta method). 

Casting the `delta` expression to `timedelta64` also fails, maybe we do not support casting to `timedelta64`?

Anyway, something for us to look into. Maybe one day we can outsource all datetime/timedelta operations to arrow but maybe for now it would be better if everything worked through numpy/pandas?
