### ISSUE TITLE
[BUG-REPORT] Cannot filter dataframe by a dictionary column

### ISSUE THREAD

**Issue by rosstitmarsh** [vaexio/vaex#1528]
**Description**
Created a parquet file using pyarrow with a dictionary type column, opened it with Vaex successfully but cannot then filter or group by the dictionary column. Simple filter example shown below.

Minimal code example:

1. Create parquet dataset
```python
import pyarrow as pa
import pyarrow.parquet as pq
import vaex
import numpy as np

schema = pa.schema({
    'col1': pa.int32(),
    'col2': pa.float32(),
    'col3': pa.dictionary(pa.int16(), pa.string()),
})

table = pa.table({
    'col1': range(10),
    'col2': np.random.randn(10),
    'col3': list(np.random.choice(['A', 'B', 'C'], 10)),
}, schema=schema)

pq.write_table(table, 'test.parquet')
```
2. Show dataframe
```python
df = vaex.open('test.parquet')
print(df)
print(df.dtypes)
```
```
  #    col1       col2  col3
  0       0  -1.69965   A
  1       1  -0.711488  B
  2       2  -0.62356   C
  3       3  -0.262011  A
  4       4  -0.875539  A
  5       5  -2.10895   C
  6       6  -0.404066  A
  7       7  -0.400343  C
  8       8   0.618483  B
  9       9   0.220107  C
col1                                                int32
col2                                              float32
col3    dictionary<values=string, indices=int32, order...
dtype: object
```
3. Filter by dictionary column
```python
df = vaex.open('test.parquet')
dff = df[df.col3 == 'A']
print(dff)
```
```
$ .venv/Scripts/python.exe dictionary_test.py 
  File "C:\Program Files\Python39\lib\threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 77, in _worker
    work_item.run()
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "<project dir>\.venv\lib\site-packages\vaex\execution.py", line 263, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2811, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 188, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 226, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2797, in _evaluate_selection_mask
    mask = scope.evaluate(name)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 191, in evaluate
    tb.print_stack()
Traceback (most recent call last):
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 226, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2797, in _evaluate_selection_mask
    mask = scope.evaluate(name)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 188, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 130, in decorated
    return f(x, *args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 1037, in str_equals
    x = _to_string_sequence(x)
  File "<project dir>\.venv\lib\site-packages\vaex\column.py", line 510, in _to_string_sequence
    return convert.column_from_arrow_array(x).string_sequence
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 84, in column_from_arrow_array
    return numpy_array_from_arrow_array(arrow_array)
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 124, in numpy_array_from_arrow_array
    dtype = arrow_array.type.to_pandas_dtype()
  File "pyarrow\types.pxi", line 200, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: dictionary<values=string, indices=int32, ordered=0>
ERROR:ThreadPoolExecutor-1_0:vaex.scopes:error in evaluating: '__filter__'
Traceback (most recent call last):
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 226, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2797, in _evaluate_selection_mask
    mask = scope.evaluate(name)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 188, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 130, in decorated
    return f(x, *args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 1037, in str_equals
    x = _to_string_sequence(x)
  File "<project dir>\.venv\lib\site-packages\vaex\column.py", line 510, in _to_string_sequence
    return convert.column_from_arrow_array(x).string_sequence
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 84, in column_from_arrow_array
    return numpy_array_from_arrow_array(arrow_array)
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 124, in numpy_array_from_arrow_array
    dtype = arrow_array.type.to_pandas_dtype()
  File "pyarrow\types.pxi", line 200, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: dictionary<values=string, indices=int32, ordered=0>
  File "C:\Program Files\Python39\lib\threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 77, in _worker
    work_item.run()
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "<project dir>\.venv\lib\site-packages\vaex\execution.py", line 263, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2811, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 191, in evaluate
    tb.print_stack()
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "<project dir>\.venv\lib\site-packages\vaex\execution.py", line 194, in execute_async
    async for element in self.thread_pool.map_async(self.process_part, dataset.chunk_iterator(columns, chunk_size),
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 88, in map_async
    value = await value
  File "C:\Program Files\Python39\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "C:\Program Files\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "<project dir>\.venv\lib\site-packages\vaex\execution.py", line 263, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2811, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 188, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 226, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2797, in _evaluate_selection_mask
    mask = scope.evaluate(name)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 188, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 130, in decorated
    return f(x, *args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 1037, in str_equals
    x = _to_string_sequence(x)
  File "<project dir>\.venv\lib\site-packages\vaex\column.py", line 510, in _to_string_sequence
    return convert.column_from_arrow_array(x).string_sequence
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 84, in column_from_arrow_array
    return numpy_array_from_arrow_array(arrow_array)
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 124, in numpy_array_from_arrow_array
    dtype = arrow_array.type.to_pandas_dtype()
  File "pyarrow\types.pxi", line 200, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: dictionary<values=string, indices=int32, ordered=0>
Traceback (most recent call last):
  File "<project dir>\dictionary_test.py", line 30, in <module>
    print(dff)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 3906, in __str__
    return self._head_and_tail_table(format='plain')
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 3662, in _head_and_tail_table
    N = _len(self)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 67, in _len
    return o.__len__()
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 3998, in __len__
    self. _cached_filtered_length = int(self.count())
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 799, in count
    return self._compute_agg('count', expression, binby, limits, shape, selection, delay, edges, progress, array_type=array_type)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 773, in _compute_agg
    return self._delay(delay, var)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 1537, in _delay
    self.execute()
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 375, in execute
    just_run(self.execute_async())
  File "<project dir>\.venv\lib\site-packages\vaex\asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "<project dir>\.venv\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "C:\Program Files\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 380, in execute_async
    await self.executor.execute_async()
  File "<project dir>\.venv\lib\site-packages\vaex\execution.py", line 194, in execute_async
    async for element in self.thread_pool.map_async(self.process_part, dataset.chunk_iterator(columns, chunk_size),
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 88, in map_async
    value = await value
  File "C:\Program Files\Python39\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\Program Files\Python39\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "C:\Program Files\Python39\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 84, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in iterator)
  File "<project dir>\.venv\lib\site-packages\vaex\multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "<project dir>\.venv\lib\site-packages\vaex\execution.py", line 263, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2811, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 188, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 226, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "<project dir>\.venv\lib\site-packages\vaex\dataframe.py", line 2797, in _evaluate_selection_mask
    mask = scope.evaluate(name)
  File "<project dir>\.venv\lib\site-packages\vaex\scopes.py", line 188, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 130, in decorated
    return f(x, *args, **kwargs)
  File "<project dir>\.venv\lib\site-packages\vaex\functions.py", line 1037, in str_equals
    x = _to_string_sequence(x)
  File "<project dir>\.venv\lib\site-packages\vaex\column.py", line 510, in _to_string_sequence
    return convert.column_from_arrow_array(x).string_sequence
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 84, in column_from_arrow_array
    return numpy_array_from_arrow_array(arrow_array)
  File "<project dir>\.venv\lib\site-packages\vaex\arrow\convert.py", line 124, in numpy_array_from_arrow_array
    dtype = arrow_array.type.to_pandas_dtype()
  File "pyarrow\types.pxi", line 200, in pyarrow.lib.DataType.to_pandas_dtype
NotImplementedError: dictionary<values=string, indices=int32, ordered=0>
```

**Software information**
 - Vaex version:
 {'vaex': '4.3.0',
 'vaex-core': '4.3.0.post1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.8.0',
 'vaex-server': '0.5.0',
 'vaex-astro': '0.8.2',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.12.0'}
 - Vaex was installed via: pip 
 - OS: Windows 10 19042.1110

**Additional information**
If you cast the dictionary column to a string `df.col3 = df.col.astype('string')` it will work for filtering and grouping but a proper dictionary version should be more performant. Also saves the need to cast the column back to a dictionary to write the file again.

**Comment by kmcentush** [comment]
Is the intent to filter by the value of the dictionary column? Or are there also some use cases for filtering by key as well? I'm trying to scope what a proper solution would solve.

**Comment by JovanVeljanoski** [comment]
I am not sure if we have proper support for arrow dictionaries tho.. I know support for arrow structs was recently added.. so maybe something similar is needed for arrow dictionaries?

**Comment by maartenbreddels** [comment]
Yes, we do support it a bit, note that this should work with. The problem is we don't recognize this with `df.is_category` due to the parquet columns not being in memory.

**Comment by kmcentush** [comment]
I'll take a stab at fixing this.
