### ISSUE TITLE
Calculating Cosine Similarity

### ISSUE THREAD

**Issue by aclifton314** [vaexio/vaex#1558]
**Description**
I am wondering if there is a way to calculate cosine similarity using vaex? Suppose I have the following:
```python
import pandas as pd
import vaex
import numpy as np


def calc_cos_sim_vaex(embed_a, embed_b):
   ???

tmp_df = pd.read_pickle('./embed_pairs_df.pkl')
embed_pairs_df_vaex = vaex.from_pandas(tmp_df)
embed_pairs_df_vaex['cos_sims'] = calc_cos_sim_vaex(embed_pairs_df_vaex['embeds_a'], embed_pairs_df_vaex['embeds_b'])
```
What would the `calc_cos_sim_vaex()` implementation look like? The data in `embed_pairs_df_vaex['embeds_a']` and `embed_pairs_df_vaex['embeds_b']` are 1x300 numpy arrays and there are 1 million of these.  So `embed_pairs_df_vaex['embeds_a'].shape` is `(1000000, 1)` and so is `embed_pairs_df_vaex['embeds_b']`, but each element in `embed_pairs_df_vaex['embeds_a']` or `embed_pairs_df_vaex['embeds_b']` is a 1x300 numpy array.

I tried implementing something by hand:
```python
def calc_cos_sim_vaex(embed_a, embed_b):
      cos_sim = np.dot(embed_a, embed_b)/(np.linalg.norm(embed_a)*np.linalg.norm(embed_b))
      return cos_sim
```
but I get the following error:
```python
ERROR:Thread-7:vaex:error evaluating: cos_sims at rows 0-5
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2002, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 3815, in table_part
    values = dict(zip(column_names, df.evaluate(column_names)))
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6022, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2004, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2002, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 3820, in table_part
    values[name] = df.evaluate(name)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6022, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2004, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
ERROR:Thread-7:vaex:error evaluating: cos_sims at rows 999995-1000000
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2002, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 3815, in table_part
    values = dict(zip(column_names, df.evaluate(column_names)))
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6022, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2004, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2002, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '((embeds_a * embeds_b) / (sqrt((embeds_a * embeds_a)) * sqrt((embeds_b * embeds_b))))'"
During handling of the above exception, another exception occurred:
AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 3820, in table_part
    values[name] = df.evaluate(name)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6022, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2004, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/aclifton/anaconda3/lib/python3.7/site-packages/vaex/functions.py", line 95, in wrapper
    result = function(*numpy_data, **kwargs)
TypeError: loop of ufunc does not support argument 0 of type numpy.ndarray which has no callable sqrt method
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.4.0
 - Vaex was installed via: pip 
 - OS: Pop!_OS 20.04 LTS

Thanks in advance for your help!

**Comment by aclifton314** [comment]
Any thoughts on this?

**Comment by JovanVeljanoski** [comment]
Hi @aclifton314 

This is an interesting problem. In the past I was thinking of how such things can be used for clustering algorithms for example.

In any case, I'm at capacity of what I can take on right now.. not sure if @maartenbreddels can offer any advice. 

I would say you can look at  transformations.py in vaex-ml, and there is a function that does a dot product (`dot_product`). You can try using that, although depending on the dimensions of your space, you might run into the "too many parentheses problem" which we still have not solved.. 

Also, if possible can you provide a (very) small sample of your data just to try things out if we get time? Would be much easier to develop that way.

**Comment by maartenbreddels** [comment]
Did you try passing in numpy arrays to test your function? Also,  I don't understand your shapes. Maybe you can generate a full code example that generates some game data, now it's very difficult for us to reproduce.

**Comment by aclifton314** [comment]
@maartenbreddels @JovanVeljanoski I am happy to provide whatever is needed. Below you will find a short example script:
```python
import pandas as pd
import vaex
import numpy as np

def dot_test(embed_a, embed_b):
    tmp_dot = np.dot(embed_a, embed_b)
    return tmp_dot

tmp_df = pd.read_pickle('./embed_pairs_df_100.pkl')
print(tmp_df.shape)

embed_a = tmp_df['embeds_a'][0]
embed_b = tmp_df['embeds_b'][31]

np_dot_test = dot_test(embed_a, embed_b)
print('np_dot_test = {}'.format(np_dot_test))

vaex_df = vaex.from_pandas(tmp_df)
vaex_df['dots'] = dot_test(vaex_df.embeds_a, vaex_df.embeds_b)
print(vaex_df['dots'].shape)
print(vaex_df['dots'].values[0].shape)
```
And I have also attached a very small sample dataset to play with:
[embed_pairs_df_100.zip](https://github.com/vaexio/vaex/files/7157167/embed_pairs_df_100.zip)

Each row of `tmp_df` contains a numpy array of size (300,).  `dot_test()` should return a scalar, which does occur when using the straight numpy approach. However, it looks to be doing elementwise multiplication whenever I pass in the columns from the vaex dataframe.

**Comment by maartenbreddels** [comment]
> embed_pairs_df_100.zip

I cannot open this file because it's pickle, which is not safe (it allows for arbitrary code execution), please provide a csv/hdf5/parquet file next time. 



It would be great if some fake data can just be generated using np.random instead, that saves me time having to download files.

**Comment by Ben-Epstein** [comment]
@maartenbreddels  I'd imagine the dataframe being referenced here looks like this 

```
import vaex
import numpy as np
from random import random


NUM_SAMPLES = 1000 # more from the description but isn't really relevant
WIDTH = 300

embeds_a = [np.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)]
embeds_b = [np.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)]
ids = list(range(NUM_SAMPLES))
data = {
    'embeds_a': embeds_a,
    'embeds_b': embeds_b,
    'id': ids
}
df = vaex.from_pandas(pd.DataFrame(data))
```

Does that help?

**Comment by maartenbreddels** [comment]
What about this:
```
import pandas as pd
import vaex
import numpy as np
from random import random

def dot_test(embed_a, embed_b):
    tmp_dot = np.dot(embed_a, embed_b)
    return tmp_dot

# tmp_df = pd.read_pickle('./embed_pairs_df_100.pkl')
# print(tmp_df.shape)
NUM_SAMPLES = 1000 # more from the description but isn't really relevant
WIDTH = 300

embeds_a = [np.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)]
embeds_b = [np.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)]
ids = list(range(NUM_SAMPLES))
data = {
    'embeds_a': embeds_a,
    'embeds_b': embeds_b,
    'id': ids
}
df = vaex.from_dict(data)

@vaex.register_function()
def mydot(a, b):
    return np.sum(a * b, axis=1)
df['dot'] = df.embeds_a.mydot(df.embeds_b)
print(df)
```
the trick is, because Vaex will pass the function mydot chunks of data, to use the `sum(..., axis=1)`, does that make sense?

**Comment by Ben-Epstein** [comment]
@maartenbreddels  that works! but when I try to use that virtual column in a way such that it is actually calculated the memory explodes..

```
df['dot'] = df.embeds_a.mydot(df.embeds_b)
df = df.sort(by='dot') # memory explosion
```

Any ideas why?

**Comment by maartenbreddels** [comment]
sort does use some memory, what do you mean by explosion,it will most likely take 8 bytes * len(df) of RAM for the indices, does it take more?

**Comment by Ben-Epstein** [comment]
@maartenbreddels I'm seeing RAM usage up to 35GB. I'm testing with a ~36,000,000 length dataframe.

**Comment by Ben-Epstein** [comment]
I took the example above and just kept doubling it, then exported it to hdf5. I kept this running a big longer and it just kept getting bigger, eventually crashing jupyter.


https://user-images.githubusercontent.com/22605641/140429671-1bffe736-61df-40cc-a716-c898fc21ef69.mov

https://user-images.githubusercontent.com/22605641/140429722-8ddc5ce7-c155-46cc-abcc-cb5c39493d71.mov

**Comment by aclifton314** [comment]
I'll give that trick a shot and see if it works. Ultimately, I will have to take a square root to calculate the cosine similarity. How should I take the square root of the dot product in vaex?

**Comment by maartenbreddels** [comment]
`df.x**0.5` or `np.sqrt(df.x)` should work
