### ISSUE TITLE
[BUG-REPORT] - Using virtual column after conversion to datetime64[ns] returns KeyError

### ISSUE THREAD

**Issue by harshasridhar** [vaexio/vaex#1582]
**Description**
Converting the column datatype from string to 'datetime64[ns]' and accessing the date functions returns a KeyError.
The attached code snippet shows the conversion and the usage.

**Software information**
 - Vaex version :
 ```python
{
'vaex': '4.5.0',
 'vaex-core': '4.5.1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.10.0',
 'vaex-server': '0.6.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.14.0'
}
```
 - Vaex was installed via: pip on Google Colab
 - OS: Linux

**Additional information**
Using virtual column after conversion to datetime returns KeyError
```python
import vaex
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
data=vaex.open('2017_yellow_combined.csv.hdf5')
data['hour_of_day'] = data.tpep_pickup_datetime.astype('datetime64[ns]').dt.hour
->plt.hist2d(data.hour_of_day.values,data.DOLocationID.values,norm=LogNorm())
```
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/vaex/scopes.py in evaluate(self, expression, out)
    105             # logger.debug("try avoid evaluating: %s", expression)
--> 106             result = self[expression]
    107         except KeyError:

27 frames
KeyError: 'Unknown variables or column: "dt_hour(astype(tpep_pickup_datetime, \'datetime64[ns]\'))"'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<string> in <module>

AttributeError: 'pyarrow.lib.TimestampArray' object has no attribute 'flags'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
KeyError: 'Unknown variables or column: "dt_hour(astype(tpep_pickup_datetime, \'datetime64[ns]\'))"'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<string> in <module>

/usr/local/lib/python3.7/dist-packages/vaex/functions.py in _pandas_dt_fix(x)
    275     # see https://github.com/pandas-dev/pandas/issues/23276
    276     # not sure which version this is fixed in
--> 277     if not x.flags['WRITEABLE']:
    278         x = x.copy()
    279     return x

AttributeError: 'pyarrow.lib.TimestampArray' object has no attribute 'flags'
```
data.info gives the same error(post executing line 5), nevertheless the column 'hour_of_day' is a virtual column 
hour_of_day	virtual column		dt_hour(astype(tpep_pickup_datetime, 'datetime64[ns]'))

**Comment by JovanVeljanoski** [comment]
Hi, 

Can you perhaps try like this:

```python
data.tpep_pickup_datetime.astype('datetime64').dt.hour
```

(so without the [ns] bit)

**Comment by harshasridhar** [comment]
Hi @JovanVeljanoski 
I'm still facing the same error

**Comment by JovanVeljanoski** [comment]
I can reproduce it - thanks!

**Comment by JovanVeljanoski** [comment]
This has now been fixed and will be part of the next release. Thanks!

**Comment by harshasridhar** [comment]
@JovanVeljanoski Since the merge is done, can I use the dev build for now?
Also any estimate of when the next release will go live?

**Comment by BrechtDeVlieger** [comment]
Hi, there's a similar issue when using `df.my_col.td.days` that is not solved by this fix yet. Perhaps it's better to cast all `pa.lib.Array` types to pandas?

```python
my_df['duration'] = (my_df['timestamp_begin'] - my_df['timestamp_begin_min']).td.days
my_df.info()
```

```python
ERROR:MainThread:vaex:error evaluating: days_active at rows 0-5
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/scopes.py", line 113, in evaluate
    result = self[expression]
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/scopes.py", line 198, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'td_days((timestamp_begin - timestamp_begin_min))'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/dataframe.py", line 2062, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/dataframe.py", line 2869, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/dataframe.py", line 6151, in _evaluate_implementation
    value = block_scope.evaluate(expression)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/scopes.py", line 113, in evaluate
    result = self[expression]
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/scopes.py", line 188, in __getitem__
    values = self.evaluate(expression)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/scopes.py", line 119, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/functions.py", line 834, in td_days
    return _to_pandas_series(x).dt.days.values
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/functions.py", line 295, in _to_pandas_series
    x = _pandas_dt_fix(x)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/vaex/functions.py", line 288, in _pandas_dt_fix
    if not x.flags['WRITEABLE']:
AttributeError: 'pyarrow.lib.DurationArray' object has no attribute 'flags'
```
