### ISSUE TITLE
[BUG-REPORT] Accessing column values gives: AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by abf7d** [vaexio/vaex#1592]
**Description**
I have a 14 million row dataset in which I loaded from a feather file. I'm trying to detect which points are in a polygon, but am running into an error. Here is sample code which I used:
```
 px = np.array([1.5, 2.5, 2.5, 1.5])
 py = np.array([2.5, 2.5, 3.5, 3.5])
 df = vaex.from_arrays(x=[1, 2, 3], y=[2, 3, 4])
 df['inside'] = df.geo.inside_polygon(df['x'], df['y'], px, py)
 print(str(df))
```
This code is successful and prints out the dataframe with the `inside` virtual column. However, when I try to initialize the dataframe by loading my file instead using from_arrays, I get the error ` AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute 'dtype'`. Here is my code
```
 df = vaex.open(path)
 df['mask'] = df.geo.inside_polygon(df['filecol1'], df['filecol2'], px, py)
 print(str(df))
```
The last line crashes (I'm guessing because it is trying to load the values from the virtual column into memory). I do not know why this is happening. I am able to bin the data from the file with the following code:
```
hist = df.count(
    binby=axes,
    limits=limits,
    shape=(binnum,)*len(axes) 
)
```
This this line successfully gives binned data. Even just trying to access the values from the virtual column throws the same error: 
```
 z = df['inside'].values
```
How can I access which points are within the given polygon from my file loaded data?

**Software information**
 - Vaex version 4.4.0
 - Vaex was installed via: pip
 - OS: Windows

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by Nicholas-Schaub** [comment]
I also ran into this issue. I did a little debugging and discovered that there appears to be an issue with how the expressions are being processed in the `geo` module.

I added some debug logs to track down what the issue is, and it looks like it is trying to search for column names in an empty dataframe. It seems like the original dataframe is maybe getting letting somewhere. The first error that get's thrown is a key error, and it cannot find the expression in the dataframe. However, the debug logs actually show this error occurs many times, even for the original columns that were passed in as `x` and `y`.

Here is the full traceback I was receiving when trying to reproduce:

```
Traceback (most recent call last):
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 106, in evaluate
    result = self[expression]
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 167, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: 'Unknown variables or column: "inside_polygon(\'Area_um_sqd\', \'Intensity_Mean_Image_1_Channel_2\', arg_numpy_array, arg_numpy_array_1)"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 2010, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 2851, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 6099, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\geo.py", line 400, in geo_inside_polygon
    x = as_flat_array(x, np.float64)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\utils.py", line 814, in as_flat_array
    if a.dtype.type == dtype and a.strides[0] == 8:
AttributeError: 'str' object has no attribute 'dtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 106, in evaluate
    result = self[expression]
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 167, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: 'Unknown variables or column: "inside_polygon(\'Area_um_sqd\', \'Intensity_Mean_Image_1_Channel_2\', arg_numpy_array, arg_numpy_array_1)"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\plots-explorer-api\core\test.py", line 19, in <module>
    print(df_selection.evaluate())
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\expression.py", line 822, in evaluate
    return self.ds.evaluate(self, i1, i2, out=out, selection=selection, array_type=array_type, parallel=parallel)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 2851, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 6011, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 2012, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 2851, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 6099, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\arrow\numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\geo.py", line 400, in geo_inside_polygon
    x = as_flat_array(x, np.float64)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\utils.py", line 814, in as_flat_array
    if a.dtype.type == dtype and a.strides[0] == 8:
AttributeError: 'str' object has no attribute 'dtype'
```

**Comment by maartenbreddels** [comment]
Hi Aaron and Nicholas,

thanks for reporting, and looking into this. This indeed seems like a bug, I think step 1 would be to change the testing, so we catch this. Instead of doing `df = vaex.from_arrays(x=[1, 2, 3], y=[2, 3, 4])` in `tests/geo_test.py` we should use the df_factory fixture instead (search the codebase to see how we use it). Calling that, our tests should expose the issue, and we can see if we can fix it together. Do you want to open a PR? See #1365 for our updated contributing docs.
Don't be afraid to open a PR that only exposes the failure, without a fix, I'm already super happy with failing tests!

Regards,

Maarten

**Comment by abf7d** [comment]
Thanks @maartenbreddels!

**Comment by abf7d** [comment]
I saw the PR comments and replaced all `vaex.from_arrays` with `df_factory`. Thanks!
