### ISSUE TITLE
[BUG-REPORT] DataFrame.apply crashes when the column name has spaces in it

### ISSUE THREAD

**Issue by eff-kay** [vaexio/vaex#1596]
**Description**
When trying to execute the following code with data

```
import vaex

vaex_df = vaex.from_dict(
    {
        "g1 space": ["a", "a", "b", "b", "a"],
        "g2": ["c", "d", "c", "d", "c"],
        "g3 space": ["c", None, "c", "d", "c"],
    }
)


def unique_or_other(g1, g2, g3):
    if g3 == "c":
        return "OTHER"
    else:
        return g1


vaex_df["g4"] = vaex_df.apply(unique_or_other, arguments=["g1 space", "g2", "g3 space"])


print(vaex_df)
```

Results in the following error

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/scopes.py", line 166, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'lambda_function(g1 space, g2, g3 space)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/dataframe.py", line 3820, in table_part
    values[name] = df.evaluate(name)
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/dataframe.py", line 6022, in _evaluate_implementation
    dtypes[expression] = dtype = df.data_type(expression).internal
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/dataframe.py", line 2004, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/dataframe.py", line 2850, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/dataframe.py", line 6110, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/scopes.py", line 106, in evaluate
    result = self[expression]
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/scopes.py", line 156, in __getitem__
    values = self.evaluate(expression)
  File "/Users/faizank/workspace/plotly/dashboard-engine/sample-runnable-app/venv/lib/python3.6/site-packages/vaex/scopes.py", line 112, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1
    lambda_function(g1 space, g2, g3 space)
```

**Software information**
 - Vaex version {'vaex': '4.5.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0'}
 - Vaex was installed via: pip
 - OS: BigSure 11.2.2

**Comment by maartenbreddels** [comment]
What about 
```
df.apply(unique_or_other, arguments=[df["g1 space"], "g2", df["g3 space"]])
```
Does that work?

**Comment by eff-kay** [comment]
It worked :D

**Comment by eff-kay** [comment]
Wait, it works for this data test but for some reason it does not work with a different dataset. Trying to reproduce that error.

**Comment by eff-kay** [comment]
Ok, sorry I was using a different environment for the different dataset. 

So the above solution works with Vaex==4.4.0, python==3.6.8. 

Produces the same error with Vaex==4.5.1, python==3.8
