### ISSUE TITLE
[BUG-REPORT] Installation Error Running setup.py develop for vaex-meta

### ISSUE THREAD

**Issue by abf7d** [vaexio/vaex#1621]
**Description**
I am trying to install Vaex from the source so I can contribute to the project. I followed the instructions in the CONTRIBUTING.md file. I cloned the repo and created a virual enviorment. The next command fails:

 pip install -e .[dev]

When pip runs one of the first messages is : 

```
Obtaining file:///C:/Work/sandbox/experiments/vaex
Requirement already satisfied: pip in c:\python\lib\site-packages (from vaex-meta==0.1.0) (20.2.3)```
```

This says that a vaex-meta requirement is already satisfied. As the resources go on and install it looks like there is a problem running setup.py for vaex meta (see the stacktrace below).
 
I cloned with `--recursive` and my terminal has admin privileges.

**Software information**
 - Vaex version 4.5.0:
 - Vaex was installed via: from source 
 - OS: Windows

**Additional information**

```
Installing collected packages: vaex-meta
  Running setup.py develop for vaex-meta
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\friedmanab\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Work\\sandbox\\experiments\\vaex\\setup.py'"'"'; __file__='"'"'C:\\Work\\sandbox\\experiments\\vaex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Work\sandbox\experiments\vaex\
    Complete output (210 lines):
    running develop
    Obtaining file:///C:/Work/sandbox/experiments/vaex/packages/vaex-core
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'done'
    Requirement already satisfied: aplus in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (0.11.0)
    Requirement already satisfied: filelock in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (3.3.0)
    Requirement already satisfied: tabulate>=0.8.3 in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (0.8.9)
    Requirement already satisfied: frozendict in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (2.0.6)
    Requirement already satisfied: requests in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (2.26.0)
    Requirement already satisfied: numpy>=1.16 in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (1.21.2)
    Requirement already satisfied: pandas in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (1.3.3)
    Requirement already satisfied: pyyaml in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (5.4.1)
    Requirement already satisfied: progressbar2 in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (3.53.3)
    Requirement already satisfied: cloudpickle in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (2.0.0)
    Requirement already satisfied: dask in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (2021.9.1)
    Requirement already satisfied: six in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (1.16.0)
    Requirement already satisfied: blake3 in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (0.2.0)
    Requirement already satisfied: pyarrow>=3.0 in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (5.0.0)
    Requirement already satisfied: nest-asyncio>=1.3.3 in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (1.5.1)
    Requirement already satisfied: future>=0.15.2 in c:\python\lib\site-packages (from vaex-core==4.6.0a2) (0.18.2)
    Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in c:\python\lib\site-packages (from requests->vaex-core==4.6.0a2) (2.0.6)
    Requirement already satisfied: certifi>=2017.4.17 in c:\python\lib\site-packages (from requests->vaex-core==4.6.0a2) (2021.5.30)
    Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\lib\site-packages (from requests->vaex-core==4.6.0a2) (1.26.7)
    Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in c:\python\lib\site-packages (from requests->vaex-core==4.6.0a2) (3.2)
    Requirement already satisfied: python-dateutil>=2.7.3 in c:\python\lib\site-packages (from pandas->vaex-core==4.6.0a2) (2.8.2)
    Requirement already satisfied: pytz>=2017.3 in c:\python\lib\site-packages (from pandas->vaex-core==4.6.0a2) (2021.3)
    Requirement already satisfied: python-utils>=2.3.0 in c:\python\lib\site-packages (from progressbar2->vaex-core==4.6.0a2) (2.5.6)
    Requirement already satisfied: fsspec>=0.6.0 in c:\python\lib\site-packages (from dask->vaex-core==4.6.0a2) (2021.10.0)
    Requirement already satisfied: partd>=0.3.10 in c:\python\lib\site-packages (from dask->vaex-core==4.6.0a2) (1.2.0)
    Requirement already satisfied: toolz>=0.8.2 in c:\python\lib\site-packages (from dask->vaex-core==4.6.0a2) (0.11.1)
    Requirement already satisfied: packaging>=20.0 in c:\python\lib\site-packages (from dask->vaex-core==4.6.0a2) (21.0)
    Requirement already satisfied: locket in c:\python\lib\site-packages (from partd>=0.3.10->dask->vaex-core==4.6.0a2) (0.2.1)
    Requirement already satisfied: pyparsing>=2.0.2 in c:\python\lib\site-packages (from packaging>=20.0->dask->vaex-core==4.6.0a2) (2.4.7)
    Installing collected packages: vaex-core
      Running setup.py develop for vaex-core
        ERROR: Command errored out with exit status 1:
         command: 'C:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Work\\sandbox\\experiments\\vaex\\packages\\vaex-core\\setup.py'"'"'; __file__='"'"'C:\\Work\\sandbox\\experiments\\vaex\\packages\\vaex-core\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
             cwd: C:\Work\sandbox\experiments\vaex\packages\vaex-core\
        Complete output (148 lines):
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\setup.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
          import imp
        C:\Users\friedmanab\AppData\Local\Temp\pip-build-env-e0tylw52\overlay\Lib\site-packages\setuptools\dist.py:487: UserWarning: Normalizing '4.6.0-alpha.2' to '4.6.0a2'
          warnings.warn(tmpl.format(**locals()))
        running develop
        running egg_info
        creating vaex_core.egg-info
        writing vaex_core.egg-info\PKG-INFO
        writing dependency_links to vaex_core.egg-info\dependency_links.txt
        writing entry points to vaex_core.egg-info\entry_points.txt
        writing requirements to vaex_core.egg-info\requires.txt
        writing top-level names to vaex_core.egg-info\top_level.txt
        writing manifest file 'vaex_core.egg-info\SOURCES.txt'
        package init file 'vaex\arrow\__init__.py' not found (or not a regular file)
        reading manifest file 'vaex_core.egg-info\SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no files found matching '*.c' under directory 'vendor'
        warning: no files found matching '*.h' under directory 'src'
        warning: no files found matching '*.c' under directory 'src'
        adding license file 'LICENSE.txt'
        writing manifest file 'vaex_core.egg-info\SOURCES.txt'
        running build_ext
        building 'vaex.vaexfast' extension
        creating build
        creating build\temp.win-amd64-3.9
        creating build\temp.win-amd64-3.9\Release
        creating build\temp.win-amd64-3.9\Release\src
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\friedmanab\AppData\Local\Temp\pip-build-env-e0tylw52\overlay\Lib\site-packages\numpy\core\include -IC:\python\include -IC:\python\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include -IC:\Program Files 
(x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files 
(x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpsrc\vaexfast.cpp /Fobuild\temp.win-amd64-3.9\Release\src\vaexfast.obj /EHsc
        vaexfast.cpp
        src\vaexfast.cpp(18): warning C4005: 'INFINITY': macro redefinition
        C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_math.h(90): note: see previous definition of 'INFINITY'
        C:\Users\friedmanab\AppData\Local\Temp\pip-build-env-e0tylw52\overlay\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION     
        src\vaexfast.cpp(201): warning C4244: 'argument': conversion from '__int64' to 'int', possible loss of data
        src\vaexfast.cpp(532): warning C4244: 'argument': conversion from '__int64' to 'const int', possible loss of data
        src\vaexfast.cpp(956): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
        src\vaexfast.cpp(1798): warning C4244: 'argument': conversion from '__int64' to 'int', possible loss of data
        src\vaexfast.cpp(1798): warning C4244: 'argument': conversion from '__int64' to 'int', possible loss of data
        src\vaexfast.cpp(64): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(198): note: see reference to function template instantiation 'void object_to_numpy1d_nocopy<double>(T *&,PyObject *,__int64 &,int &,int)' being compiled
                with
                [
                    T=double
                ]
        src\vaexfast.cpp(88): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(280): note: see reference to function template instantiation 'void object_to_numpy1d_nocopy_endian<double>(T *&,PyObject *,__int64 &,bool &,int &,int)' being compiled
                with
                [
                    T=double
                ]
        src\vaexfast.cpp(105): warning C4244: 'initializing': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(644): note: see reference to function template instantiation 'void object_to_numpy2d_nocopy<double>(T *&,PyObject *,int &,int &,int)' being compiled
                with
                [
                    T=double
                ]
        src\vaexfast.cpp(108): warning C4244: 'initializing': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(667): warning C4244: 'initializing': conversion from 'const double' to 'float', possible loss of data
        src\vaexfast.cpp(775): note: see reference to function template instantiation 'void histogram2d_f4<__int64>(const float *__restrict const ,const float *__restrict const ,const float *const ,const __int64,bool,bool,bool,Tout *__restrict const ,const int,const int,const double,const double,const double,const double,const __int64,const __int64)' being compiled
                with
                [
                    Tout=__int64
                ]
        src\vaexfast.cpp(667): warning C4244: 'initializing': conversion from 'const double' to 'const float', possible loss of data
        src\vaexfast.cpp(668): warning C4244: 'initializing': conversion from 'const double' to 'float', possible loss of data
        src\vaexfast.cpp(668): warning C4244: 'initializing': conversion from 'const double' to 'const float', possible loss of data
        src\vaexfast.cpp(669): warning C4244: 'initializing': conversion from 'const double' to 'float', possible loss of data
        src\vaexfast.cpp(669): warning C4244: 'initializing': conversion from 'const double' to 'const float', possible loss of data
        src\vaexfast.cpp(670): warning C4244: 'initializing': conversion from 'const double' to 'float', possible loss of data
        src\vaexfast.cpp(670): warning C4244: 'initializing': conversion from 'const double' to 'const float', possible loss of data
        src\vaexfast.cpp(671): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
        src\vaexfast.cpp(671): warning C4244: 'initializing': conversion from 'double' to 'const float', possible loss of data
        src\vaexfast.cpp(672): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
        src\vaexfast.cpp(672): warning C4244: 'initializing': conversion from 'double' to 'const float', possible loss of data
        src\vaexfast.cpp(133): warning C4244: 'initializing': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(887): note: see reference to function template instantiation 'void object_to_numpy3d_nocopy<double>(T *&,PyObject *,int &,int &,int &,int)' being compiled
                with
                [
                    T=double
                ]
        src\vaexfast.cpp(136): warning C4244: 'initializing': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(139): warning C4244: 'initializing': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(174): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
        src\vaexfast.cpp(983): note: see reference to function template instantiation 'void object_to_numpyNd_nocopy<double>(T *&,PyObject *,int,int &,int *,__int64 *,int)' being compiled
                with
                [
                    T=double
                ]
        src\vaexfast.cpp(1335): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
        src\vaexfast.cpp(2072): note: see reference to function template instantiation 'PyObject *statisticNd_<double,NPY_DOUBLE>(PyObject *,PyObject *)' being compiled
        src\vaexfast.cpp(1338): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
        src\vaexfast.cpp(1149): warning C4244: 'initializing': conversion from 'double' to 'T', possible loss of data
                with
                [
                    T=float
                ]
        src\vaexfast.cpp(1271): note: see reference to function template instantiation 'void statisticNd<T,op_add1<T,double,endian>,endian>(const T *__restrict const [],const T *__restrict const [],__int64,const int,const int,double *__restrict const ,const __int64 *__restrict const ,const int *__restrict const ,const T *__restrict const ,const T *__restrict const ,int)' being compiled
                with
                [
                    T=float,
                    endian=functor_double_to_native
                ]
        src\vaexfast.cpp(1308): note: see reference to function template instantiation 'void statisticNd_wrap_template_endian<T,functor_double_to_native>(const T *const [],const T *const [],__int64,int,int,double *,__int64 [],int [],T [],T [],int,int)' being compiled
                with
                [
                    T=float
                ]
        src\vaexfast.cpp(1402): note: see reference to function template instantiation 'void statisticNd_wrap_template<T>(const T *const [],const T *const [],__int64,int,int,double *,__int64 [],int [],T [],T [],bool,int,int)' being compiled
                with
                [
                    T=float
                ]
        src\vaexfast.cpp(2073): note: see reference to function template instantiation 'PyObject *statisticNd_<float,NPY_FLOAT>(PyObject *,PyObject *)' being compiled
        src\vaexfast.cpp(1178): warning C4244: 'initializing': conversion from 'double' to 'T', possible loss of data
                with
                [
                    T=float
                ]
        src\vaexfast.cpp(1198): warning C4244: 'initializing': conversion from 'double' to 'T', possible loss of data
                with
                [
                    T=float
                ]
        src\vaexfast.cpp(1216): warning C4244: 'initializing': conversion from 'double' to 'T', possible loss of data
                with
                [
                    T=float
                ]
        creating C:\Work\sandbox\experiments\vaex\packages\vaex-core\build\lib.win-amd64-3.9
        creating C:\Work\sandbox\experiments\vaex\packages\vaex-core\build\lib.win-amd64-3.9\vaex
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\python\libs /LIBPATH:C:\python\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64 /EXPORT:PyInit_vaexfast build\temp.win-amd64-3.9\Release\src\vaexfast.obj /OUT:build\lib.win-amd64-3.9\vaex\vaexfast.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\src\vaexfast.cp39-win_amd64.lib
           Creating library build\temp.win-amd64-3.9\Release\src\vaexfast.cp39-win_amd64.lib and object build\temp.win-amd64-3.9\Release\src\vaexfast.cp39-win_amd64.exp
        Generating code
        Finished generating code
        building 'vaex.superstrings' extension
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\friedmanab\AppData\Local\Temp\pip-build-env-e0tylw52\overlay\Lib\site-packages\numpy\core\include -Ivendor/pybind11/include -Ivendor/pybind11/include -Ivendor/string-view-lite/include -Ivendor/boost -IC:\python\include -IC:\python\Library\include -IC:\Work\sandbox\experiments\vaex\packages\vaex-core\vendor\pcre\Library\include -IC:\python\include -IC:\python\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpsrc\string_utils.cpp /Fobuild\temp.win-amd64-3.9\Release\src\string_utils.obj /EHsc
        string_utils.cpp
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(208): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(210): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(213): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(217): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\friedmanab\AppData\Local\Temp\pip-build-env-e0tylw52\overlay\Lib\site-packages\numpy\core\include -Ivendor/pybind11/include -Ivendor/pybind11/include -Ivendor/string-view-lite/include -Ivendor/boost -IC:\python\include -IC:\python\Library\include -IC:\Work\sandbox\experiments\vaex\packages\vaex-core\vendor\pcre\Library\include -IC:\python\include -IC:\python\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /Tpsrc\strings.cpp /Fobuild\temp.win-amd64-3.9\Release\src\strings.obj /EHsc
        strings.cpp
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(208): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(210): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(213): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        C:\Work\sandbox\experiments\vaex\packages\vaex-core\src\string_utils.hpp(217): warning C4244: '=': conversion from 'char32_t' to 'char', possible loss of data
        src\strings.cpp(23): fatal error C1083: Cannot open include file: 'pcrecpp.h': No such file or directory
        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
        ----------------------------------------
    ERROR: Command errored out with exit status 1: 'C:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Work\\sandbox\\experiments\\vaex\\packages\\vaex-core\\setup.py'"'"'; __file__='"'"'C:\\Work\\sandbox\\experiments\\vaex\\packages\\vaex-core\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
    WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
    You should consider upgrading via the 'C:\python\python.exe -m pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Work\sandbox\experiments\vaex\setup.py", line 63, in <module>
        setup(
      File "c:\users\friedmanab\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\friedmanab\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\friedmanab\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\friedmanab\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Work\sandbox\experiments\vaex\setup.py", line 33, in run
        raise RuntimeError(f'Oops, failed to install {package}')
    RuntimeError: Oops, failed to install vaex-core
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\friedmanab\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Work\\sandbox\\experiments\\vaex\\setup.py'"'"'; __file__='"'"'C:\\Work\\sandbox\\experiments\\vaex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by maartenbreddels** [comment]
My recommendation is to use conda, a package manager, to install Python, and to create a Python env (ton of resources available online on how to set that up).
You can run `make init` or `pip install ...` not both, does that make sense?

**Comment by JovanVeljanoski** [comment]
Closing as completed.
