### ISSUE TITLE
Concatenation of data frames 

### ISSUE THREAD

**Issue by AliAkbarAhmadiDaryab** [vaexio/vaex#1622]
I am trying to concatenate two data frame of same columns size and name. However, it doesn't matter what I use:
1. df = vaex.concat([df1, df2])
2. df = df1.concat(df2)
3. df = df1.concat(df2, resolver='flexible')
I get the same error:
Traceback (most recent call last):
  File "/home/U808532/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataframe.py", line 5860, in concat
    dfs[dfs.index(df)] = df._lazy_materialize(name)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataframe.py", line 4591, in _lazy_materialize
    df.add_column(name, column)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataframe.py", line 3187, in add_column
    self.columns[valid_name] = ar
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataframe.py", line 5294, in __setitem__
    right = vaex.dataset.DatasetArrays({item: value})
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 1301, in __init__
    self._ids = frozendict({key: hash_array(array) for key, array in self._columns.items()})
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 1301, in <dictcomp>
    self._ids = frozendict({key: hash_array(array) for key, array in self._columns.items()})
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 160, in hash_array
    hash_info = hash_array_data(ar)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 150, in hash_array_data
    hash_data = {"type": "column", "fingerprint": ar.fingerprint()}
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/column.py", line 32, in fingerprint
    self._cached_fingerprint = self._fingerprint()
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/column.py", line 355, in _fingerprint
    fp = vaex.cache.fingerprint([k.fingerprint() for k in self.expressions])
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/column.py", line 355, in <listcomp>
    fp = vaex.cache.fingerprint([k.fingerprint() for k in self.expressions])
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/expression.py", line 228, in fingerprint
    fp = vaex.cache.fingerprint(self.expression, self.df.fingerprint())
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataframe.py", line 229, in fingerprint
    state = df._state_get_vaex_5(skip=[df.dataset])
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataframe.py", line 2269, in _state_get_vaex_5
    encoding._object_specs[dataset.id] = None
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 336, in id
    return self.fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 934, in _fingerprint
    id = vaex.cache.fingerprint(self.original.id, self._hash_index, self.state, self.selection)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 336, in id
    return self.fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 615, in _fingerprint
    id = vaex.cache.fingerprint(self.original.fingerprint, self.renaming)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 1220, in _fingerprint
    id = vaex.cache.fingerprint(self.left.fingerprint, self.right.fingerprint)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 1220, in _fingerprint
    id = vaex.cache.fingerprint(self.left.fingerprint, self.right.fingerprint)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 615, in _fingerprint
    id = vaex.cache.fingerprint(self.original.fingerprint, self.renaming)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 1220, in _fingerprint
    id = vaex.cache.fingerprint(self.left.fingerprint, self.right.fingerprint)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 615, in _fingerprint
    id = vaex.cache.fingerprint(self.original.fingerprint, self.renaming)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 342, in fingerprint
    self._cached_fingerprint = self._fingerprint
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/dataset.py", line 934, in _fingerprint
    id = vaex.cache.fingerprint(self.original.id, self._hash_index, self.state, self.selection)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/cache.py", line 250, in fingerprint
    return dask.base.tokenize(*args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 798, in tokenize
    return md5(str(tuple(map(normalize_token, args))).encode()).hexdigest()
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 821, in normalize_dict
    return normalize_token(sorted(d.items(), key=str))
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 842, in normalize_seq
    return type(seq).__name__, func(seq)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 838, in func
    return list(map(normalize_token, seq))
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 842, in normalize_seq
    return type(seq).__name__, func(seq)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 838, in func
    return list(map(normalize_token, seq))
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 821, in normalize_dict
    return normalize_token(sorted(d.items(), key=str))
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 842, in normalize_seq
    return type(seq).__name__, func(seq)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 838, in func
    return list(map(normalize_token, seq))
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 842, in normalize_seq
    return type(seq).__name__, func(seq)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 838, in func
    return list(map(normalize_token, seq))
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/dask/base.py", line 860, in normalize_object
    return normalize_function(o) if callable(o) else uuid.uuid4().hex
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/cache.py", line 248, in explain
    raise TypeError('You have passed in an object for which we cannot determine a fingerprint')

Just to let you know I have checked the type of dataframe, I can print them both data frames and can check their values but I am not able to concat them.
df1 = <class 'vaex.dataframe.DataFrameLocal'>
df2 = <class 'vaex.dataframe.DataFrameLocal'>

Thank you

**Comment by JovanVeljanoski** [comment]
Can you answer the questions that were stated in the issues form? or provide a minimal reproducible example?

**Comment by AliAkbarAhmadiDaryab** [comment]
Since the data is credential I am not able to show you the data. However, following is my script:
initial_shape = data.shape[0]
water = data[data['some_col_name'].isin(rtb_water)][key + var].sort(by=var)
water = water.extract()
water = water.to_pandas_df()
logging.debug(f'water: {water.shape}')

for i, v in enumerate(var):
	logging.debug(f'Enrich glas data with feature {v}')
	water[v] = water.groupby(key)[v].ffill()

data_glas = data[data['some_col_name'].isin(rtb_glas)].sort(by=key)
data_glas = data_glas.extract()
data_glas.drop(var, inplace=True)
data_glas_key = data_glas[key].to_pandas_df()

water = water.drop_duplicates(subset=key, keep='first')
data_glas_key = data_glas_key.merge(water, on=key, how='left')
for v in var:
	data_glas[v] = data_glas_key[v].values

# merge new glas data to orginal data
data = data[~data['some_col_name'].isin(rtb_glas)].extract()
data = data.concat(data_glas)

logging.debug(f'rows lost: {initial_shape - data.shape[0]}')


The original data has 95 columns and the key is used to determine the same rows

**Comment by JovanVeljanoski** [comment]
It is definetely not due to size of data.. i just tried with with over **1 billion** rows, resulting in over 2 billion rows in a second...

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/18574951/136676658-aa82e8e2-2988-42d0-84ec-e023138027c7.png">


maybe there is something strange with your data.. maybe there is a real problem, but without reproducing it we can't help..

**Comment by JovanVeljanoski** [comment]
Hmm.. this is a long shot.. but sometimes users report random errors when they use pycharm (i noticed from the error stacktrace that you are maybe using it?) can you try your example in a simple ipython terminal? See if that makes any difference?

**Comment by AliAkbarAhmadiDaryab** [comment]
I am using IntelliJ, unfortunately, I don't have access to jupyter to run my ipython code. I need to run the code on the server because of the data size. 
What I found little bit strange is the following:
data_glas = data[data['some_col_name'].isin(rtb_glas)].sort(by=key)
data_glas = data_glas.extract()

data = data[~data['some_col_name'].isin(rtb_glas)].extract()
data = data.concat(data_glas)

This also works, the strange things happened when I remove the 'v' column and append the numpy array of 'v' columns values

**Comment by AliAkbarAhmadiDaryab** [comment]
I found the problem.
I guess it is because of the way vaex save the column as expression. The numpy altered 'v' column was numeric however the vaex data frame was expression.
What I did export the data and load back the data. It solved my issue for now
Thank you @JovanVeljanoski

**Comment by JovanVeljanoski** [comment]
Ok few things here:

 - it is best to open a new issue for a different problem, otherwise the discussion is unfocused, and things are hard to find
 - When you open a new issue, please answer the questions in the template, as it helps us to help you, especially because:
 - I have seen this error before, and it has been fixed, so would have been helpful to know your vaex version, and how you install it (the stuff we ask in the issue template form)
 - Please provide a reproducible example, because if we can't reproduce it we can't fix it.. and you see the basic example works on my end:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/18574951/136854190-81dd6a95-03a2-4a01-8029-35bd93db393e.png">
 - Please try to format your code in the issues, makes it more easy to read (will likely make others to help as well, as it makes it more easy to read through your problem).

**Comment by AliAkbarAhmadiDaryab** [comment]
I know it is closed. Just for people who likes to know whether the Vaex update works or no:
The Vaex update didn't work.
I simple find a new way to solve it:
After loading the exported file:
save the column with date data into numpy array.
drop it from vaex dataframe.
finally add the saved numpy array to vaex dataframe.

It worked for me.

**Comment by JovanVeljanoski** [comment]
We do not need the real data. Create a mock dataset ->put made up values, you can change the column names too. 
We just want to reproduce the bug. 

Also regarding the datetime issue -> that is indeed fixed, but it released in the alpha versions. We dont have a stable version out that has that fix. So you might wanna try installing the latest alpha.
