### ISSUE TITLE
[FEATURE-REQUEST] vaex map function dafualt_value parameters can support the np.nan

### ISSUE THREAD

**Issue by AliAkbarAhmadiDaryab** [vaexio/vaex#1633]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your request may already be discussed or addressed.

**Description**
I am looking to replace values which are not in the mapper dictionary with a np.nan
Here is the reproducible example:
df = vaex.from_arrays(color=['red', 'red', 'blue', 'red', 'green', 'new'])
mapper = {'red': 1, 'blue': 2, 'green': np.nan}
df['color_mapped'] = df.color.map(mapper, default_value=np.nan)

When I run the above code I get this error:
Traceback (most recent call last):
  File "/home/U808532/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/usr/share/applications/anaconda3/envs/pip/lib/python3.7/site-packages/vaex/expression.py", line 1375, in map
    assert np.issubdtype(type(default_value), np.array(value0).dtype), "default value has to be of similar type"
AssertionError: default value has to be of similar type

I am using the following vaex:
{'vaex': '4.5.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0'}

**Comment by JovanVeljanoski** [comment]
Ok, so this is not a bug, and `default_value` does support `np.nan`. 

What is happening is you are trying to put a `np.nan`, which is a float, into an expression for strings. Vaex no longer supports columns/expressions of mixed types. 

Another thing is, you need to enable `allow_missing=True` flag to be able to fill unseen values anyway, which is there as a safely flag.

So to make your example work, you just need to do 

```python
df['color_mapped'] = df.color.map(mapper, allow_missing=True)
```

and by default you will get masked values for the unseen new categories. Otherwise you can use `default_value` to specify the fill value, but it needs to be of string type.

**Comment by maartenbreddels** [comment]
Also, a solution is to make the values in the map of the float type, then you _can_ use np.nan (otherwise vaex things the values are ints, and ints do not have a NaN).

```python
import vaex
import numpy as np
df = vaex.from_arrays(color=['red', 'red', 'blue', 'red', 'green', 'new'])
mapper = {'red': 1., 'blue': 2., 'green': np.nan}  # note the .
df['color_mapped'] = df.color.map(mapper, default_value=np.nan, allow_missing=True)
```
