### ISSUE TITLE
ValueError: cannot create an OBJECT array from memory buffer when using value_counts()

### ISSUE THREAD

**Issue by Code4SAFrankie** [vaexio/vaex#1682]
**Description**
When trying to get a distinct list and count of a text column read in from parquet files created by Dask I get the below error. The data is the yagoFacts from [here](https://yago-knowledge.org/downloads).

```
import glob
file_list = glob.glob(r'D:\Downloads\Wikipedia\Yago\yagoFacts\part.*.parquet')
df = vaex.open_many(file_list)
df.statement.value_counts()
```
Gives this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\expression.py", line 995, in value_counts
    self.ds.map_reduce(map, reduce, [self.expression], delay=False, progress=progress, name='value_counts', info=True, to_numpy=False)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\dataframe.py", line 415, in map_reduce
    return self._delay(delay, task)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\dataframe.py", line 1566, in _delay
    self.execute()
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\dataframe.py", line 398, in execute
    just_run(self.execute_async())
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\nest_asyncio.py", line 59, in run_until_complete
    return f.result()
  File "E:\WPy64-3771\python-3.7.7.amd64\lib\asyncio\futures.py", line 181, in result
    raise self._exception
  File "E:\WPy64-3771\python-3.7.7.amd64\lib\asyncio\tasks.py", line 249, in __step
    result = coro.send(None)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\dataframe.py", line 402, in execute_async
    await self.executor.execute_async()
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\execution.py", line 258, in execute_async
    cancel=lambda: self._cancel(run), unpack=True, run=run):
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\multithreading.py", line 95, in map_async
    value = await value
    yield self  # This tells Task to wait for completion.
  File "E:\WPy64-3771\python-3.7.7.amd64\lib\asyncio\tasks.py", line 318, in __wakeup
    future.result()
  File "E:\WPy64-3771\python-3.7.7.amd64\lib\asyncio\futures.py", line 181, in result
    raise self._exception
  File "E:\WPy64-3771\python-3.7.7.amd64\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\multithreading.py", line 90, in <lambda>
    iterator = (loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in cancellable_iter())
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\multithreading.py", line 76, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\execution.py", line 368, in process_part
    task_part.process(thread_index, i1, i2, filter_mask, *blocks)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\cpu.py", line 292, in process
    self.values.append(self._map(thread_index, i1, i2, *blocks))
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\expression.py", line 986, in map
    ar = vaex.array_types.to_numpy(ar)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\array_types.py", line 131, in to_numpy
    x = vaex.arrow.convert.column_from_arrow_array(x)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\arrow\convert.py", line 84, in column_from_arrow_array
    return numpy_array_from_arrow_array(arrow_array)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\arrow\convert.py", line 130, in numpy_array_from_arrow_array
    array = np.frombuffer(data_buffer, dtype, len(arrow_array) + offset)[offset:]
ValueError: cannot create an OBJECT array from memory buffer
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
 {'vaex': '3.0.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0', 'vaex-arrow': '0.5.1'}
 - Vaex was installed via: pip 
 - OS: Windows 10

**Additional information**
[This](https://stackoverflow.com/questions/52972412/valueerror-cannot-create-an-object-array-from-memory-buffer) might help

**Comment by Code4SAFrankie** [comment]
`df.export(r'D:\Downloads\Wikipedia\Yago\yagoFacts.hdf5')` also gives the same error

**Comment by JovanVeljanoski** [comment]
What is the `dtype` of the column you are using? Is it possible to make a small reproducible example (something we can use to reproduce the problem locally), or get a small sample of the data?

**Comment by Code4SAFrankie** [comment]
`df.export(r'D:\Downloads\Wikipedia\Yago\yagoFacts.hdf5')` also gives the same error

**Comment by Code4SAFrankie** [comment]
```
>>> df.dtypes
id1_1        dictionary<values=string, indices=int32, order...
id1_rel      dictionary<values=string, indices=int32, order...
id1_2        dictionary<values=string, indices=int32, order...
class1       dictionary<values=string, indices=int32, order...
statement    dictionary<values=string, indices=int32, order...
class2       dictionary<values=string, indices=int32, order...
dtype: object
```

**Comment by Code4SAFrankie** [comment]
Did a `df['statement'] = df['statement'].astype('str')` and that fixed the problem! Thanks

**Comment by JovanVeljanoski** [comment]
Ah so value_counts works only on non-nested types for now. Maybe in the future we can have support for key-value pair counting or sample based counting, but I expect that to be further down the line. 

By casting to string, i guess you are making the whole dictionary (sample) a string so you are effectively doing sample countring.
