### ISSUE TITLE
[BUG-REPORT] Vaex dataframe access crashes asyncio event loop tasks

### ISSUE THREAD

**Issue by schwingkopf** [vaexio/vaex#1701]
**Description**
I'm experiencing issues when using vaex in the context of an asyncio event loop. The repeated interaction with the data frame seems to kill auxiliary tasks in the same event loop. The following code reproduces my issue:
```
import asyncio
import vaex
import numpy as np

async def vaex_task(df):
    while True:
        await asyncio.sleep(0.1)
        print(df.count())

async def aux_task():
    while True:
        await asyncio.sleep(0.3)
        print("Aux task alive")

df = vaex.from_dict(dict(x=np.linspace(0, 1., 100)))

loop = asyncio.get_event_loop()
loop.create_task(vaex_task(df))
loop.create_task(aux_task())
loop.run_forever()
```

Example output is:
```
100
100
Aux task alive
100
100
100
Aux task alive
100
100
Aux task alive
100
100
100
Aux task alive
100
100
Exception in callback <TaskWakeupMethWrapper object at 0x00000156BC40C4F8>(<Future finished result=None>)
handle: <Handle <TaskWakeupMethWrapper object at 0x00000156BC40C4F8>(<Future finished result=None>)>
Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending coro=<aux_task() running at D:\git_repos\genericosci\src\osci_backend\minimal_vaex_problem.py:20> wait_for=<Future finished result=None>> while another task <Task pending coro=<vaex_task() running at D:\git_repos\genericosci\src\osci_backend\minimal_vaex_problem.py:16>> is being executed.
Task was destroyed but it is pending!
task: <Task pending coro=<aux_task() running at D:\git_repos\genericosci\src\osci_backend\minimal_vaex_problem.py:20> wait_for=<Future finished result=None>>
100
100
100
100
100
100
100
100
100
100
```

The time after which the exception is thrown varies from run to run, but usually happens within the first 10 iterations of `aux_task` 

Does that look like a bug in vaex or am I doing something wrong here?

Thanks in advance for looking into this!

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: {'vaex': '4.5.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0'}
 - Vaex was installed via: pip
 - OS: Win10
 - Python: 3.7.7

**Comment by maartenbreddels** [comment]
Hi,

We're using nest_asyncio, which may trigger this. You may want to take a look at https://github.com/vaexio/vaex/pull/1546 to see if that can solve your issue. Although I know there are more issues like this.

Thanks for providing this example!

**Comment by schwingkopf** [comment]
Hi,

the solution in #1546 seems to solve the issue for most of my use cases when using `df.executor.async_method = "awaitio"`. Thanks for suggesting that.

However there is one particular edge case that still doesn't work (and that may be relevant for vaex-server as well). It's when using `fastapi` in combination with `http-middleware`. This (extended) example reproduces the issue:
```
import asyncio
import numpy as np
import time

import vaex
import uvicorn
from fastapi import FastAPI, Request


async def vaex_task(df):
    print(df.count())
    return "Reponse content"


async def aux_task():
    while True:
        await asyncio.sleep(0.3)
        print("Aux task alive")


df = vaex.from_dict(dict(x=np.linspace(0, 1., 100)))
df.executor.async_method = "awaitio"


app = FastAPI()

@app.get("/")
async def vaex_call():
    return await vaex_task(df)


@app.middleware("http")
async def nonsense_middleware(request: Request, call_next):
    return await call_next(request)


async def web_request(host, port):
    import aiohttp

    await asyncio.sleep(1.0)    
    async with aiohttp.ClientSession() as session:
        while True:
            async with session.get(f"http://{host}:{port}/") as resp:
                print(await resp.text())
            await asyncio.sleep(0.1)            


if __name__ == "__main__":
    addr = "127.0.0.1"
    port = 8001
    
    config = uvicorn.Config(app=app, host=addr, port=port, loop="asyncio")
    server = uvicorn.Server(config)
    
    loop = asyncio.get_event_loop()
    loop.create_task(server.serve())
    loop.create_task(web_request(addr, port))
    loop.create_task(aux_task())
    loop.run_forever()
```
It gives the following output:
```
INFO:     Started server process [18168]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8001 (Press CTRL+C to quit)
Aux task alive
Aux task alive
Aux task alive
100
INFO:     127.0.0.1:51188 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Python37\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Python37\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Python37\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await response(scope, receive, send)
  File "C:\Python37\lib\site-packages\starlette\responses.py", line 226, in __call__
    (self.listen_for_disconnect, {"receive": receive}),
  File "C:\Python37\lib\site-packages\starlette\concurrency.py", line 21, in run_until_first_complete
    tasks = [create_task(handler(**kwargs)) for handler, kwargs in args]
  File "C:\Python37\lib\site-packages\starlette\concurrency.py", line 21, in <listcomp>
    tasks = [create_task(handler(**kwargs)) for handler, kwargs in args]
  File "C:\Python37\lib\asyncio\tasks.py", line 350, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
C:\Python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py:403: RuntimeWarning: coroutine 'StreamingResponse.stream_response' was never awaited
  self.transport.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Internal Server Error
100
INFO:     127.0.0.1:51189 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Python37\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Python37\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Python37\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python37\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Python37\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Python37\lib\site-packages\starlette\middleware\base.py", line 26, in __call__
    await response(scope, receive, send)
  File "C:\Python37\lib\site-packages\starlette\responses.py", line 226, in __call__
    (self.listen_for_disconnect, {"receive": receive}),
  File "C:\Python37\lib\site-packages\starlette\concurrency.py", line 21, in run_until_first_complete
    tasks = [create_task(handler(**kwargs)) for handler, kwargs in args]
  File "C:\Python37\lib\site-packages\starlette\concurrency.py", line 21, in <listcomp>
    tasks = [create_task(handler(**kwargs)) for handler, kwargs in args]
  File "C:\Python37\lib\asyncio\tasks.py", line 350, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop

...
```
The interesting part is that it works perfectly when I remove the `@app.middleware("http")` section. Not sure if that problem is to be looked for in `fastapi` though..

Any ideas what could cause this?

**Comment by maartenbreddels** [comment]
At https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/asyncio.py#L15 we remove the running loop, maybe we should restore it. It's difficult for me to test this out at the moment.
It would be great if you can experiment with this, and possible add a test that reproduces this error.
