### ISSUE TITLE
vaex apply does not work when using dataframe columns

### ISSUE THREAD

**Issue by Code4SAFrankie** [vaexio/vaex#1705]
**Description**
I am trying to replace string values in a string column using other string columns in the dataframe. In Pandas I can do this using 

`df['Test'] = df.apply(lambda x: x['Name'].replace(x['Rep'], x['Sub']), axis=1)`

but I cannot find the equivalent vaex method. [This](https://github.com/vaexio/vaex/issues/442) issue led me to believe that this should be possible in vaex based on Maarten Breddels' example code, however when trying it I get the below error.

```
import pandas as pd
import vaex

df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Rep": ["Braund", "Henry", "Miss."],
        "Sub": ["<surname>", "<name>", "<title>"],
    }
)
dfv = vaex.from_pandas(df)

def func(x, y, z):
    return x.replace(y, z)

dfv['Test'] = dfv.apply(func, arguments=[df.Name.astype('str'), df.Rep.astype('str'), df.Sub.astype('str')])
```

Gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\dataframe.py", line 455, in apply
    arguments = _ensure_strings_from_expressions(arguments)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\utils.py", line 780, in _ensure_strings_from_expressions
    return [_ensure_strings_from_expressions(k) for k in expressions]
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\utils.py", line 780, in <listcomp>
    return [_ensure_strings_from_expressions(k) for k in expressions]
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\utils.py", line 782, in _ensure_strings_from_expressions
    return _ensure_string_from_expression(expressions)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\utils.py", line 775, in _ensure_string_from_expression
    raise ValueError('%r is not of string or Expression type, but %r' % (expression, type(expression)))
ValueError: 0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2    Bonnell, Miss. Elizabeth
Name: Name, dtype: object is not of string or Expression type, but <class 'pandas.core.series.Series'>
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: {'vaex': '3.0.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0', 'vaex-arrow': '0.5.1'}
 - Vaex was installed via: pip 
 - OS: Windows 10 64 bit

**Additional information**
I am trying to tokenize natural language for the first sentence in wikipedia in order to find 'is a' patterns. n-grams of the tokens and left over text would be the next step. 'Wellington is a town in the UK.' becomes '`<town>` is a `<attr_root>` in the `<country>`.' Then find common patterns using n-grams.

**Comment by Ben-Epstein** [comment]
@Code4SAFrankie  I think the issue is your arguments are coming from your pandas df (`df`) not your vaex df (`dfv`)

This works for me

```
import pandas as pd
import vaex

df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Rep": ["Braund", "Henry", "Miss."],
        "Sub": ["<surname>", "<name>", "<title>"],
    }
)
dfv = vaex.from_pandas(df)

dfv['Test'] = dfv.apply(lambda x, y, z: x.replace(y, z) , arguments=[dfv.Name, dfv.Rep, dfv.Sub])
dfv['Test']
```

**Comment by Ben-Epstein** [comment]
I'm not positive, because this seems hacky, but it may be faster (because `apply` is pretty slow in my experience)

```
import pyarrow as pa
import pandas as pd
import vaex

df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Rep": ["Braund", "Henry", "Miss."],
        "Sub": ["<surname>", "<name>", "<title>"],
    }
)
dfv = vaex.from_pandas(df)


@vaex.register_function()
def replacer(x, y, z):
    res = []
    for i, j, k in zip(x.tolist(), y.tolist(), z.tolist()):
        res.append(i.replace(j, k))
    return pa.array(res)

dfv['Test'] = dfv.func.replacer(dfv['Name'], dfv['Rep'], dfv['Sub'])
```

**Comment by Code4SAFrankie** [comment]
Thanks for all this, it was because I was using df instead of dfv.
