### ISSUE TITLE
[BUG-REPORT] - Unable to read multipart parquet files from minio 

### ISSUE THREAD

**Issue by saikiran2603** [vaexio/vaex#1714]
**Description**
When reading multipart parquet files from minio server , getting below error. 

```python
OSError: When getting information for key 'temp/parquet/yelp_academic_dataset_user/part0.parquet' in bucket 'data-sources': AWS Error [code 15]: No response body.
```

although the file exists on the minio on the said path. 

If the parquet files are stored on disk , and loaded in similar fashion it works properly. Also below code works fine for me 

```python
import vaex
vaex.open('s3://vaex/taxi/yellow*v2.parquet', fs_options={'anon': True})
```

So it seems the issue is specifically with minio , and not when the files are present on s3 / local storage. Below are the fs_options i am passing 

```python
vaex_storage_options = {"endpoint_override": "http://" + minio_server,
                        "access_key": minio_key,
                        "secret_key": minio_secret,
                        # "scheme": 'http',
                        "cache": False}
```

As per documentation , in storage options for minio , "scheme": "http" is to be passed , but when i try this, i get key error 

```python
    warnings.warn(f'The option {key} is not supported using s3fs instead of arrow, so it will be ignored')
NameError: name 'warnings' is not defined
```
which points to https://github.com/vaexio/vaex/blob/012cc74ea8cc15cc2a664bf3bb635f7abb12f8a0/packages/vaex-core/vaex/file/s3fs.py#L20

So essentially reading multipart parquet files from minio seems to be not working.  Below is the full stack.

```python
ERROR:MainThread:vaex:error opening 's3://data-sources/temp/parquet/yelp_academic_dataset_user/part0.parquet'
Traceback (most recent call last):
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/__init__.py", line 225, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/dataset.py", line 73, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/opener.py", line 44, in open
    return open_parquet(path, *args, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 344, in open_parquet
    return DatasetParquet(path, fs_options=fs_options, fs=fs, partitioning=partitioning, kwargs=kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 197, in __init__
    super().__init__(max_rows_read=max_rows_read)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 26, in __init__
    self._create_columns()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 226, in _create_columns
    super()._create_columns()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 29, in _create_columns
    self._create_dataset()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 231, in _create_dataset
    self._arrow_ds = pyarrow.dataset.dataset(source, filesystem=file_system, partitioning=self.partitioning)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 680, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 425, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 392, in _ensure_single_source
    file_info = filesystem.get_file_info(path)
  File "pyarrow/_fs.pyx", line 439, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1101, in pyarrow._fs._cb_get_file_info
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/file/cache.py", line 96, in get_file_info
    return self.fs.get_file_info(*args, **kwargs)
  File "pyarrow/_fs.pyx", line 435, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: When getting information for key 'temp/parquet/yelp_academic_dataset_user/part0.parquet' in bucket 'data-sources': AWS Error [code 15]: No response body.
ERROR:MainThread:vaex:error opening 's3://data-sources/temp/parquet/yelp_academic_dataset_user/*.parquet'
Traceback (most recent call last):
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/__init__.py", line 240, in open
    dfs.append(vaex.open(filename, convert=bool(convert), shuffle=shuffle, **kwargs))
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/__init__.py", line 225, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/dataset.py", line 73, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/opener.py", line 44, in open
    return open_parquet(path, *args, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 344, in open_parquet
    return DatasetParquet(path, fs_options=fs_options, fs=fs, partitioning=partitioning, kwargs=kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 197, in __init__
    super().__init__(max_rows_read=max_rows_read)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 26, in __init__
    self._create_columns()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 226, in _create_columns
    super()._create_columns()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 29, in _create_columns
    self._create_dataset()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 231, in _create_dataset
    self._arrow_ds = pyarrow.dataset.dataset(source, filesystem=file_system, partitioning=self.partitioning)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 680, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 425, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 392, in _ensure_single_source
    file_info = filesystem.get_file_info(path)
  File "pyarrow/_fs.pyx", line 439, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1101, in pyarrow._fs._cb_get_file_info
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/file/cache.py", line 96, in get_file_info
    return self.fs.get_file_info(*args, **kwargs)
  File "pyarrow/_fs.pyx", line 435, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: When getting information for key 'temp/parquet/yelp_academic_dataset_user/part0.parquet' in bucket 'data-sources': AWS Error [code 15]: No response body.
Traceback (most recent call last):
  File "/home/saikiran/PycharmProjects/tests/Vaex_Test.py", line 66, in <module>
    df1 = vaex.open('s3://data-sources/temp/parquet/yelp_academic_dataset_user/*.parquet', fs_options=vaex_storage_options)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/__init__.py", line 240, in open
    dfs.append(vaex.open(filename, convert=bool(convert), shuffle=shuffle, **kwargs))
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/__init__.py", line 225, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/dataset.py", line 73, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/opener.py", line 44, in open
    return open_parquet(path, *args, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 344, in open_parquet
    return DatasetParquet(path, fs_options=fs_options, fs=fs, partitioning=partitioning, kwargs=kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 197, in __init__
    super().__init__(max_rows_read=max_rows_read)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 26, in __init__
    self._create_columns()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 226, in _create_columns
    super()._create_columns()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 29, in _create_columns
    self._create_dataset()
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/arrow/dataset.py", line 231, in _create_dataset
    self._arrow_ds = pyarrow.dataset.dataset(source, filesystem=file_system, partitioning=self.partitioning)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 680, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 425, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/pyarrow/dataset.py", line 392, in _ensure_single_source
    file_info = filesystem.get_file_info(path)
  File "pyarrow/_fs.pyx", line 439, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1101, in pyarrow._fs._cb_get_file_info
  File "/home/saikiran/.PycharmProjects/test3.8.12/lib/python3.8/site-packages/vaex/file/cache.py", line 96, in get_file_info
    return self.fs.get_file_info(*args, **kwargs)
  File "pyarrow/_fs.pyx", line 435, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: When getting information for key 'temp/parquet/yelp_academic_dataset_user/part0.parquet' in bucket 'data-sources': AWS Error [code 15]: No response body.

``` 

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
  {'vaex': '4.5.0', 
   'vaex-core': '4.5.1', 
   'vaex-viz': '0.5.0', 
   'vaex-hdf5': '0.10.0', 
   'vaex-server': '0.6.1',
   'vaex-astro': '0.9.0',
    'vaex-jupyter': '0.6.0', 
    'vaex-ml': '0.14.0'}

 - Vaex was installed via: pip  
 - OS: Linux 

**Additional information**
pyarrow version - 6.0.0

**Comment by saikiran2603** [comment]
I figured how to get it to work. apparently instead of specifying wild cards , i should have passed the directory path were parquet parts are stored. It works when i pass the directory path. 

```python
df1 = vaex.open('s3://data-sources/temp/parquet/yelp_academic_dataset_user/*.parquet', fs_options=vaex_storage_options)

``` 
This does not work and throws error , but 
```python
df1 = vaex.open('s3://data-sources/temp/parquet/yelp_academic_dataset_user/', fs_options=vaex_storage_options)

``` 
this works properly and loads all file parts from inside the directory ! 

Thanks !

**Comment by maartenbreddels** [comment]
Hi,

thanks for the details report. I think this is a bug because we use a mix of s3fs (for wildcards) and pyarrow (for performance). I think we don't pass the endpoint_override to s3fs (argument should probably be renamed).

cheers,

Maarten

**Comment by saikiran2603** [comment]
Thanks for that ! , btw i am open to pitch in and help with a PR to fix this if you could point me to the right direction !

**Comment by maartenbreddels** [comment]
Cool, I think the starting point is here:
https://github.com/vaexio/vaex/blob/65ee8a4a3ea2ca7998d14731aed50a1531844378/packages/vaex-core/vaex/file/s3arrow.py#L17

We then jump to s3.py, to do the globbing, which uses s3fs.py, but in https://github.com/vaexio/vaex/blob/65ee8a4a3ea2ca7998d14731aed50a1531844378/packages/vaex-core/vaex/file/s3fs.py#L16 we actually *do* translate the `endpoint_override` option, but those downstream libraries have a tendency to change argument names, so maybe `endpoint_url` is not the right way.

Hope that helps, and looking forward to a PR if you fix it!

**Comment by JovanVeljanoski** [comment]
@saikiran2603 you can also join the slack (see readme at the front page) which can be useful for quick questions and the like.

**Comment by saikiran2603** [comment]
Thanks @maartenbreddels  @JovanVeljanoski  for the pointers , i will get going on this over the week and get back !
