### ISSUE TITLE
[BUG-REPORT] Feather file not opening

### ISSUE THREAD

**Issue by abf7d** [vaexio/vaex#1805]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
I recently upgraded to Vaex 4.7 for my application, which works on one computer. When I tried updating on another computer, my app runs but it fails when trying to load a feather file. I compared the versions of Vaex on both computers and they are the same. 

**Software information**
 - Vaex version 
vaex                4.7.0
vaex-astro          0.9.0
vaex-core           4.7.0.post1
vaex-hdf5           0.11.1
vaex-jupyter        0.7.0
vaex-ml             0.16.0
vaex-server         0.8.0
vaex-viz            0.5.1
 - Vaex was installed via: updating the version in the requirements.txt and running `pip install -r requirements.txt`
 - OS: Windows

**Additional information**
Here are the errors I get:
```
ERROR:ThreadPoolExecutor-1_0:vaex:error opening 'data\\collection3\\full.feather'
Traceback (most recent call last):
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\__init__.py", line 231, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataset.py", line 75, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\opener.py", line 29, in open
    return open(path, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 339, in open
    return DatasetArrowIPCFile(path, fs_options=fs_options, fs=fs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 259, in __init__
    self._create_columns()
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in _create_columns
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in <listcomp>
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "pyarrow\ipc.pxi", line 734, in pyarrow.lib._RecordBatchFileReader.get_batch
  File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 114, in pyarrow.lib.check_status
OSError: LZ4 decompress failed: ERROR_GENERIC
30-Dec-21 10:21:20 - vaex     - ERROR    - error opening 'data\\collection3\\full.feather'
Traceback (most recent call last):
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\__init__.py", line 231, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataset.py", line 75, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\opener.py", line 29, in open
    return open(path, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 339, in open
    return DatasetArrowIPCFile(path, fs_options=fs_options, fs=fs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 259, in __init__
    self._create_columns()
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in _create_columns
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in <listcomp>
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "pyarrow\ipc.pxi", line 734, in pyarrow.lib._RecordBatchFileReader.get_batch
  File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 114, in pyarrow.lib.check_status
OSError: LZ4 decompress failed: ERROR_GENERIC
←[32mINFO←[0m:     127.0.0.1:62657 - "←[1mGET /columns/collection3/full.feather HTTP/1.1←[0m" ←[91m500 Internal Server Error←[0m
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 214, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Work\Master\plots-explorer-api\core\api.py", line 236, in columns
    columns = await run_in_process(
  File "C:\Work\Master\plots-explorer-api\core\api.py", line 523, in run_in_process
    return await loop.run_in_executor(app.state.executor, fn, *args)  # wait and return result
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Work\Master\plots-explorer-api\core\plots\metadata.py", line 174, in get_columns
    df = get_file(path)
  File "C:\Work\Master\plots-explorer-api\core\plots\metadata.py", line 80, in get_file
    df = vaex.open(path)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\__init__.py", line 231, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataset.py", line 75, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\opener.py", line 29, in open
    return open(path, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 339, in open
    return DatasetArrowIPCFile(path, fs_options=fs_options, fs=fs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 259, in __init__
    self._create_columns()
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in _create_columns
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in <listcomp>
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "pyarrow\ipc.pxi", line 734, in pyarrow.lib._RecordBatchFileReader.get_batch
  File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 114, in pyarrow.lib.check_status
OSError: LZ4 decompress failed: ERROR_GENERIC
30-Dec-21 10:21:21 - uvicorn.error - ERROR    - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 214, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\fastapi\routing.py", line 149, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Work\Master\plots-explorer-api\core\api.py", line 236, in columns
    columns = await run_in_process(
  File "C:\Work\Master\plots-explorer-api\core\api.py", line 523, in run_in_process
    return await loop.run_in_executor(app.state.executor, fn, *args)  # wait and return result
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Work\Master\plots-explorer-api\core\plots\metadata.py", line 174, in get_columns
    df = get_file(path)
  File "C:\Work\Master\plots-explorer-api\core\plots\metadata.py", line 80, in get_file
    df = vaex.open(path)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\__init__.py", line 231, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\dataset.py", line 75, in open
    return opener.open(path, fs_options=fs_options, fs=fs, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\opener.py", line 29, in open
    return open(path, *args, **kwargs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 339, in open
    return DatasetArrowIPCFile(path, fs_options=fs_options, fs=fs)
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 259, in __init__
    self._create_columns()
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in _create_columns
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "C:\Users\afrie\AppData\Local\Programs\Python\Python39\lib\site-packages\vaex\arrow\dataset.py", line 313, in <listcomp>
    batches = [reader.get_batch(i) for i in range(reader.num_record_batches)]
  File "pyarrow\ipc.pxi", line 734, in pyarrow.lib._RecordBatchFileReader.get_batch
  File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 114, in pyarrow.lib.check_status
OSError: LZ4 decompress failed: ERROR_GENERIC
```

**Comment by maartenbreddels** [comment]
Hi Aaron,

Happy new year :). This seems like an issue with the pyarrow package. Did you compare versions? Maybe try downgrading. Please let us know if/how you fixed this, maybe the issue should be reported at Arrow if it really is a pyarrow issue.

Regards,

Maarten Breddels

**Comment by abf7d** [comment]
Happy new year Marteen!
I was trying different things on my laptop including reinstalling python and using virtual enviornments. Nothing worked, but when I rebooted my machine it things started working. I'm not sure what the issue was. I'm going to look into this a little futher to find what the issue was. I will let you know if I find anything. Thank you so much for responding!

**Comment by juanr2001** [comment]
Any news yet? I am having the same issue in AWS EMR. Vaex: 4.7.0

**Comment by JovanVeljanoski** [comment]
Can you share which pyarraw versions you have on your laptop and in AWS?

**Comment by JovanVeljanoski** [comment]
Will close this as inactive. Please reopen if needed (but please provide information relevant to the discussion above)
