### ISSUE TITLE
[BUG-REPORT] incompatibility with blake3 >= 0.3.0

### ISSUE THREAD

**Issue by francesco086** [vaexio/vaex#1852]
**Description**
`pip install vaex-core` installs the latest blake3. However, since blake3 transitioned from 0.2.1 to 0.3.0 (and 0.3.1) vaex does not work anymore.
Downgrading blake3 to 0.2.1 solves the issue.

Instructions to reproduce the problem (with python 3.9.4):
- pip install vaex-core
- run the following python script
```python
import vaex
import pandas as pd

df = pd.DataFrame({'A': [0, 1, 2], 'B': [0, 0, 1]})
vdf = vaex.from_pandas(df)
```
- obtain the following error:
```
Traceback (most recent call last):
  File "/Users/cesco/Desktop/vaex/run.py", line 7, in <module>
    vdf = vaex.from_pandas(df)
  File "/Users/cesco/Desktop/vaex/venv/lib/python3.9/site-packages/vaex/__init__.py", line 444, in from_pandas
    return from_dict(columns)
  File "/Users/cesco/Desktop/vaex/venv/lib/python3.9/site-packages/vaex/__init__.py", line 310, in from_dict
    return vaex.from_arrays(**data)
  File "/Users/cesco/Desktop/vaex/venv/lib/python3.9/site-packages/vaex/__init__.py", line 365, in from_arrays
    dataset = vaex.dataset.DatasetArrays(arrays)
  File "/Users/cesco/Desktop/vaex/venv/lib/python3.9/site-packages/vaex/dataset.py", line 1287, in __init__
    self._ids = frozendict({key: hash_array(array) for key, array in self._columns.items()})
  File "/Users/cesco/Desktop/vaex/venv/lib/python3.9/site-packages/vaex/dataset.py", line 1287, in <dictcomp>
    self._ids = frozendict({key: hash_array(array) for key, array in self._columns.items()})
  File "/Users/cesco/Desktop/vaex/venv/lib/python3.9/site-packages/vaex/dataset.py", line 165, in hash_array
    hash_info = hash_array_data(ar)
  File "/Users/cesco/Desktop/vaex/venv/lib/python3.9/site-packages/vaex/dataset.py", line 133, in hash_array_data
    blake = blake3.blake3(byte_ar, multithreading=True)
TypeError: blake3.__new__() got an unexpected keyword argument 'multithreading'
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: vaex-core 4.7.0.post1
 - Vaex was installed via: pip
 - OS: MacOs 11.6.1

**Additional information**
I will try to create a pull request that solves the issue

**Comment by JovanVeljanoski** [comment]
This has been already fixed in https://github.com/vaexio/vaex/pull/1818

Will be available in the next release.

**Comment by francesco086** [comment]
ok, whatever you find best :)
