### ISSUE TITLE
[BUG-REPORT] Get error when using apply on a specific function

### ISSUE THREAD

**Issue by tdeboer-ilmn** [vaexio/vaex#1915]
I have a genomics use case where I try to convert some coordinates from one genome build into another and I use a specific module for that called LIFTOVER that I installed with a simply ```pip install liftover```.

When I try to use the APPLY method (still looking into ways to avoid that, but first things first) it gives me a very strang error. See below.

It seems to be specific for the function I use from the liftover package, but it is just a regular python function AFAIK. Reproducing the error would require installation of liftover.

A toy example function shows that the apply was called correctly etc. but I can't seem to use the ```liftover``` module function get lifter.

Any ideas? Bug in vaex o liftover/ Operator error? It's on an ubuntu 18.04 docker image.

Here's the workflow:

```python
import vaex as vx
vx.__version__
{'vaex': '4.7.0',
 'vaex-core': '4.7.0.post1',
 'vaex-viz': '0.5.1',
 'vaex-hdf5': '0.11.1',
 'vaex-server': '0.8.0',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.7.0',
 'vaex-ml': '0.16.0'}
from liftover import get_lifter
lifter = get_lifter('hg19','hg38')

#Test if lifter works
lifter.query('1',2217096)
>>> [('chr1', 2285657, '+')]
#Yup, all good

type(lifter.query)
>>> builtin_function_or_method

#Toy data set
d = {
    'CHROM':['1', '1'],
    'GENPOS':[2217097, 2436407]
}
df = vx.from_dict(d)
df
  #    CHROM    GENPOS
  0        1   2217097
  1        1   2436407

#Toy function that works fine
def func(g,p):
    return f"('chr{g}', {p-1}, '+')"
df['lifted'] = df.apply(func, arguments=[df['CHROM'], df['GENPOS']])
df
 #    CHROM    GENPOS  lifted
  0        1   2217097  ('chr1', 2217096, '+')
  1        1   2436407  ('chr1', 2436406, '+')

#This function does not work
def liftme(g,p):
    return f"{lifter.query(g,p-1)}"
df['lifted'] = df.apply(liftme, arguments=[df['CHROM'], df['GENPOS']])
df

ERROR:MainThread:vaex:error evaluating: lifted at rows 0-2
Traceback (most recent call last):
  File "/data/.local/lib/python3.7/site-packages/vaex/scopes.py", line 113, in evaluate
    result = self[expression]
  File "/data/.local/lib/python3.7/site-packages/vaex/scopes.py", line 198, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'lambda_function_7(CHROM, GENPOS)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/.local/lib/python3.7/site-packages/vaex/dataframe.py", line 2157, in data_type
    data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
  File "/data/.local/lib/python3.7/site-packages/vaex/dataframe.py", line 2967, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size, progress=progress)
  File "/data/.local/lib/python3.7/site-packages/vaex/dataframe.py", line 6352, in _evaluate_implementation
    value = block_scope.evaluate(expression)
  File "/data/.local/lib/python3.7/site-packages/vaex/scopes.py", line 113, in evaluate
    result = self[expression]
  File "/data/.local/lib/python3.7/site-packages/vaex/scopes.py", line 188, in __getitem__
    values = self.evaluate(expression)
  File "/data/.local/lib/python3.7/site-packages/vaex/scopes.py", line 119, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/data/.local/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py", line 136, in wrapper
    result = f(*args, **kwargs)
  File "/data/.local/lib/python3.7/site-packages/vaex/expression.py", line 1618, in __call__
    return vaex.multiprocessing.apply(self._apply, args, kwargs, self.multiprocessing)
  File "/data/.local/lib/python3.7/site-packages/vaex/multiprocessing.py", line 29, in apply
    result = _get_pool().apply(f, args, kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 261, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/data/.local/lib/python3.7/site-packages/vaex/expression.py", line 1464, in __getstate__
    return self.state_get()
  File "/data/.local/lib/python3.7/site-packages/vaex/expression.py", line 1470, in state_get
    data = self.pickle(self.f)
  File "/data/.local/lib/python3.7/site-packages/vaex/expression.py", line 1458, in pickle
    return pickle.dumps(function)
  File "/data/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/data/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 784, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/data/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 726, in _save_reduce_pickle5
    save(state)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
  File "stringsource", line 2, in liftover.chain_file.ChainFile.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__

During handling of the above exception, another exception occurred:
.
.
#More errors that repeats
```

**Comment by tdeboer-ilmn** [comment]
The last line in the error log above does point to something "funky" with liftover (That chainfile is part of liftover) but cannot undstand what it means or how to correct (if even possible)...

```
File "stringsource", line 2, in liftover.chain_file.ChainFile.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

**Comment by JovanVeljanoski** [comment]
You can try to set "multiprocessing" to False in the apply function and see if that helps.

**Comment by tdeboer-ilmn** [comment]
That did the trick! Setting multiprocessing to False allows the function to be used...
I am guessing this is now much slower but at least it works!

**Comment by JovanVeljanoski** [comment]
>  I am guessing this is now much slower but at least it works!

Uhmm not necessarily. The reason i think you were getting the error is because that particular function is written in cython, which is already parallelized. By default, vaex assume a regular python function and will parallelize it for you. Hence the clash.  In any case, would be interesting to test. Anyway, this is more like an assumption/guess rather than actual knowledge on my part. 

But I am glad it works!

**Comment by maartenbreddels** [comment]
2 workaround for this (to avoid pickle issues)

1. wrap the object in a new class with a custom pickle implementation that only stored the parameters ('hg19','hg38'), this way only `'hg19','hg38'` will be pickled, and on unpickling you recreate the object again (calling `get_lifter('hg19','hg38')`).
2. pass the argument `'hg19','hg38'` to the function, where you create the lifter each time

In both cases, if creating the object is expensive, you can try to put this in some cache, so it reuses it once it's made in a process.

Hope this helps!

But, what Jovan said is true, if it's written in cython, it should have released the GIL, and you should see >100% CPU, if not that might indicate an issue with that library.

Regard,

Maarten

**Comment by tdeboer-ilmn** [comment]
I do see some significant speed with just using the multiprocessing=False option, but I will also investigate your suggestion about wrapping it in a class and implementing custom pickle...I have some more functions that would probably benefit from this approach but will move that to the discussion forum
