### ISSUE TITLE
`select_nothing` creates an invalid selection

### ISSUE THREAD

**Issue by Nicholas-Schaub** [vaexio/vaex#2060]
In summary, use of `select_nothing` before using an operation with a `selection` parameter leads to an error.

Here is a minimally reproducible script:
```python
import vaex

df = vaex.from_dict({"data1": [1,2,3], "data2": [4,5,6]})

df.select_nothing()

print(df.max(["data1"],selection=True))```

This is the resulting error message:
```bash
Traceback (most recent call last):
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 113, in evaluate
    result = self[expression]
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 198, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'default'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\cyto-explorer\test.py", line 7, in <module>
    print(df.max(["data1"],selection=True))
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 1598, in max
    return self._compute_agg('max', expression, binby, limits, shape, selection, delay, edges, progress, array_type=array_type)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 936, in _compute_agg
    return self._delay(delay, progressbar.exit_on(var))
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 1775, in _delay
    self.execute()
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\dataframe.py", line 417, in execute
    self.executor.execute()
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\execution.py", line 308, in execute
    for _ in self.execute_generator():
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\execution.py", line 432, in execute_generator
    yield from self.thread_pool.map(self.process_part, dataset.chunk_iterator(run.dataset_deps, chunk_size),
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\multithreading.py", line 110, in map
    for value in iterator:
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\itertools.py", line 5, in buffer
    values.append(next(i))
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\concurrent\futures\_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\concurrent\futures\_base.py", line 433, in result
    return self.__get_result()
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\multithreading.py", line 86, in wrapped
    return callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\execution.py", line 500, in process_part
    self.process_tasks(thread_index, i1, i2, chunks, run, df, tasks)
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\execution.py", line 549, in process_tasks
    selections = [None if s is None else fix(selection_scope.evaluate(s)) for s in task.selections]
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\execution.py", line 549, in <listcomp>
    selections = [None if s is None else fix(selection_scope.evaluate(s)) for s in task.selections]
  File "C:\Users\nicho\Anaconda3\envs\py39\lib\site-packages\vaex\scopes.py", line 119, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'default' is not defined```

I am using Python 3.9 and vaex==4.9.1.

I would expect that if a selection is "cleared" and `selection=True` that everything might be evaluated. If this is not the expected behavior, then could this be documented and maybe create a new method called `select_all()`?

**Comment by Nicholas-Schaub** [comment]
It appears as though the cause of this bug has to do with this line of code:

https://github.com/vaexio/vaex/blob/db69339891e408b07880f77d1fccecd01bf082eb/packages/vaex-core/vaex/dataframe.py#L5010

From the code comment, it appears as though the purpose of this is to prevent flooding the selection tree with `None` selections. However, it has the negative side effect of not permitting any `None` selections unless there is an existing selection. Effectively, `select_nothing` really functions as a way of erasing an existing named selection (based on this section of code alone).

It seems like a solution to this might be to check to see if a `None` selection exists when using `select_nothing`. If a `None` selection exists, use that. If it doesn't create a new `None` selection.

**Comment by maartenbreddels** [comment]
Hi,

good report. This is a tricky thing. Vaex makes a bad distinction between not having a selection, and a 'cleared' selection. For instance, after select_nothing, has_selection will return false. Maybe this is also had behaviour. I'm welcome to making this more consistent. Also, we maybe shouldn't use a defaultdict, because we accidently create entries in them as well.
Do you want to propose a all encompassing change for this?

Regards,

Maarten

**Comment by Nicholas-Schaub** [comment]
Sure. Not knowing exactly how all of this stuff is working under the hood, I'll ask a couple of philosophical questions to come up with a proposal.

1. Right now, it looks like `select_nothing` really just tries to "clear" a selection, which ends up selecting everything. What should the expected behavior be if someone uses `select_nothing` and then uses a method with `selection=True`? Should the method behave as if it's operating on an empty dataframe since nothing is selected?
2. Should there be more nuanced but well defined methods? Maybe create a `select_everything` or `select_all` to select everything? Then `select_nothing` would have nothing actually selected. Since `select_nothing` seems to have the effect of nullifying a specific selection if it exists, maybe create an analogous method called `delete_selection` or `remove_selection`?
3. Just to make sure things are properly handled, if changes are made according to 1 and 2, should we propagate these changes down a selection tree? I haven't look into the code for selection trees much yet. We've considered using them since we need a selection tree structure, but they seem a bit too opaque in the documentation.

I suspect these changes should be relatively simple to implement in the current code based on what I've seen, but that could be a completely naive statement.

**Comment by JovanVeljanoski** [comment]
My 2c:

Regarding point 1 and the OP. That should raise an error as it currently does. Maybe with a more informative error message. But is see that as equivalent to:
```python
import vaex
df = vaex.example()
df.mean('x', selection=True)
```

One is trying to use a selection that does not exist yet.

Regarding point 2: if you want to ignore selections you can always pass `df.mean('x', selection=None)` or even `df.mean('x', selection=[None, True, my_custom_selection, "y>0"])` and get the results of all those options at once.
