### ISSUE TITLE
openmany and open commands Throwing Error in Vaex 4.16 version with FLASK Library

### ISSUE THREAD

**Issue by ashsharma96** [vaexio/vaex#2305]
Hey @JovanVeljanoski  Hope you are doing fine.
I've upgraded my vaex version to the latest version and after that my code which is in flask is throwing this error:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
        return self.wsgi_app(environ, start_response)
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
        response = self.handle_exception(e)
      File "/opt/conda/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
        return cors_after_request(app.make_response(f(*args, **kwargs)))
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
        response = self.full_dispatch_request()
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/opt/conda/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
        return cors_after_request(app.make_response(f(*args, **kwargs)))
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/jovyan/work/Cassandraconnector/FlaskApis/src/app.py", line 266, in inventory_dashboard
        df = vaex.open_many(ad)
      File "/opt/conda/lib/python3.7/site-packages/vaex/__init__.py", line 287, in open_many
        dfs.append(open(filename))
      File "/opt/conda/lib/python3.7/site-packages/vaex/__init__.py", line 244, in open
        ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/vaex/dataset.py", line 68, in open
        for entry in entry_points(group='vaex.dataset.opener'):
    TypeError: entry_points() got an unexpected keyword argument 'group'
**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
  {'vaex': '4.16.0',
 'vaex-core': '4.16.1',
 'vaex-viz': '0.5.4',
 'vaex-hdf5': '0.14.1',
 'vaex-server': '0.8.1',
 'vaex-astro': '0.9.3',
 'vaex-jupyter': '0.8.1',
 'vaex-ml': '0.18.1'}
 - Flask Version: 1.1.2
 - Vaex was installed via: pip 
 - OS: AWS Jupyter
 *Note: open and openmany are working in jupyter notebook but whenever I try to Run the code in flask api then its throwing the above error. It is happening after vaex version upgrade.

**Comment by ashsharma96** [comment]
Please Ignore this issue. I updated importlib-metadata to latest version and after that it started working.

**Comment by maartenbreddels** [comment]
Hmm, yeah, I was about to take a look at that. It's a pity we cannot have a version pin for optional requirements. Thanks for opening the issue, so people who find the same issue can find a solution.

**Comment by MartenOvaere** [comment]
I installed Vaex today (pip) and get the same "TypeError: entry_points() got an unexpected keyword argument 'group'" error when I run any Vaex command in my Jupyter notebook. Any thoughts on how to solve this?
