### ISSUE TITLE
[FEATURE-REQUEST] Support Python 3.12

### ISSUE THREAD

**Issue by EwoutH** [vaexio/vaex#2397]
**Description**
Given the recent release of Python 3.12 with numerous improvements and changes, I propose that Vaex be updated to support this latest version. Ensuring compatibility will make Vaex available to a broader audience, especially those adopting the newest Python features early on. Here's a proposed workflow (feel free to edit / update):

- [ ] Update dependencies and requirements
- [ ] Modify CI/CD pipelines to include Python 3.12 in the testing matrix
- [ ] Run tests and ensure they pass
- [ ] Once tests are green, build wheels for Python 3.12
- [ ] Release a new version and upload wheels to PyPI

**Is your feature request related to a problem? Please describe.**
Currently, Python 3.12 is unsupported, doesn't compile and wheels aren't available on PyPI.

```
Collecting vaex-core
  Downloading vaex-core-4.17.1.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 23.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-zj_hkeb1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-zj_hkeb1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-zj_hkeb1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-zj_hkeb1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Notice:  A new release of pip is available: 23.2.1 -> 23.3.1
Notice:  To update, run: pip install --upgrade pip
Error: Process completed with exit code 1.
```

**Additional context**
[What’s New In Python 3.12](https://docs.python.org/3/whatsnew/3.12.html)

**Comment by vhp1360** [comment]
Hello and sorry, but I still get this error in python3.12.

**Comment by ddelange** [comment]
@vhp1360 see https://github.com/vaexio/vaex/issues/2460
