### ISSUE TITLE
[BUG-REPORT] ImportError when importing vaex

### ISSUE THREAD

**Issue by marijnkj** [vaexio/vaex#2448]
I installed vaex in a conda environment with python 3.6.13. My vaex versions are:
```
vaex                      4.5.0              pyhd8ed1ab_0
vaex-astro                0.8.3              pyhd8ed1ab_0
vaex-core                 4.5.1            py36h52d1fc4_0
vaex-hdf5                 0.10.0             pyhd8ed1ab_0
vaex-jupyter              0.6.0              pyhd8ed1ab_0
vaex-ml                   0.14.0             pyhd8ed1ab_0
vaex-server               0.6.1              pyhd8ed1ab_0
vaex-viz                  0.5.0              pyhd8ed1ab_0
```

When I call `import vaex`, the following error is thrown:
```
ERROR:MainThread:vaex:issue loading plot
Traceback (most recent call last):
  File "c:\Users\marij\miniconda3\envs\research_project_vaex\lib\site-packages\vaex\__init__.py", line 761, in <module>
    add_namespace = entry.load()
  File "c:\Users\marij\miniconda3\envs\research_project_vaex\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "c:\Users\marij\miniconda3\envs\research_project_vaex\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\Users\marij\miniconda3\envs\research_project_vaex\lib\site-packages\vaex\viz\__init__.py", line 7, in <module>
    from . import mpl
  File "c:\Users\marij\miniconda3\envs\research_project_vaex\lib\site-packages\vaex\viz\mpl.py", line 10, in <module>
    import vaex.image
  File "c:\Users\marij\miniconda3\envs\research_project_vaex\lib\site-packages\vaex\image.py", line 2, in <module>
    import PIL.Image
  File "c:\Users\marij\miniconda3\envs\research_project_vaex\lib\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.
```

I'm on Windows 11 (Home), have tried starting VSCode from the anaconda prompt with the environment activated, but otherwise really don't know how to fix this issue!

**Comment by ddelange** [comment]
this is not an issue with vaex. if you look at the last line of this traceback, you see that the error happens while PIL is trying to import its relative module `_imaging`. try `pip install --force-reinstall PIL`
