### ISSUE TITLE
`from_pandas` missing h5py in vaex-core

### ISSUE THREAD

**Issue by egpbos** [vaexio/vaex#279]
Reproduce environment:

```sh
conda create -n vaex_from_pandas_issue vaex-core pandas -c conda-forge
conda activate vaex_from_pandas_issue
```

Trigger problem:

```python
import vaex as vx
import pandas as pd
vx.from_pandas(pd.DataFrame({'x': (1,2,3), 'y': (4,5,6)}))
```

**Comment by egpbos** [comment]
The fix is probably to add h5py to the conda dependencies for vaex-core.

**Comment by JovanVeljanoski** [comment]
Thanks for this! 

Can you please also provide the error traceback?

**Comment by egpbos** [comment]
```pytb
ERROR:MainThread:vaex:error evaluating: x at rows 0-3
Traceback (most recent call last):
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 3376, in table_part
    values[name] = self.evaluate(name, i1=k1, i2=k2)
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 4713, in evaluate
    value = scope.evaluate(expression)
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/scopes.py", line 86, in evaluate
    result = self[expression]
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/scopes.py", line 111, in __getitem__
    if self.df._needs_copy(variable):
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 5032, in _needs_copy
    import vaex.file.other
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/file/__init__.py", line 10, in <module>
    import vaex.file.other
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/file/other.py", line 26, in <module>
    from vaex.dataset_mmap import DatasetMemoryMapped
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataset_mmap.py", line 31, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
ERROR:MainThread:vaex:error evaluating: y at rows 0-3
Traceback (most recent call last):
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 3376, in table_part
    values[name] = self.evaluate(name, i1=k1, i2=k2)
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 4713, in evaluate
    value = scope.evaluate(expression)
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/scopes.py", line 86, in evaluate
    result = self[expression]
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/scopes.py", line 111, in __getitem__
    if self.df._needs_copy(variable):
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 5032, in _needs_copy
    import vaex.file.other
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/file/__init__.py", line 10, in <module>
    import vaex.file.other
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/file/other.py", line 26, in <module>
    from vaex.dataset_mmap import DatasetMemoryMapped
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataset_mmap.py", line 31, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
ERROR:MainThread:vaex:error evaluating: index at rows 0-3
Traceback (most recent call last):
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 3376, in table_part
    values[name] = self.evaluate(name, i1=k1, i2=k2)
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 4713, in evaluate
    value = scope.evaluate(expression)
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/scopes.py", line 86, in evaluate
    result = self[expression]
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/scopes.py", line 111, in __getitem__
    if self.df._needs_copy(variable):
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataframe.py", line 5032, in _needs_copy
    import vaex.file.other
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/file/__init__.py", line 10, in <module>
    import vaex.file.other
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/file/other.py", line 26, in <module>
    from vaex.dataset_mmap import DatasetMemoryMapped
  File "/Users/pbos/sw/miniconda3/envs/vaex_from_pandas_issue/lib/python3.7/site-packages/vaex/dataset_mmap.py", line 31, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
  #  x      y      index
  0  error  error  error
  1  error  error  error
  2  error  error  error
```

**Comment by JovanVeljanoski** [comment]
Thank you!

**Comment by egpbos** [comment]
Maybe also good to add the above to the integration tests :)

**Comment by maartenbreddels** [comment]
Thanks! h5py should not be a dependency of vaex-core, only of vaex-hdf5. It's difficult to add this to tests, since you need to progresssively install packages and many tests don't run with all the other packages. The import is unused fix coming.

**Comment by egpbos** [comment]
Thanks for the quick fix. Wouldn't using just `vx.from_pandas(pd.DataFrame({'x': (1,2,3), 'y': (4,5,6)}))` as a test already be an improvement?

**Comment by maartenbreddels** [comment]
The problem is that the whole test suite runs only when all sub packages are installed. Ideally you'd have a test suit per sub packages and tests that span more, but that's a lot of work to split up. Maybe when mamba becomes mainstream it's easier to install/uninstall packages all the time for testing, but til now i'm fine with the current state.
