### ISSUE TITLE
vaex-core fails to import with numpy 1.15.4 under python 3.7

### ISSUE THREAD

**Issue by egpbos** [vaexio/vaex#302]
This is relevant because this is the current default configuration of Travis CI under Ubuntu Xenial with Python 3.7.

To reproduce on a random machine:

```sh
conda create -n vaex_37_fail python=3.7
pip install vaex-core
pip install numpy=1.15.4
```

Then in Python:

```python
>>> import vaex
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pbos/sw/miniconda3/envs/vaex_37_fail/lib/python3.7/site-packages/vaex/__init__.py", line 39, in <module>
    import vaex.dataframe
  File "/Users/pbos/sw/miniconda3/envs/vaex_37_fail/lib/python3.7/site-packages/vaex/dataframe.py", line 26, in <module>
    import vaex.grids
  File "/Users/pbos/sw/miniconda3/envs/vaex_37_fail/lib/python3.7/site-packages/vaex/grids.py", line 3, in <module>
    import vaex.vaexfast
ImportError: numpy.core.multiarray failed to import
```

A solution would be to set vaex-core dependencies in setup.py and requirements.txt to `numpy>=1.16`. This is what I did to fix the problem on Travis.

**Comment by arpadtamasi** [comment]
I get the same error in Google Dataproc

**Comment by robocioaca** [comment]
Hi @maartenbreddels ,

Since as of _now_ (June 5th 2021, vaex v4.2.0) the required **NumPy** version for `vaex-core` is [numpy>=1.16](https://github.com/vaexio/vaex/blob/52dac4997eec408d2222b60cf6f16f05a6bbcd2e/packages/vaex-core/setup.py#L23), is this issue still relevant for backward compatibility's sake?

Also, while installing **NumPy 1.15.4** as suggested in the issue description, **pip** is quite vocal about the dependency conflicts (so maybe the future runtime errors should not really crop up unannounced 🤷🏻 ):

```
(vaex_37_fail)sasha@trekker ~/Projects/open_source_efforts/vaex $ pip install numpy==1.15.4
Collecting numpy==1.15.4
  Using cached numpy-1.15.4-cp37-cp37m-manylinux1_x86_64.whl (13.8 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vaex-core 4.2.0 requires numpy>=1.16, but you have numpy 1.15.4 which is incompatible.
pyarrow 4.0.1 requires numpy>=1.16.6, but you have numpy 1.15.4 which is incompatible.
pandas 1.2.4 requires numpy>=1.16.5, but you have numpy 1.15.4 which is incompatible.
Successfully installed numpy-1.15.4
```
What do you think?

/cc @JovanVeljanoski 

Thank you,
Alex
