### ISSUE TITLE
Import issue: module 'vaex' has no attribute 'utils'

### ISSUE THREAD

**Issue by CsiPeT** [vaexio/vaex#363]
When trying to import with a simple: ```import vaex```

```AttributeError                            Traceback (most recent call last)
<ipython-input-10-710c8f6b7287> in <module>
----> 1 import vaex

~/Documents/GitHub/data-products/venv/lib/python3.6/site-packages/vaex/__init__.py in <module>
     37 import six
     38 
---> 39 import vaex.dataframe
     40 import vaex.dataset
     41 from vaex.functions import register_function

~/Documents/GitHub/data-products/venv/lib/python3.6/site-packages/vaex/dataframe.py in <module>
    143     return meth
    144 
--> 145 class DataFrame(object):
    146     """All local or remote datasets are encapsulated in this class, which provides a pandas
    147     like API to your dataset.

~/Documents/GitHub/data-products/venv/lib/python3.6/site-packages/vaex/dataframe.py in DataFrame()
    250 
    251     @_hidden
--> 252     @vaex.utils.deprecated('use is_category')
    253     def iscategory(self, column):
    254         return self.is_category(column)

AttributeError: module 'vaex' has no attribute 'utils'
```
My pip list (sorry it's a bit long):
```Package                  Version   
------------------------ ----------
aiofiles                 0.4.0     
aiohttp                  3.5.4     
airflow                  1.8.0     
alabaster                0.7.12    
alembic                  0.8.10    
anytree                  2.2.1     
aplus                    0.11.0    
appdirs                  1.4.3     
appnope                  0.1.0     
astropy                  3.2.1     
async-timeout            3.0.1     
attrs                    18.1.0    
avro-python3             1.8.1     
awscli                   1.16.179  
Babel                    2.6.0     
backcall                 0.1.0     
backoff                  1.5.0     
bleach                   3.1.0     
blinker                  1.4       
boto                     2.42.0    
boto3                    1.9.165   
botocore                 1.12.169  
bqplot                   0.11.6    
branca                   0.3.1     
cached-property          1.4.3     
cachetools               2.1.0     
certifi                  2018.4.16 
chardet                  3.0.4     
ciso8601                 2.1.1     
Click                    7.0       
cloudpickle              1.2.1     
colorama                 0.3.9     
coverage                 4.5.1     
croniter                 0.3.25    
cycler                   0.10.0    
Cython                   0.28.3    
decorator                4.3.2     
defusedxml               0.5.0     
dill                     0.2.8.2   
docutils                 0.14      
entrypoints              0.3       
facebook-business        3.0.0     
facebookads              2.11.4    
fastavro                 0.14.2    
Flask                    1.0.2     
Flask-Admin              1.4.1     
Flask-Cache              0.13.1    
Flask-Login              0.2.11    
flask-swagger            0.2.13    
Flask-WTF                0.12      
freezegun                0.3.10    
funcsigs                 1.0.0     
future                   0.15.2    
geoip2                   2.9.0     
gevent                   1.4.0     
gitdb2                   2.0.5     
GitPython                2.1.11    
google-api-core          1.4.0     
google-api-python-client 1.6.2     
google-auth              1.5.1     
google-cloud-bigquery    0.28.0    
google-cloud-core        0.27.1    
google-cloud-storage     1.10.0    
google-resumable-media   0.2.3     
googleapis-common-protos 1.5.3     
greenlet                 0.4.15    
grequests                0.3.0     
gunicorn                 19.3.0    
h11                      0.8.1     
h2                       3.1.0     
h5py                     2.9.0     
hpack                    3.0.0     
httplib2                 0.11.3    
Hypercorn                0.5.3     
hyperframe               5.2.0     
hypothesis               3.57.0    
idna                     2.7       
idna-ssl                 1.1.0     
ijson                    2.3       
imagesize                1.1.0     
ipydatawidgets           4.0.1     
ipykernel                5.1.0     
ipyleaflet               0.11.1    
ipympl                   0.3.3     
ipython                  7.3.0     
ipython-genutils         0.2.0     
ipyvolume                0.5.2     
ipyvuetify               0.1.7     
ipywebrtc                0.5.0     
ipywidgets               7.5.0     
isodate                  0.6.0     
ItsDangerous             1.0.0     
jedi                     0.13.3    
Jinja2                   2.10      
jmespath                 0.9.3     
joblib                   0.13.2    
JSON-log-formatter       0.2.0     
jsonschema               3.0.1     
jupyter                  1.0.0     
jupyter-client           5.2.4     
jupyter-console          6.0.0     
jupyter-core             4.4.0     
kafka                    1.3.5     
kiwisolver               1.1.0     
lightgbm                 2.2.3     
lockfile                 0.12.2    
logmatic                 0.1.7     
lxml                     3.8.0     
Mako                     1.0.7     
Markdown                 2.6.11    
MarkupSafe               1.0       
marshmallow              2.13.5    
matplotlib               3.1.1     
maxminddb                1.4.1     
mistune                  0.8.4     
multidict                4.5.2     
nbconvert                5.4.1     
nbformat                 4.4.0     
notebook                 5.7.6     
numexpr                  2.6.9     
numpy                    1.16.4    
oauth2client             4.1.2     
ordereddict              1.1       
packaging                18.0      
pandas                   0.23.1    
pandocfilters            1.4.2     
parse                    1.8.4     
parso                    0.3.4     
pexpect                  4.6.0     
pickleshare              0.7.5     
Pillow                   6.1.0     
pip                      18.0      
progressbar2             3.42.0    
prometheus-client        0.6.0     
prompt-toolkit           2.0.9     
protobuf                 3.6.0     
psutil                   4.4.2     
psycopg2                 2.7.5     
ptyprocess               0.6.0     
pyarrow                  0.10.0    
pyasn1                   0.4.3     
pyasn1-modules           0.2.1     
PyAthena                 1.3.0     
pycountry                18.12.8   
Pygments                 2.2.0     
pymssql                  2.1.4     
pyparsing                2.2.2     
pyrsistent               0.14.11   
python-daemon            2.1.2     
python-dateutil          2.7.3     
python-dotenv            0.10.1    
python-editor            1.0.3     
python-nvd3              0.14.2    
python-slugify           1.1.4     
python-snappy            0.5.3     
python-utils             2.3.0     
pythreejs                2.1.1     
pytoml                   0.1.20    
pytz                     2018.4    
PyYAML                   3.13      
pyzmq                    18.0.1    
qtconsole                4.4.3     
Quart                    0.6.12    
ratelimit                2.2.0     
requests                 2.11.1    
requests-toolbelt        0.8.0     
rsa                      3.4.2     
s3fs                     0.2.1     
s3transfer               0.2.1     
salesforce-bulk          2.1.0     
scikit-learn             0.20.3    
scipy                    1.2.1     
Send2Trash               1.5.0     
setproctitle             1.1.10    
setuptools               39.1.0    
simple-salesforce        0.74.2    
simplejson               3.16.0    
six                      1.12.0    
sklearn-pandas           1.8.0     
slacker                  0.9.65    
smmap2                   2.0.5     
snowballstemmer          1.2.1     
sortedcontainers         2.1.0     
Sphinx                   1.8.1     
sphinxcontrib-websupport 1.1.0     
SQLAlchemy               1.2.12    
tables                   3.4.4     
tabulate                 0.8.3     
tenacity                 5.0.2     
terminado                0.8.1     
testpath                 0.4.2     
thrift                   0.9.3     
tornado                  6.0.1     
tqdm                     4.32.2    
traitlets                4.3.2     
traittypes               0.2.1     
typing-extensions        3.7.2     
ujson                    1.35      
unicodecsv               0.14.1    
Unidecode                1.0.22    
uritemplate              3.0.0     
urllib3                  1.23      
vaex                     2.0.2     
vaex-arrow               0.3.5     
vaex-astro               0.5.0     
vaex-core                0.9.2     
vaex-hdf5                0.5.2     
vaex-jupyter             0.3.0     
vaex-server              0.2.1     
vaex-viz                 0.3.4     
wario                    0.2.7.dev0
watchtower               0.5.2     
wcwidth                  0.1.7     
webencodings             0.5.1     
Werkzeug                 0.14.1    
widgetsnbextension       3.5.0     
wr-metrics               0.1.0     
wsproto                  0.13.0    
WTForms                  2.2.1     
xarray                   0.12.3    
yarl                     1.3.0     
zeep                     2.3.0     
zope.deprecation         4.3.0  
```

**Comment by maartenbreddels** [comment]
Thanks for the report.
I'm surprised to see this error, since on like 17 in do `import vaex.utils`. Which Python version are you using, and could you try:
```python
import vaex  # ignore the error you get above.
print(vaex.utils.__file__)
import utils
print(utils.__file__)
```

**Comment by maartenbreddels** [comment]
No feedback on this, so I am assuming it's an installation issue and/or it was resolved. Feel free to reopen.

**Comment by nunocoutinho** [comment]
I just had the same error. Does anyone knows the cause?

**Comment by candalfigomoro** [comment]
@maartenbreddels
Same issue

**Comment by pietrolesci** [comment]
Hi there,

Today I was trying to spin up a copy of a streamlit app that runs [here](https://huggingface.co/spaces/pietrolesci/wordify) but does not run [here](https://huggingface.co/spaces/MilaNLProc/wordify). Everything is the same as they are both automatically synced from the [same github repo](https://github.com/MilaNLProc/wordify-webapp-streamlit). This also means the same version of `vaex==4.6.0`. 
In one of the app, I had the same error described in this issue, with this stacktrace:

```
2021-12-29 13:41:03.956 Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/app.py", line 3, in <module>
    from src.components import analysis, docs, faq, footer, form, presentation
  File "/home/user/app/src/components.py", line 7, in <module>
    from src.preprocessing import PreprocessingPipeline
  File "/home/user/app/src/preprocessing.py", line 9, in <module>
    import vaex
  File "/home/user/.local/lib/python3.8/site-packages/vaex/__init__.py", line 42, in <module>
    import vaex.dataframe
  File "/home/user/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 32, in <module>
    import vaex.execution
  File "/home/user/.local/lib/python3.8/site-packages/vaex/execution.py", line 20, in <module>
    import vaex.memory
  File "/home/user/.local/lib/python3.8/site-packages/vaex/memory.py", line 6, in <module>
    import vaex.settings
  File "/home/user/.local/lib/python3.8/site-packages/vaex/settings.py", line 109, in <module>
    import vaex.server.settings
ModuleNotFoundError: No module named 'vaex.server.settings'

2021-12-29 13:41:47.935 Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/app.py", line 3, in <module>
    from src.components import analysis, docs, faq, footer, form, presentation
  File "/home/user/app/src/components.py", line 7, in <module>
    from src.preprocessing import PreprocessingPipeline
  File "/home/user/app/src/preprocessing.py", line 9, in <module>
    import vaex
  File "/home/user/.local/lib/python3.8/site-packages/vaex/__init__.py", line 42, in <module>
    import vaex.dataframe
  File "/home/user/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 32, in <module>
    import vaex.execution
  File "/home/user/.local/lib/python3.8/site-packages/vaex/execution.py", line 20, in <module>
    import vaex.memory
  File "/home/user/.local/lib/python3.8/site-packages/vaex/memory.py", line 6, in <module>
    import vaex.settings
  File "/home/user/.local/lib/python3.8/site-packages/vaex/settings.py", line 16, in <module>
    _default_home = vaex.utils.get_vaex_home()
AttributeError: partially initialized module 'vaex' has no attribute 'utils' (most likely due to a circular import)

2021-12-29 13:42:17.292 Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/app.py", line 3, in <module>
    from src.components import analysis, docs, faq, footer, form, presentation
  File "/home/user/app/src/components.py", line 7, in <module>
    from src.preprocessing import PreprocessingPipeline
  File "/home/user/app/src/preprocessing.py", line 9, in <module>
    import vaex
  File "/home/user/.local/lib/python3.8/site-packages/vaex/__init__.py", line 42, in <module>
    import vaex.dataframe
  File "/home/user/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 32, in <module>
    import vaex.execution
  File "/home/user/.local/lib/python3.8/site-packages/vaex/execution.py", line 20, in <module>
    import vaex.memory
  File "/home/user/.local/lib/python3.8/site-packages/vaex/memory.py", line 6, in <module>
    import vaex.settings
  File "/home/user/.local/lib/python3.8/site-packages/vaex/settings.py", line 16, in <module>
    _default_home = vaex.utils.get_vaex_home()
AttributeError: partially initialized module 'vaex' has no attribute 'utils' (most likely due to a circular import)

2021-12-29 13:44:47.404 Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/app.py", line 3, in <module>
    from src.components import analysis, docs, faq, footer, form, presentation
  File "/home/user/app/src/components.py", line 7, in <module>
    from src.preprocessing import PreprocessingPipeline
  File "/home/user/app/src/preprocessing.py", line 9, in <module>
    import vaex
  File "/home/user/.local/lib/python3.8/site-packages/vaex/__init__.py", line 42, in <module>
    import vaex.dataframe
  File "/home/user/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 32, in <module>
    import vaex.execution
  File "/home/user/.local/lib/python3.8/site-packages/vaex/execution.py", line 20, in <module>
    import vaex.memory
  File "/home/user/.local/lib/python3.8/site-packages/vaex/memory.py", line 6, in <module>
    import vaex.settings
  File "/home/user/.local/lib/python3.8/site-packages/vaex/settings.py", line 16, in <module>
    _default_home = vaex.utils.get_vaex_home()
AttributeError: partially initialized module 'vaex' has no attribute 'utils' (most likely due to a circular import)

2021-12-29 14:14:59.120 Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/app.py", line 3, in <module>
    from src.components import analysis, docs, faq, footer, form, presentation
  File "/home/user/app/src/components.py", line 7, in <module>
    from src.preprocessing import PreprocessingPipeline
  File "/home/user/app/src/preprocessing.py", line 9, in <module>
    import vaex
  File "/home/user/.local/lib/python3.8/site-packages/vaex/__init__.py", line 42, in <module>
    import vaex.dataframe
  File "/home/user/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 32, in <module>
    import vaex.execution
  File "/home/user/.local/lib/python3.8/site-packages/vaex/execution.py", line 20, in <module>
    import vaex.memory
  File "/home/user/.local/lib/python3.8/site-packages/vaex/memory.py", line 6, in <module>
    import vaex.settings
  File "/home/user/.local/lib/python3.8/site-packages/vaex/settings.py", line 16, in <module>
    _default_home = vaex.utils.get_vaex_home()
AttributeError: partially initialized module 'vaex' has no attribute 'utils' (most likely due to a circular import)
```

Updating to vaex == 4.7.0 solved the issue in my case. Hope this can be useful.

**Comment by maartenbreddels** [comment]
Thanks for sharing, note that it's not the same issue btw, just happens to have a similar error message.

> ModuleNotFoundError: No module named 'vaex.server.settings'

I think this can happen when you have a newer Vaex-core, but an older Vaex-server. Note that you don't have to install all of vaex, you can pick individual sub packages and get much less dependencies and avoid these kind of complex interdepdenency issues. Note that we are trying to avoid such issues by having the vaex metapackage (which will install all vaex sub packages) be more strict on the versions.
