### ISSUE TITLE
Converting to Datetime fails

### ISSUE THREAD

**Issue by theTibi** [vaexio/vaex#510]
Hi, 

I have originally posted the question on [stackoverflow](https://stackoverflow.com/questions/59345130/pandas-filtering-and-convert-to-date-to-datetime64ns/59346946) but it looks like it is a bug.

Here is my test data:
```
In [84]: df2
Out[84]:
  #  name    date
  0  aa      2012-11-30T14:00:00+01:00
  1  bb      2012-12-01T08:16:00+01:00
  2  cc      2012-12-01T10:14:00+01:00
  3  ee      2012-12-01T11:05:00+01:00
  4  gg      2012-12-01T11:05:00+01:00
```

```
In [85]: df2.dtypes
Out[85]:
name    <class 'str'>
date    <class 'str'>
dtype: object
```

If I try to convert `date` which is an `str` to `datetime` with the following command:
```
df2['pdate']=df2.date.astype('datetime64[ns]')
```
I get an error when I try to use `df2`:
```
In [87]: df2
Out[87]: ERROR:MainThread:vaex:error evaluating: pdate at rows 0-5
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 94, in evaluate
    result = self[expression]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 141, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: 'Unknown variables or column: "astype(date, \'datetime64[ns]\')"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 3467, in table_part
    values[name] = df.evaluate(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 5038, in evaluate
    dtype = dtypes[expression] = self.dtype(expression, internal=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 2005, in dtype
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 5143, in evaluate
    value = scope.evaluate(expression)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 94, in evaluate
    result = self[expression]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 136, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 100, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/functions.py", line 2106, in _astype
    return x.astype(dtype)
AttributeError: 'ColumnStringArrow' object has no attribute 'astype'
ERROR:MainThread:vaex:error evaluating: pdate at rows 0-5
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 94, in evaluate
    result = self[expression]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 141, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: 'Unknown variables or column: "astype(date, \'datetime64[ns]\')"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 3467, in table_part
    values[name] = df.evaluate(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 5038, in evaluate
    dtype = dtypes[expression] = self.dtype(expression, internal=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 2005, in dtype
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/dataframe.py", line 5143, in evaluate
    value = scope.evaluate(expression)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 94, in evaluate
    result = self[expression]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 136, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/scopes.py", line 100, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/vaex/functions.py", line 2106, in _astype
    return x.astype(dtype)
AttributeError: 'ColumnStringArrow' object has no attribute 'astype'

  #  name    date                       pdate
  0  aa      2012-11-30T14:00:00+01:00  error
  1  bb      2012-12-01T08:16:00+01:00  error
  2  cc      2012-12-01T10:14:00+01:00  error
  3  ee      2012-12-01T11:05:00+01:00  error
  4  gg      2012-12-01T11:05:00+01:00  error
```

Let me know if you need any more details.

Thanks,
Tibi

**Comment by JovanVeljanoski** [comment]
Hi @theTibi 

I think this is more of a missing feature rather than a bug, but nonetheless it is a known issue: #368  and work was started #440. 

Thanks for bringing it up!
Cheers, 
Jovan.

**Comment by theTibi** [comment]
Thank you I didn't see those reports. In that case this can be closed. Thanks.

**Comment by maartenbreddels** [comment]
I didn't realise that @JovanVeljanoski. @theTibi you can track #440 for when we fix this.

**Comment by maartenbreddels** [comment]
fixed in https://github.com/vaexio/vaex/blob/master/CHANGELOG.md#vaex-250-2019-12-16
let us know if that helped.

**Comment by maartenbreddels** [comment]
Assuming this is fixed, if not, feel free to reopen.

**Comment by pjgao** [comment]
what if datetime string like "202011091259"?

**Comment by JovanVeljanoski** [comment]
Hi @pjgao 

Just reformat the string into a something that np.datetime64 will recognize. Something lik
```
x = ['202011091259', '202011101259', '202011111259']
df = vaex.from_arrays(x=x)

df['tmp'] = df.x.str.slice(0, 4) + '-' + df.x.str.slice(4, 6) + '-' + df.x.str.slice(6, 8) + 'T' + df.x.str.slice(8, 10) + ':' + df.x.str.slice(10, 12)
df['datetime'] = df.tmp.astype('datetime64')

print(df)
```

I hope this helps

**Comment by pjgao** [comment]
> Hi @pjgao Just reformat the string into a something that np.datetime64 will recognize. Something like ``` x = ['202011091259', '202011101259', '202011111259'] df = vaex.from_arrays(x=x) df['tmp'] = df.x.str.slice(0, 4) + '-' + df.x.str.slice(4, 6) + '-' + df.x.str.slice(6, 8) + 'T' + df.x.str.slice(8, 10) + ':' + df.x.str.slice(10, 12) df['datetime'] = df.tmp.astype('datetime64') print(df) ```

It works, Thanks a lot!
