### ISSUE TITLE
Failed to run `vaex convert file` command

### ISSUE THREAD

**Issue by openaphid** [vaexio/vaex#597]
I tried to convert a fits file with heads to hdf5:
`vaex convert file sample.fits sample.hdf5`

An error is thrown as following while :
```
Traceback (most recent call last):
  File "/data/tmp-venv/bin/vaex", line 10, in <module>
    sys.exit(main())
  File "/data/tmp-venv/lib/python3.7/site-packages/vaex/__main__.py", line 114, in main
    vaex.export.main([os.path.basename(args[0]) + " " + args[1]] + args[2:])
  File "/data/tmp-venv/lib/python3.7/site-packages/vaex/export.py", line 482, in main
    progressbar.finish()
  File "/data/tmp-venv/lib/python3.7/site-packages/vaex/misc/progressbar.py", line 95, in finish
    print(repr(self), file=self.output, end=' ')
  File "/data/tmp-venv/lib/python3.7/site-packages/vaex/misc/progressbar.py", line 104, in __repr__
    output = "\r" + bar + super(ProgressBar, self).__repr__()
  File "/data/tmp-venv/lib/python3.7/site-packages/vaex/misc/progressbar.py", line 59, in __repr__
    return self.format % self.info()
  File "/data/tmp-venv/lib/python3.7/site-packages/vaex/misc/progressbar.py", line 31, in info
    cpu_time_delta = self.stime - self.stime0 + self.utime - self.utime0
AttributeError: 'ProgressBar' object has no attribute 'stime0'
```

There is an issue in `progressbar.py`:
- `self.stime0` is only declared while `self.value` is zero. https://github.com/vaexio/vaex/blob/54d5d30e28360cbc0d35de9cba0c09c3c6ab016e/packages/vaex-core/vaex/misc/progressbar.py#L21

- but `self.stime0` is always accessed in the main path
https://github.com/vaexio/vaex/blob/54d5d30e28360cbc0d35de9cba0c09c3c6ab016e/packages/vaex-core/vaex/misc/progressbar.py#L31

**Comment by maartenbreddels** [comment]
Hi,

Thanks for the report, I'll try to reproduce that with a unittest, should be easy to fix I think, unless you or @JovanVeljanoski beats me to it :)

cheers,

Maarten

**Comment by nateraw** [comment]
Hey, guys...just bumping this one. I'm having the same issue.

**Comment by maartenbreddels** [comment]
Thanks for that hint.
#710 should fix this!
