### ISSUE TITLE
After install vaex, the original jupyter lab always die cause many error

### ISSUE THREAD

**Issue by lx1054331851** [vaexio/vaex#610]
Every time after I install vaex in my conda env enviroment, the jupyter server in the env enviroment always can not start properly.

The error is below:
`Microsoft Windows [版本 10.0.18363.657]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\lx105>conda -V
conda 4.8.2

C:\Users\lx105>jupyter notebook
[I 19:34:11.013 NotebookApp] The port 8888 is already in use, trying another port.
[I 19:34:11.098 NotebookApp] JupyterLab extension loaded from C:\Anaconda3\lib\site-packages\jupyterlab
[I 19:34:11.098 NotebookApp] JupyterLab application directory is C:\Anaconda3\share\jupyter\lab
[I 19:34:11.102 NotebookApp] Serving notebooks from local directory: C:\Users\lx105
[I 19:34:11.103 NotebookApp] The Jupyter Notebook is running at:
[I 19:34:11.103 NotebookApp] http://localhost:8889/?token=65560b1681753ac94c0db8e423c2adcac1c5b431ecccdad9
[I 19:34:11.103 NotebookApp]  or http://127.0.0.1:8889/?token=65560b1681753ac94c0db8e423c2adcac1c5b431ecccdad9
[I 19:34:11.104 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:34:11.170 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/lx105/AppData/Roaming/jupyter/runtime/nbserver-14588-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=65560b1681753ac94c0db8e423c2adcac1c5b431ecccdad9
     or http://127.0.0.1:8889/?token=65560b1681753ac94c0db8e423c2adcac1c5b431ecccdad9
[I 19:34:20.427 NotebookApp] Creating new notebook in
[I 19:34:23.544 NotebookApp] Kernel started: 8a1ffb91-2de4-4fc9-8bd3-4116e99d3bb0
[I 19:34:46.011 NotebookApp] Creating new notebook in
[I 19:34:47.710 NotebookApp] Kernel started: 74afaa5a-c0b4-4da1-b6a2-6bf969045e40
Traceback (most recent call last):
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\connect.py", line 24, in <module>
    import zmq
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: 找不到指定的模块。
[I 19:34:50.689 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\connect.py", line 24, in <module>
    import zmq
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: 找不到指定的模块。
[I 19:34:53.693 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\connect.py", line 24, in <module>
    import zmq
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: 找不到指定的模块。
[I 19:34:56.716 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\connect.py", line 24, in <module>
    import zmq
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: 找不到指定的模块。
[I 19:34:59.728 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Anaconda3\envs\python37\lib\site-packages\jupyter_client\connect.py", line 24, in <module>
    import zmq
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Anaconda3\envs\python37\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: 找不到指定的模块。
[W 19:35:02.732 NotebookApp] KernelRestarter: restart failed
[W 19:35:02.732 NotebookApp] Kernel 74afaa5a-c0b4-4da1-b6a2-6bf969045e40 died, removing from map.
[W 19:35:47.807 NotebookApp] Timeout waiting for kernel_info reply from 74afaa5a-c0b4-4da1-b6a2-6bf969045e40
[E 19:35:47.808 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 74afaa5a-c0b4-4da1-b6a2-6bf969045e40)
[W 19:35:48.843 NotebookApp] 404 GET /api/kernels/74afaa5a-c0b4-4da1-b6a2-6bf969045e40/channels?session_id=51018f94e91f4311b4e32fd72a199e2b (::1): Kernel does not exist: 74afaa5a-c0b4-4da1-b6a2-6bf969045e40
[W 19:35:48.868 NotebookApp] 404 GET /api/kernels/74afaa5a-c0b4-4da1-b6a2-6bf969045e40/channels?session_id=51018f94e91f4311b4e32fd72a199e2b (::1) 26.98ms referer=None
[W 19:35:50.890 NotebookApp] Replacing stale connection: 74afaa5a-c0b4-4da1-b6a2-6bf969045e40:51018f94e91f4311b4e32fd72a199e2b
[I 19:36:23.368 NotebookApp] Saving file at /Untitled.ipynb
[I 19:36:48.350 NotebookApp] Saving file at /Untitled1.ipynb
[W 19:39:55.350 NotebookApp] Replacing stale connection: 74afaa5a-c0b4-4da1-b6a2-6bf969045e40:51018f94e91f4311b4e32fd72a199e2b
`

**Comment by maartenbreddels** [comment]
Hi,

that is a strange error, are you saying it is solved? It could be a tornado issue.

cheers,

Maarten
