### ISSUE TITLE
Support shift

### ISSUE THREAD

**Issue by maartenbreddels** [vaexio/vaex#660]
https://stackoverflow.com/questions/60995917

**Comment by yetyetanotherusername** [comment]
Not sure but i think i'm seeing another issue not covered by #661 when I run your suggestion against vaex 2.6.1:

```
 #    x    y  shifted_y
 0    0    0  error    
 1    1    1  error    
 2    2    4  error
 3    3    9  error
 4    4   16  error
 5    5   25  error
 6    6   36  error
 7    7   49  error
 8    8   64  error
 9    9   81  error
```

Here's the stack
```
ERROR:MainThread:vaex:error evaluating: shifted_y at rows 0-10                                                                                                                  
Traceback (most recent call last):                                                                                                                                              
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 97, in evaluate                                                           
    result = self[expression]                                                                                                                                                   
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 144, in __getitem__                                                       
    raise KeyError("Unknown variables or column: %r" % (variable,))                                                                                                             
KeyError: "Unknown variables or column: '__y'"                                                                                                                                  
                                                                                                                                                                                
During handling of the above exception, another exception occurred:                                                                                                             
                                                                                                                                                                                
Traceback (most recent call last):                                                                                                                                              
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 2031, in dtype                                                         
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)                                                                                       
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 5120, in evaluate                                                      
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 5287, in _evaluate_implementation                                      
    value = scope.evaluate(expression)                                                               
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 97, in evaluate                                                           
    result = self[expression]                     
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 139, in __getitem__                                                       
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])                                                                                          
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 103, in evaluate                                                          
    result = eval(expression, expression_namespace, self)                                            
  File "<string>", line 1, in <module>                                                               
NameError: name '__y' is not defined                                                                 

During handling of the above exception, another exception occurred:                                                                                                             

Traceback (most recent call last):                                                                   
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 97, in evaluate                                                           
    result = self[expression]                     
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 144, in __getitem__                                                       
    raise KeyError("Unknown variables or column: %r" % (variable,))                                                                                                             
KeyError: "Unknown variables or column: '__y'"                                                       

During handling of the above exception, another exception occurred:                                                                                                             

Traceback (most recent call last):                                                                   
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 3523, in table_part                                                    
    values[name] = df.evaluate(name)                                                                 
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 5120, in evaluate                                                      
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 5212, in _evaluate_implementation                                      
    dtypes[expression] = df.dtype(expression, internal=False)                                                                                                                   
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 2033, in dtype                                                         
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)                                                                                        
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 5120, in evaluate                                                      
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/dataframe.py", line 5287, in _evaluate_implementation                                      
    value = scope.evaluate(expression)                                                               
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 97, in evaluate                                                           
    result = self[expression]                     
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 139, in __getitem__                                                       
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])                                                                                          
  File "/home/sgrill/Documents/repos/ml_heat/.env/lib64/python3.7/site-packages/vaex/scopes.py", line 103, in evaluate                                                          
    result = eval(expression, expression_namespace, self)                                            
  File "<string>", line 1, in <module>                                                               
NameError: name '__y' is not defined                                                                 
```

**Comment by maartenbreddels** [comment]
My guess this is fixed in master, are you ok trying a dev install?

**Comment by yetyetanotherusername** [comment]
Works, sorry for the noise.

**Comment by acubed3** [comment]
What about 4.0 version? It seems that this feature does not work. I have the same error

**Comment by janakact** [comment]
I did something like this. seems like it is working.

```python
shifted_df= df[:-n]
shifted_df["x"] = df.evaluate(df.x, i1=n, i2=len(df))
```

**Comment by acubed3** [comment]
@janakact 

It seems that it works correctly:

<pre><code>@vaex.register_dataframe_accessor('vx', override=True)
    class VaexUsefulTools(object):
        def __init__(self, df):
            self.df = df

        # vx.shift is the analog of pandas.shift() but add the shifted column with specified name to the end of initial df

        def shift(self, column, new_column, n, cyclic=True, inplace=False):
            df = self.df.copy().drop(column)
            df_column = self.df[[column]]
            if cyclic:
                df_head = df_column[-n:]
            else:
                df_head = vaex.from_dict({column: np.ma.filled(np.ma.masked_all(n, dtype=float), 0)})
            df_tail = df_column[:-n]

            df_shifted = df_head.concat(df_tail)
            df_shifted.rename(column, new_column)

            return df_shifted</pre></code>

It returns shifted column which can be immediately joined with dataframe. For my goals `dtype=float` and fill by zero are convenient. It seems that `dtype` and `np.ma.filled` can be esaily modified.

**Comment by JovanVeljanoski** [comment]
Shift is now supported, although this is an area of active work. If you encounter problems please open a new issue, with a reproducible example is possible. 
Thanks all!
