### ISSUE TITLE
dtype error 

### ISSUE THREAD

**Issue by heyuqi1970** [vaexio/vaex#681]
when I sort, I get follow error :

`raceback (most recent call last):
  File "/Users/.conda/envs/vaex/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
TypeError: '<' not supported between instances of 'str' and 'float'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/.conda/envs/vaex/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-92191b68134c>", line 1, in <module>
    df.sort('ACC_NAME', ascending=True)
  File "/Users/heyuqi/development/vaex/install/vaex/packages/vaex-core/vaex/dataframe.py", line 4112, in sort
    indices = np.argsort(values, kind=kind)
  File "<__array_function__ internals>", line 6, in argsort
  File "/Users/.conda/envs/vaex/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1105, in argsort
    return _wrapfunc(a, 'argsort', axis=axis, kind=kind, order=order)
  File "/Users/.conda/envs/vaex/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 70, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/.conda/envs/vaex/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: '<' not supported between instances of 'str' and 'float'`

Is that mean have two dtype in column?

**Comment by heyuqi1970** [comment]
I can pass through sort when I use pandas .

**Comment by JovanVeljanoski** [comment]
Hi @heyuqi1970 

I will assume that the column that you are trying to sort by is of dtype object. How do you sort values in that sense? You can perhaps convert them to strings and sort them like as such. 

I do not know how pandas sorts column of dtype objects.

Also, how do you read in data into vaex? If you pass it via pandas, a good practice is to make sure that you have not columns of dtype=object, i.e. each entry in a column should be of the same data type. 

I hope this helps

**Comment by heyuqi1970** [comment]
HI @JovanVeljanoski 
Follow is my code, 
`
df = vaex.read_csv("testdata1.csv", warn_bad_lines=True, error_bad_lines=False)
df.dtypes`

> Out[8]
> TRD_DATE                     int64
> MATCHED_TIME         <class 'str'>
> ORDER_DATE           <class 'str'>
> CUST_CODE                    int64
> ACC_NAME               <class 'str'>
> USER_CHAR                    int64
> SERIAL_NO                    int64
> CUST_CLS                     int64
> SPECIAL_CUST               float64
> dtype: object

Please forgive me for being a novice.
Is <class 'str'>  an object dtype? and how to convert object to string in vaex.

**Comment by JovanVeljanoski** [comment]
Hi @heyuqi1970 

Hmm that is strange. Just to test things.. can you try sorting by any other column?

Also, would it be possible to provide a small sample of your data, can be of course anonymity or some random entries that look similar to what you have, just so we can reproduce your issue on our end. 

I tried to guess what the data may be like, but I've not been able to make it crash (well I did, but for dtype object, which you do not have in your example.. but I am almost certain it has something  to do with dtype object).

(this may be a bug)
Thanks!

**Comment by heyuqi1970** [comment]
HI @JovanVeljanoski 

 Yes, I can sort other column.

Attach is sample file. 
The data has 1 million lines. I tried to get a small part of the data, but the error could not be reproduced 
[test5.csv.zip](https://github.com/vaexio/vaex/files/4497164/test5.csv.zip)

**Comment by JovanVeljanoski** [comment]
Hi @heyuqi1970 

Thank you for sharing your data. I have figure out why the issue happens. It is most likely a bug in vaex that is a bit exotic perhaps. 

I will describe it why it happens so maybe you can figure out how to avoid it. 

Your file is in CSV format. When reading such files, vaex uses pandas in the background. In the file that you sent, the column ACC_NAME has 2 missing values, and the MATCHED_TIME has one such missing value. These are the rows where this happens (the index is their location, i.e. row number):

<img width="281" alt="image" src="https://user-images.githubusercontent.com/18574951/79662025-c0628580-81b4-11ea-9de5-44faeacaedc4.png">

pandas represents such missing values with NaN (not a number) thus mixing up strings and numbers.  When we read the data from pandas into vaex we typically automatically fix such inconsistencies, but this case I guess we have not covered (@maartenbreddels ). So even though `df.dtypes` says the columns  ACC_NAME and MATCHED_TIME are of type strings, they are in fact objects, and thus we don't know how to sort them.

What does this mean for you: 
Until we fix this, you have 3 options that I can think of:
 - if you data is static, you can just manually edit your csv file and add some entries where the missing data is, so then this problem will not appear (I do not recommend this however!)
- better is to impute the data, i.e. fill missing values once you read them in. You can do it like this:
```
df_filled = df.fillna('missing')
df_filled.sort('ACC_NAME')
```
-  if the rows where the missing values appear are rare or not so important, you can simply drop them:
```
df_dropped = df.dropna()
df_dropped.sort('ACC_NAME')
```

Any of these methods will work. 

Thank you for helping me to figure this out!

I hope this helps

**Comment by heyuqi1970** [comment]
HI, @JovanVeljanoski 

Thanks for your patient and detailed answer.
According your methods , can resovled issues.

I also did some tests, and found that an error would be raised only in the CSV files which column contents were character type.  Meanwhile it won't work when there exists any blank unit in the same column mentioned. 

I'm looking forward to fixing this bug . 

Follow is my test data

[test6.csv.zip](https://github.com/vaexio/vaex/files/4499246/test6.csv.zip)

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks fr the info but it was not really necessary: I explained the problem to you meaning we know what it is :). We are working on fixing it soon.

Thanks.

I will keep this issue opened until it is fixed. Cheers.
