### ISSUE TITLE
Assigning an join() expression to a non-current dataframe fails. And wrong where() output if it selects NA values

### ISSUE THREAD

**Issue by And0k** [vaexio/vaex#732]
```python
import vaex, pandas as pd
ds = vaex.from_arrays(a=['a', 'a', 'c', 'd', 'e', 'f', 'f'], row_index=range(7))
Out[4]: 
  #  a      row_index
  0  a              0
  1  a              1
  2  c              2
  3  d              3
  4  e              4
  5  f              5
  6  f              6
df = pd.DataFrame({'a': ['A', 'B', 'F', 'G']}, index=[0, 1, 5, 6])
dsj = ds.join(vaex.from_pandas(df), left_on='row_index', right_on='index', rsuffix='u')
dsj
Out[5]: 
  #  a      row_index  au    index
  0  a              0  A     0
  1  a              1  B     1
  2  c              2  --    --
  3  d              3  --    --
  4  e              4  --    --
  5  f              5  F     5
  6  f              6  G     6

# Replacing a with NA where it is in au:
combined = dsj['au'].isna().where(dsj['au'], dsj['a'])
combined
Out[6]: 
Expression = where(isna(au), au, a)
Length: 7 dtype: object (expression)
------------------------------------
0  a
1  a
2  G
3  G
4  G
5  f
6  f
```
First issue: why "G" in values?

Bug 2 - on assignment:
```python
ds['combined'] = combined
ds
Out[37]: ERROR:MainThread:vaex:error evaluating: combined at rows 0-7
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'where(isna(au), au, a)'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 2031, in dtype
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5287, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'au' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'where(isna(au), au, a)'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5212, in _evaluate_implementation
    dtypes[expression] = df.dtype(expression, internal=False)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 2033, in dtype
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5287, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'au' is not defined
ERROR:MainThread:vaex:error evaluating: combined at rows 0-7
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'where(isna(au), au, a)'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 2031, in dtype
    data = self.evaluate(expression, 0, 1, filtered=False, internal=True, parallel=False)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5287, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'au' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'where(isna(au), au, a)'"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 3523, in table_part
    values[name] = df.evaluate(name)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5212, in _evaluate_implementation
    dtypes[expression] = df.dtype(expression, internal=False)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 2033, in dtype
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5120, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\dataframe.py", line 5287, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 97, in evaluate
    result = self[expression]
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "C:\Users\and0k\anaconda3\envs\py3.7x64h5togrid_no_pip1\lib\site-packages\vaex\scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'au' is not defined
  #  a      row_index  combined
  0  a              0  error
  1  a              1  error
  2  c              2  error
  3  d              3  error
  4  e              4  error
  5  f              5  error
  6  f              6  error
```
But why this works?
```python
dsj['combined'] = combined
dsj
Out[13]: 
  #  a      row_index  au    index    combined
  0  a              0  A     0        A
  1  a              1  B     1        B
  2  c              2  --    --       c
  3  d              3  --    --       d
  4  e              4  --    --       e
  5  f              5  F     5        F
  6  f              6  G     6        G
```

**Comment by And0k** [comment]
3. join() behaves different for expressions - it adds some not NA values where no data in right dataframe
import vaex, pandas as pd
   ...: ds = vaex.from_arrays(a=['a', 'a', 'c', 'd', 'e', 'f', 'f'], index=range(7))
   ...: ds_right = vaex.from_arrays(a=['A', 'B', 'F', 'G'], index=[0, 1, 5, 6])
   ...: ds_right_part = ds_right[ds_right['a'].str.contains('A|F')]
   ...: dsj = ds.join(ds_right_part, left_on='index', right_on='index', rsuffix='_r')
   ...: dsj
Out[29]: 
  #  a      index  a_r      index_r
  0  a          0  A              0
  1  a          1  F              5
  2  c          2  F              5
  3  d          3  F              5
  4  e          4  F              5
  5  f          5  F              5
  6  f          6  F              5

**Comment by And0k** [comment]
Bug 3: join() behaves different for modified dataframes - it adds some not NA values where no data in right dataframe
import vaex, pandas as pd
ds = vaex.from_arrays(a=['a', 'a', 'c', 'd', 'e', 'f', 'f'], index=range(7))
ds_right = vaex.from_arrays(a=['A', 'B', 'F', 'G'], index=[0, 1, 5, 6])
# here we see expected NA:
ds_right_part = ds_right[ds_right['a'].str.contains('A|F')]
ds.join(ds_right_part, left_on='index', right_on='index', rsuffix='_r')
Out[29]:
a index a_r index_r
0 a 0 A 0
1 a 1 F 5
2 c 2 F 5
3 d 3 F 5
4 e 4 F 5
5 f 5 F 5
6 f 6 F 5

but for first dataframe work

**Comment by And0k** [comment]
Bug 3: join() behaves differently for modified dataframes - it adds some not NA values where no data in right dataframe
```python
import vaex, pandas as pd
ds = vaex.from_arrays(a=['a', 'a', 'c', 'd', 'e', 'f', 'f'], index=range(7))
ds_right = vaex.from_arrays(a=['A', 'B', 'F', 'G'], index=[0, 1, 5, 6])
ds_right_part = ds_right[ds_right['a'].str.contains('A|F')]
ds.join(ds_right_part, left_on='index', right_on='index', rsuffix='_r')
Out[29]:
a index a_r index_r
0 a 0 A 0
1 a 1 F 5
2 c 2 F 5
3 d 3 F 5
4 e 4 F 5
5 f 5 F 5
6 f 6 F 5
```
but here we see expected NA values:
```python
ds.join(ds_right, left_on='index', right_on='index', rsuffix='_r')
Out[31]: 
  #  a      index  a_r    index_r
  0  a          0  A      0
  1  a          1  B      1
  2  c          2  --     --
  3  d          3  --     --
  4  e          4  --     --
  5  f          5  F      5
  6  f          6  G      6```

**Comment by JovanVeljanoski** [comment]
Hi @And0k 

Thank  you for the report and for the reproducible examples. I will try to take a look at some point today and get back to you. 

Cheers!
Jovan.

**Comment by maartenbreddels** [comment]
Hi Andrey,

indeed, thanks for the report.

> First issue: why "G" in values?

The same is observed with using numpy directly:
```
a = dsj['au'].isna().values
b = dsj['au'].values
c = dsj['a'].values
np.ma.where(a, c, b)
```

This looks like horrible behaviour from numpy that we 'inherit', `np.ma.where(a, c, b)` seem to give proper behaviour.


> But why this works?

np.where seems to behave correct in this case.

The other questions I will answer separately/later.

**Comment by JovanVeljanoski** [comment]
Hi @And0k 

I think you have found exposed an issue with join when the right DataFrame is filtered. Thanks for that. We've already built a test and hope to looking into fixing this very soon. Cheers.

**Comment by JovanVeljanoski** [comment]
As for one more of your questions from the original post:

This did not work
```ds['combined'] = combined```

This did work:
```dsj['combined'] = combined```

This is expected and correct behaviour, and I believe the error message is informative. Keep in mind that vaex works with expressions. Expressions are attached to a DataFrame. You don't really have a "stand-alone" vaex Expression as you would have for example a 1-d numpy array or a pandas Series. 

So in the above case, 1st example did not work, because the definition of `combined` requires the existence of `au` in the DataFrame, which is there in `dsj` but not in `ds`. So while in principle one can "transfer" an expression from one DataFrame to another (and we do this a lot in various cases such as ML), it requires that all it's dependencies (expressions, variables etc..) are available / present in the target DataFrame as in the source DataFrame. One should be careful that the meaning/context is also unchanged, or one may get some some funky problems. 

This is because vaex Expressions are not necessarily in-memory data structures, but rather instructions of what is supposed to be calculated, when the time comes (which is why vaex can work with very large datasets easily). 

I hope this clears things up a bit.

**Comment by And0k** [comment]
Thanks, Jovan, Maarten! This all clarifies, I will keep in mind.
