### ISSUE TITLE
Inability to join when column names have a non alphanumeric character

### ISSUE THREAD

**Issue by wrosko** [vaexio/vaex#771]
I need to perform joins on many tables that have the following format: `':START, :TYPE, :END`.

This is throwing an `invalid syntax error` on the `:`. I'm wondering if there is a workaround or anything planned.

```
Traceback (most recent call last):

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))

KeyError: "Unknown variables or column: ':START_ID'"
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-51-0fba1bfe3c97>", line 4, in <module>
    allow_duplication=True)

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/dataframe.py", line 5583, in join
    index = right._index(right_on)

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/dataframe.py", line 424, in _index
    transient = self[str(expression)].transient or self.filtered or self.is_masked(expression)

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/dataframe.py", line 2010, in is_masked
    ar = self.evaluate(column, i1=0, i2=1, parallel=False)

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/dataframe.py", line 2602, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/dataframe.py", line 5397, in _evaluate_implementation
    value = scope.evaluate(expression)

  File "/home/ubuntu/miniconda3/envs/neo/lib/python3.7/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)

  File "<string>", line 1
     :START_ID
     ^
SyntaxError: invalid syntax
```

**Comment by maartenbreddels** [comment]
I was just working on similar issues here: https://github.com/vaexio/vaex/pull/768

As a workaround I suggest renaming them first?

**Comment by wrosko** [comment]
@maartenbreddels awesome! Yeah, I decided to go and rename them as a workaround for now. Should I close this issue?

**Comment by maartenbreddels** [comment]
No, lets leave it open will it's fixed.

Can I ask for the code that produces this error? How do you do the join?

**Comment by wrosko** [comment]
This code reproduces my problem. Doesn't matter if the row index is there or not, same thing happens.

```
df_1 = pd.DataFrame({':START_ID':['12','34','56','78'],
                     ':END_ID':['1','2','3','4'],})
df_2 = pd.DataFrame({':START_ID':['2','5','3','6'],
                     ':END_ID':['a','b','c','d'],})
df_1.to_csv('/home/ubuntu/df_1.csv',index=False)
df_2.to_csv('/home/ubuntu/df_2.csv',index=False)

df1 = vaex.from_csv('/home/ubuntu/df_1.csv')
df2 = vaex.from_csv('/home/ubuntu/df_2.csv')

vaex_df = vaex_df = df1.join(df2,left_on=':END_ID',right_on=':START_ID',
                             how='inner',
                             lprefix='df1_',rprefix='df2_',
                             allow_duplication=True)
```

**Comment by maartenbreddels** [comment]
Try left_on=df1[':END_ID'], that will translate it to the real column name.
Same for right_on

(from mobile phone)

**Comment by maartenbreddels** [comment]
This is fixed and released now, you can try it out with `$ pip install "vaex-core>=2.0.2"`
