### ISSUE TITLE
Can't open Arrow files

### ISSUE THREAD

**Issue by lnicola** [vaexio/vaex#786]
See https://github.com/vaexio/vaex/blob/2eaba353cc2f330933d6e9a4392b792bfad98183/packages/vaex-arrow/vaex_arrow/dataset.py#L26-L31.

It seems that `arrow` now throws an `OSError` when trying to open a non-stream file file with `open_stream`:

```
>>> pyarrow.ipc.open_stream("feat.arrow")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 146, in open_stream
    return RecordBatchStreamReader(source)
  File "/home/me/.local/lib/python3.8/site-packages/pyarrow/ipc.py", line 62, in __init__
    self._open(source)
  File "pyarrow/ipc.pxi", line 360, in pyarrow.lib._RecordBatchStreamReader._open
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: Invalid flatbuffers message.
```

**Comment by maartenbreddels** [comment]
Hi Laurențiu,

thanks, great feedback, I thought this was checked in CI, but we should test and fix that!

cheers,

Maarten

**Comment by maartenbreddels** [comment]
Would you dare to do a PR?
