### ISSUE TITLE
Arrow: large memory usage, error when opening files

### ISSUE THREAD

**Issue by lnicola** [vaexio/vaex#787]
I'm trying to open a rather large (14 GB) Arrow IPC stream file:

```
>>> import vaex
df = vaex.open("of.arrow")

# Python is now using 5-6 GB RAM

>>> df.head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 3431, in head
    return self[:min(n, len(self))]
  File "/home/me/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 4604, in __getitem__
    df = self.trim()
  File "/home/me/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 3839, in trim
    df = self if inplace else self.copy()
  File "/home/me/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 5011, in copy
    df.add_column(name, column, dtype=self._dtypes_override.get(name))
  File "/home/me/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 6019, in add_column
    super(DataFrameArrays, self).add_column(name, data, dtype=dtype)
  File "/home/me/.local/lib/python3.8/site-packages/vaex/dataframe.py", line 2928, in add_column
    raise ValueError("array is of length %s, while the length of the DataFrame is %s" % (len(ar), self.length_original()))
ValueError: array is of length 206, while the length of the DataFrame is 5627352
```

**Comment by maartenbreddels** [comment]
The memory usage is odd, you could try #517 if you feel like living on the edge. The next major version (or maybe sooner) will include this branch.

**Comment by lnicola** [comment]
Sorry for the late response. It doesn't crash, but after opening a 16 GB Feather file the memory usage of the process is 33GB. But maybe that's expected?

**Comment by maartenbreddels** [comment]
feather can have compressed data, and with the current implementation of how we read feather, it will decompress into memory. You could try saving to IPC arrow format, or hdf5 instead.

**Comment by lnicola** [comment]
For an IPC file, I get `OSError: Cannot open bar.ipc nobody knows how to read it.`.

**Comment by maartenbreddels** [comment]
With an Arrow IPC I mean it should have the `.arrow` extension.

**Comment by lnicola** [comment]
Oh, sorry for that :sweat_smile:. I can confirm that I can load both Arrow IPC file and stream formats without blowing up the memory usage.

**Comment by maartenbreddels** [comment]
No problem! Good to hear.
