### ISSUE TITLE
rename export_hdf5 and export_fits

### ISSUE THREAD

**Issue by datascienceit** [vaexio/vaex#79]
use `ds.save(file_type=hdf5/csv...)`

**Comment by maartenbreddels** [comment]
I agree that instead of having both export_hdf5 and export_fits, it should have one method. The distinction between save and export (as often seen in GUI's), is that with save you expect it to be a complete representation on disk, including the selections, virtual columns etc. With export, it signals that it is a particular representation. 
Can we settle on having:
`ds.export('nyt.csv')`
And keep `.save` for maybe the future, where it will save more than just the data/columns.

**Comment by datascienceit** [comment]
It also works, but also print this stuff:

from vaex.ml import Pipeline, lightgbm
model_path = '../models/taxi_classification.json'
pipeline_server = Pipeline()
pipeline_server.load(model_path)
results = pipeline_server.transform(test)
results




It still works, but it also prints this stuff:

ERROR:MainThread:vaex:error evaluating: lightgbm_prediction at rows 0-5
Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 682, in evaluate
    result = self[expression]
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 726, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'lightgbm_prediction_function(dropoff_hour, dropoff_dayofweek, dropoff_longitude, dropoff_latitude, trip_distance)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 682, in evaluate
    result = self[expression]
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 721, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 688, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/expression.py", line 365, in __call__
    return self.f(*args, **kwargs)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/ml/lightgbm.py", line 87, in __call__
    return np.argmax(super(LightGBMClassifier, self).__call__(*args), axis=1)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 682, in evaluate
    result = self[expression]
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 726, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'lightgbm_prediction_function(dropoff_hour, dropoff_dayofweek, dropoff_longitude, dropoff_latitude, trip_distance)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 3861, in table_part
    data_parts[name] = self.evaluate(name, i1=k1, i2=k2)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 4881, in evaluate
    value = scope.evaluate(expression)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 688, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 721, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 688, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/expression.py", line 365, in __call__
    return self.f(*args, **kwargs)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/ml/lightgbm.py", line 87, in __call__
    return np.argmax(super(LightGBMClassifier, self).__call__(*args), axis=1)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
ERROR:MainThread:vaex:error evaluating: lightgbm_prediction at rows 29222593-29222598
Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 682, in evaluate
    result = self[expression]
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 726, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'lightgbm_prediction_function(dropoff_hour, dropoff_dayofweek, dropoff_longitude, dropoff_latitude, trip_distance)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 682, in evaluate
    result = self[expression]
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 721, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 688, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/expression.py", line 365, in __call__
    return self.f(*args, **kwargs)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/ml/lightgbm.py", line 87, in __call__
    return np.argmax(super(LightGBMClassifier, self).__call__(*args), axis=1)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 682, in evaluate
    result = self[expression]
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 726, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'lightgbm_prediction_function(dropoff_hour, dropoff_dayofweek, dropoff_longitude, dropoff_latitude, trip_distance)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 3861, in table_part
    data_parts[name] = self.evaluate(name, i1=k1, i2=k2)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 4881, in evaluate
    value = scope.evaluate(expression)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 688, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 721, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/dataset.py", line 688, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/expression.py", line 365, in __call__
    return self.f(*args, **kwargs)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/vaex/ml/lightgbm.py", line 87, in __call__
    return np.argmax(super(LightGBMClassifier, self).__call__(*args), axis=1)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1004, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/Users/yonatanalexander/.virtualenvs/xdss_taxi/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
Out[70]:

**Comment by maartenbreddels** [comment]
Error is unrelated I think, and we now have [DataFrame.export](https://docs.vaex.io/en/latest/api.html#vaex.dataframe.DataFrameLocal.export)
