### ISSUE TITLE
import vaex fails with MemoryError on latest version

### ISSUE THREAD

**Issue by Code4SAFrankie** [vaexio/vaex#799]
Upgraded to the latest version using `python -m pip install --upgrade vaex`.

`Successfully installed ipyvue-1.3.2 ipyvuetify-1.4.0 nest-asyncio-1.3.3 vaex-3.0.0 vaex-arrow-0.5.1 vaex-astro-0.7.0 vaex-core-2.0.2 vaex-hdf5-0.6.0 vaex-jupyter-0.5.1 vaex-ml-0.9.0 vaex-server-0.3.1 vaex-viz-0.4.0`

When I do `import vaex` it errors with:

```
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vaex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\vaex\__init__.py", line 40, in <module>
    import vaex.dataframe
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\vaex\dataframe.py", line 28, in <module>
    import vaex.promise
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\vaex\promise.py", line 6, in <module>
    import aplus
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\aplus\__init__.py", line 452, in <module>
    import gevent
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._config import config
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 699, in <module>
    Loop().get()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 146, in get
    self.value = self.validate(self._default())
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 219, in _import_one_of
    return self._import_one(item)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\libuv\loop.py", line 51, in <module>
    ('python_queue_callback', None)])
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_ffi\loop.py", line 297, in assign_standard_callbacks
    callback = ffi.def_extern(onerror=error_func)(func)
MemoryError
```

I am using WinPython 3.7.1 on Windows 10.

**Comment by maartenbreddels** [comment]
> python -m pip install --upgrade vaex

I never do this, because pip upgrades really eagerly and can sometimes update numpy in an anaconda distribution, but looking at your second line, that does not seem to have happened. Is this all that was upgraded?

Can you downgrade vaex to 2.0.1, or 2.0.0, and which versions were you using before?

**Comment by Code4SAFrankie** [comment]
All that was recently upgraded. Haven't really had much time to play with Python. First time using vaex in years after seeing your article about it now supporting text. Can't remember whether it worked previously.

**Comment by Code4SAFrankie** [comment]
Works on `Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32` though.

**Comment by maartenbreddels** [comment]
I think it is not related to vaex, possibly you could google the error?. What you could do, is install a new conda environment, or use virtualenv using your existing Python.

**Comment by Code4SAFrankie** [comment]
I will just use 3.8. Thanks! Any tips on how to get a larger than memory .tsv file with text read in?

**Comment by maartenbreddels** [comment]
https://docs.vaex.io/en/latest/example_io.html this should help, good luck!

**Comment by maartenbreddels** [comment]
https://bitbucket.org/cffi/cffi/issues/360/memoryerror-on-travis-python-370b2-with seems like the same issue, so I do not think it is vaex related. But no real solution. You could try pip installing a different version of the libraries (gevent, cffi) to see if it fixes it.
