### ISSUE TITLE
Unable to filter using time

### ISSUE THREAD

**Issue by Nishant23** [vaexio/vaex#838]
I am trying to do the following:

```
df = pd.read_parquet("abc.parquet")
df_v = vaex.from_pandas(df)
start_time = datetime.datetime.strptime("2019-09-01 00:00:00", "%Y-%m-%d %H:%M:%S")
end_time = datetime.datetime.strptime("2019-09-01 01:00:00", "%Y-%m-%d %H:%M:%S")
df_v = df_v[(df_v['Time'] >= start_time) & (df_v['Time'] <= end_time)]
df1 = df_v.to_pandas_df()
```

but it is throwing this error:

`  File "/Users/nishant.suman/anaconda3/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 64, in <lambda>
    iterator = [loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in values]
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 54, in wrapped
    callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/execution.py", line 202, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2576, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in evaluate
    return eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 200, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2565, in _evaluate_selection_mask
    return vaex.utils.unmask_selection_mask(scope.evaluate(name))
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 169, in evaluate
    tb.print_stack()
Traceback (most recent call last):
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 200, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2565, in _evaluate_selection_mask
    return vaex.utils.unmask_selection_mask(scope.evaluate(name))
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in evaluate
    return eval(expression, expression_namespace, self)
  File "<string>", line 1
    ((Time >= 2019-09-01 00:00:00) & (Time <= 2019-09-01 01:00:00))
                    ^
SyntaxError: invalid token
ERROR:ThreadPoolExecutor-0_0:vaex.scopes:error in evaluating: '__filter__'
Traceback (most recent call last):
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 200, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2565, in _evaluate_selection_mask
    return vaex.utils.unmask_selection_mask(scope.evaluate(name))
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in evaluate
    return eval(expression, expression_namespace, self)
  File "<string>", line 1
    ((Time >= 2019-09-01 00:00:00) & (Time <= 2019-09-01 01:00:00))
                    ^
SyntaxError: invalid token
  File "/Users/nishant.suman/anaconda3/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 64, in <lambda>
    iterator = [loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in values]
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 54, in wrapped
    callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/execution.py", line 202, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2576, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 169, in evaluate
    tb.print_stack()
ERROR:MainThread:vaex.execution:error in task, flush task queue
Traceback (most recent call last):
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/execution.py", line 157, in execute_async
    cancel=lambda: self._cancel(run), unpack=True, run=run):
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 74, in map_async
    yield await value
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/tasks.py", line 292, in __wakeup
    future.result()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Users/nishant.suman/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 64, in <lambda>
    iterator = [loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in values]
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 54, in wrapped
    callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/execution.py", line 202, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2576, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in evaluate
    return eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 200, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2565, in _evaluate_selection_mask
    return vaex.utils.unmask_selection_mask(scope.evaluate(name))
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in evaluate
    return eval(expression, expression_namespace, self)
  File "<string>", line 1
    ((Time >= 2019-09-01 00:00:00) & (Time <= 2019-09-01 01:00:00))
                    ^
SyntaxError: invalid token
Traceback (most recent call last):
  File "test.py", line 256, in <module>
    df = df_v.to_pandas_df()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2807, in to_pandas_df
    return create_pdf(self.to_dict(column_names=column_names, selection=selection, parallel=parallel))
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2725, in to_dict
    return dict(list(zip(column_names, [to_array_type(chunk, array_type) for chunk in self.evaluate(column_names, selection=selection, parallel=parallel)])))
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 5316, in _evaluate_implementation
    max_stop = (len(self) if (self.filtered and filtered) else self.length_unfiltered())
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 3790, in __len__
    self. _cached_filtered_length = int(self.count())
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 730, in count
    return self._compute_agg('count', expression, binby, limits, shape, selection, delay, edges, progress, array_type=array_type)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 704, in _compute_agg
    return self._delay(delay, var)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 1463, in _delay
    self.execute()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 315, in execute
    just_run(self.execute_async())
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/nest_asyncio.py", line 59, in run_until_complete
    return f.result()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/tasks.py", line 225, in __step
    result = coro.throw(exc)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 320, in execute_async
    await self.executor.execute_async()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/execution.py", line 157, in execute_async
    cancel=lambda: self._cancel(run), unpack=True, run=run):
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 74, in map_async
    yield await value
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/tasks.py", line 292, in __wakeup
    future.result()
  File "/Users/nishant.suman/anaconda3/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Users/nishant.suman/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 64, in <lambda>
    iterator = [loop.run_in_executor(self, lambda value=value: wrapped(value)) for value in values]
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/multithreading.py", line 54, in wrapped
    callable(self.local.index, *args, **kwargs, **kwargs_extra)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/execution.py", line 202, in process_part
    filter_mask = df.evaluate_selection_mask(None, i1=i1, i2=i2, cache=True)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2576, in evaluate_selection_mask
    mask_global = scope_global.evaluate(FILTER_SELECTION_NAME)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in evaluate
    return eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 200, in __getitem__
    mask_values = selection.evaluate(self.df, variable, self.i1, self.i2, self.filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/selections.py", line 131, in evaluate
    result = df._evaluate_selection_mask(self.boolean_expression, i1, i2, filter_mask=filter_mask)
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2565, in _evaluate_selection_mask
    return vaex.utils.unmask_selection_mask(scope.evaluate(name))
  File "/Users/nishant.suman/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 166, in evaluate
    return eval(expression, expression_namespace, self)
  File "<string>", line 1
    ((Time >= 2019-09-01 00:00:00) & (Time <= 2019-09-01 01:00:00))
                    ^
SyntaxError: invalid token
`

**Comment by JovanVeljanoski** [comment]
Hi @Nishant23 

Python datetime is currently not supported by vaex. Please make sure that your datetime columns are of type `np.datetime64`.  Then you can filter as usual, assuming the column and the limiting value are `np.datetime64`. 

I hope this helps.
J.

**Comment by Nishant23** [comment]
Thanks @JovanVeljanoski , it works fine with `np.datetime64`
