### ISSUE TITLE
ValueError: Unknown expression type: <class '_ast.NameConstant'>

### ISSUE THREAD

**Issue by xdssio** [vaexio/vaex#846]
df.x.str.replace(..., regex=False) Works fine.
df.x.str.replace(..., regex=True) seems to work, but crashes when continue to work with the virtual column.

Reproduce: 
```
import vaex
text = ['Something', 'very pretty', 'is coming', 'our', 'way.']
df = vaex.from_arrays(text=text)

# works 
(df.text.str.replace('.','')==df.text.str.replace('.','')).astype(int).sum()

# crashes
(df.text.str.replace('[.]','',regex=True)==df.text.str.replace('[.]','', regex=True)).astype(int).sum()
```

**Comment by xdssio** [comment]
```
Traceback (most recent call last):
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-158-65b41fbb4f0f>", line 9, in <module>
    (df.text.str.replace('[.]','',regex=True)==df.text.str.replace('[.]','', regex=True)).astype(int).sum()
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/expression.py", line 518, in sum
    return self.ds.sum(**kwargs)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/dataframe.py", line 867, in sum
    return self._compute_agg('sum', expression, binby, limits, shape, selection, delay, edges, progress, array_type=array_type)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/dataframe.py", line 621, in _compute_agg
    self.validate_expression(expression)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/dataframe.py", line 2887, in validate_expression
    return vaex.expresso.validate_expression(expression, vars, funcs)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/expresso.py", line 79, in validate_expression
    function_set, names)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/expresso.py", line 110, in validate_expression
    validate_expression(arg, variable_set, function_set, names)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/expresso.py", line 110, in validate_expression
    validate_expression(arg, variable_set, function_set, names)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/expresso.py", line 112, in validate_expression
    validate_expression(arg, variable_set, function_set, names)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/expresso.py", line 121, in validate_expression
    validate_expression(expr.value, variable_set, function_set, names)
  File "/Users/yonatanalexander/.virtualenvs/xvaex/lib/python3.7/site-packages/vaex/expresso.py", line 131, in validate_expression
    raise ValueError("Unknown expression type: %r" % type(expr))
ValueError: Unknown expression type: <class '_ast.NameConstant'>
```

**Comment by maartenbreddels** [comment]
Thanks for giving a reproducible example!
