### ISSUE TITLE
ERROR:MainThread:vaex:issue loading reader

### ISSUE THREAD

**Issue by vuqnguyen90** [vaexio/vaex#855]
Hi all, 
This is my first time to try out Vaex. I plan to use Vaex for big data instead of Pandas. 
After I successfully installed Vaex by using Conda, I tried to load my data from the csv files as shown below: 

import vaex
PT_dir=r'C:\Users\vu.nguyen.SILIXA\Documents\Python\SlowStrain_MSE_PumpData_PlotlyVersion\PT_Dev.csv'
PT_df=vaex.from_csv(PT_dir)

Then I ran into this error. Would you please help me to resolve this? 

Thanks, 

ERROR:MainThread:vaex:issue loading reader
Traceback (most recent call last):
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\vaex\__init__.py", line 720, in <module>
    add_namespace = entry.load()
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    self.require(*args, **kwargs)
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\pkg_resources\__init__.py", line 2468, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\pkg_resources\__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pyarrow 0.11.1 (c:\users\vu.nguyen.silixa\appdata\local\continuum\anaconda_springboard\lib\site-packages), Requirement.parse('pyarrow>=0.15'))

**Comment by JovanVeljanoski** [comment]
Hm.. could be some kind of installation issue?

Can you read your data with pandas via `pandas.read_csv()`. If you can, the same very same command should work with vaex: `veax.read_csv` or `vaex.from_csv` (they are the same). If you can read with pandas but not with vaex, it might be an installation issue.

**Comment by vuqnguyen90** [comment]
Thank you so much for replying to me. I just re-installed Vaex and it's working for me now. 

Thanks
