### ISSUE TITLE
Installation and Timestamp Issues

### ISSUE THREAD

**Issue by vuqnguyen90** [vaexio/vaex#869]
Hi, 
I'm extremely new to Vaex. I am experiencing several issues with Vaex as I want to switch from Pandas to Vaex. 

**# Issue 1:  Installation** 
Even though I have successfully installed Vaex (Installed multiple times either using PIP or Conda), I will get the error message when I first ran 'import vaex' as below. However, If I ran the same command again, it does not show any error message. So I tried to read files in, it appears working. 

ERROR:MainThread:vaex:issue loading reader
Traceback (most recent call last):
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\vaex\__init__.py", line 720, in <module>
    add_namespace = entry.load()
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    self.require(*args, **kwargs)
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\pkg_resources\__init__.py", line 2468, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\vu.nguyen.SILIXA\AppData\Local\Continuum\Anaconda_Springboard\lib\site-packages\pkg_resources\__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pyarrow 0.11.1 (c:\users\vu.nguyen.silixa\appdata\local\continuum\anaconda_springboard\lib\site-packages), Requirement.parse('pyarrow>=0.15'))

**# Issue 2:  Pivot Pandas tables and Timestamp**
I want to pivot the table in Vaex as I could do with Pandas. So the dataframe will look like this: 
data.head()
Out[4]: 
Time      2020-01-30 13:55:10  ...  2020-01-30 17:15:00
Depth                          ...                     
-1385.77                 0.47  ...                 0.91
-1382.42                 0.47  ...                 0.87
-1379.07                 0.47  ...                 0.65
-1375.72                 0.42  ...                 0.42
-1372.37                 0.43  ...                 0.27

[5 rows x 1200 columns]

However, I still haven't figured it out how to do it in Vaexyet. I tried to pivot the table with Pandas first, then convert Pandas dataframe to Vaex by using 'from_pandas' but then I ran into the error below: 

Giving up column 2020-01-31 10:39:30, error: TypeError("'Timestamp' object is not subscriptable")
could not convert column 2020-01-31 10:39:40, error: TypeError("'Timestamp' object is not subscriptable"), will try to convert it to string

I would really appreciate that you can help me out with this. 

Thanks

**Comment by JovanVeljanoski** [comment]
Hi, 

Can you please try to install vaex in new, clean environment ? Often when things get too entangled in an environment it is easier to just start fresh, rather than figure out which combination of dependencies and versions is causing the problem etc.. 

As for pivot, Vaex does not support this at the moment and it is not clear whether it will be supported in the future. Vaex is designed for working with very long tables, i.e. billions of rows, and pivoting that is simply not efficient.

As for timestamps, please (at least for now) use numpy's `np.datetime64` or `np.timedelta64` format.

**Comment by vuqnguyen90** [comment]
> Hi,
> 
> Can you please try to install vaex in new, clean environment ? Often when things get too entangled in an environment it is easier to just start fresh, rather than figure out which combination of dependencies and versions is causing the problem etc..
> 
> As for pivot, Vaex does not support this at the moment and it is not clear whether it will be supported in the future. Vaex is designed for working with very long tables, i.e. billions of rows, and pivoting that is simply not efficient. Assuming that your tables are not very large, a proposed workflow would be _vaex -> pandas (-> vaex, optionally)_. Or if you do have big data _bigdata -> vaex -> aggregate -> pandas_ (-> vaex, optionally)_.
> 
> As for timestamps, please (at least for now) use numpy's `np.datetime64` or `np.timedelta64` format.

Hi Jovan, 
Thank you so much for quick reply. 

I will try to reinstall vaex in a new environment as you suggested. Does that mean I have to call that virtual environment every time I want to use Vaex? 

So, if pivot is not a current option for vaex, how do you advise me to create a plot that needed to be in pivot table? Do you think it's better idea to pivot it first in Pandas then convert it to Vaex? 

Can you elaborate more about using np.datetime64? I loaded thoundsands of text files to dictionary first and then converted to Dataframe. The timestamp format should be in datetime already. So, how do we use np.datetime64? 

Thanks, 
Vu

**Comment by maartenbreddels** [comment]
> think it's better idea to pivot it first in Pandas then convert it to Vaex

Yes, I consider that good practice. If we Vaex wraps pandas, and provides users a convenient way, I think users expect Vaex to pivot large tables efficiently. Now it is more clear who's responsible.

@JovanVeljanoski I think we should make it clear from the docs that we advice/recommend using pandas, maybe users want to 'switch', I think that's not something we should advocate or expect from users. It's like 'switching' from a truck to a race car. You still need both for their different purposes.
