### ISSUE TITLE
Invalid token error with column names containing some special characters

### ISSUE THREAD

**Issue by ag-tcm** [vaexio/vaex#894]
Summary: Opening an arrow file with column names that contain some special characters ("." [period], "," [comma], "*" [star]) results in an Invalid Token error. For example I have a column named "ZSCORE_5_2.0_chg_10" which throws the error.

Code:
import vaex as vx
path = 'myarrowfile.arrow'
dfv = vx.open(path)

Error:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\vaex\dataframe.py", line 3580, in table_part
    values[name] = df.evaluate(name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\vaex\dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\vaex\dataframe.py", line 5352, in _evaluate_implementation
    dtypes[expression] = df.data_type(expression, internal=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\vaex\dataframe.py", line 1998, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\vaex\dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\vaex\dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\vaex\scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1
    ZSCORE_5_2.0_chg_10
                ^
SyntaxError: invalid token

Version:
vaex==3.0.0
vaex-arrow==0.5.1
vaex-astro==0.7.0
vaex-core==2.0.3
vaex-hdf5==0.6.0
vaex-jupyter==0.5.2
vaex-ml==0.9.0
vaex-server==0.3.1
vaex-viz==0.4.0

**Comment by maartenbreddels** [comment]
Thanks for reporting, it might be fixed in master, but in any case I'd like to test this.
