### ISSUE TITLE
Round a Vaex DataFrame to a variable number of decimal places

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#939]
Hi,

### in Pandas
````
x = np.arange(4)
y = np.array([10.687, 20.779, 30.917, 40.538])
z = np.array(['x', 'y', 'z', 'f'])
df_panda = pd.DataFrame({'x':x, 'y':y, 'z':z})
df = df_panda.groupby(['z']).agg({'y': 'sum'}).round(2)

````
### Output

````
          y
z       
f  40.54
x  10.69
y  20.78
z  30.92
````
### in vaex

````
df_vaex = vaex.from_arrays(x=x, y=y, z=z)
df = df_numpy.groupby(['z']).agg({'y': 'sum'}).round(2)

````
### Output
````
Traceback (most recent call last):
  File "D:/dash-120million-taxi-app/test.py", line 119, in <module>
    trn_df = df_numpy.groupby(['z']).agg({'y': 'sum'}).round(2)
  File "D:\dash-120million-taxi-app\venv\lib\site-packages\vaex\dataframe.py", line 239, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrameArrays' object has no attribute 'round'

````

**Comment by JovanVeljanoski** [comment]
Hey, 

We've just made a PR #940  that will allow for rounding of numeric columns/expressions. It will be available in the next release. 

Once that is is, it should be fairly easy to make a convenience method on the dataframe level. I might do this once I have a chance, unless someone else is willing to contribute. 

Cheers, and thanks for the issue!
J.
