### ISSUE TITLE
Reading and plotting complex numbers

### ISSUE THREAD

**Issue by deepaliagarwal211** [vaexio/vaex#941]
Hi, I am trying to read hdf5 file(size~5GB) having complex numbers in columns. I want to plot a histogram with these numbers. So used this command:

**counts_x = df.count(binby=x, limits=[-10, 10], shape=64)
plt.plot(np.linspace(-10, 10, 64),counts_x)**

It's showing error:

**Could not find a class (BinnerScalar_complex128), seems complex128 is not supported**

I guess, with Vaex I would not be able to analyse complex numbers data. Please let me know if there is any solution.

**Comment by JovanVeljanoski** [comment]
Can you please give us an example on how you see this working? Or an example with other packages using smaller data sizes?

Cheers!

**Comment by poleguy** [comment]
I'm also trying vaex for the first time, and my very first step was to load in complex data and hit on this issue. Here is a minimal reproducible test case:

If you care about why I want this, I'm doing RF engineering work and the IQ samples tend to be complex. It may be possible to work around this, but pairs of 64bit real and imaginary samples is a pretty common representation.

import numpy as np
import vaex as vx
data = np.zeros(0).astype(np.complex128)
d = {"iq":data}
ds = vx.from_arrays(**d)
    
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    ds = vx.from_arrays(**d)
  File "/home/.../cenv/lib/python3.6/site-packages/vaex/__init__.py", line 197, in from_arrays
    dataset.add_column(name, array)
  File "/home/.../cenv/lib/python3.6/site-packages/vaex/dataset.py", line 5230, in add_column
    assert _is_array_type_ok(data), "dtype not supported: %r, %r" % (data.dtype, data.dtype.type)
AssertionError: dtype not supported: dtype('complex128'), <class 'numpy.complex128'>

**Comment by maartenbreddels** [comment]
We could implement basic support for complex, like we could allow them to exist in a dataframe, and wrap some functions from numpy. Would you feel like contributing to Vaex?
