### ISSUE TITLE
Can't install vaex on Ubuntu 18.04 and Python 3.7.5, getting LLVM errors

### ISSUE THREAD

**Issue by stevesolun** [vaexio/vaex#947]
Trying to install using pip3:

`sudo pip3 install vaex`

Getting the following error:

```
got version from file /tmp/pip-build-4ejf0kw2/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-4ejf0kw2/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
```

Here are all llvm I have:

```
libllvm-10-ocaml-dev/unknown 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64
libllvm-7-ocaml-dev/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
libllvm-8-ocaml-dev/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
libllvm-9-ocaml-dev/bionic-updates,bionic-security 1:9-2~ubuntu18.04.2 amd64
libllvm10/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed,automatic]
libllvm3.9/bionic 1:3.9.1-19ubuntu1 amd64
libllvm3.9-dbg/bionic 1:3.9.1-19ubuntu1 amd64
libllvm4.0/bionic 1:4.0.1-10 amd64
libllvm4.0-dbg/bionic 1:4.0.1-10 amd64
libllvm5.0/bionic 1:5.0.1-4 amd64
libllvm5.0-dbg/bionic 1:5.0.1-4 amd64
libllvm6.0/bionic,now 1:6.0-1ubuntu2 amd64 [installed,automatic]
libllvm6.0-dbg/bionic 1:6.0-1ubuntu2 amd64
libllvm7/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
libllvm8/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
libllvm9/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
libstd-rust-1.24/bionic 1.24.1+dfsg1+llvm-0ubuntu2 amd64
libstd-rust-1.25/bionic-updates,bionic-security 1.25.0+dfsg1+llvm-0ubuntu1 amd64
libstd-rust-1.28/bionic-updates,bionic-security 1.28.0+dfsg1+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.30/bionic-updates,bionic-security 1.30.0+dfsg1+llvm-2ubuntu1~18.04.1 amd64
libstd-rust-1.31/bionic-updates,bionic-security 1.31.0+dfsg1+llvm-2ubuntu1~18.04.1 amd64
libstd-rust-1.32/bionic-updates,bionic-security 1.32.0+dfsg1+llvm-1ubuntu1~18.04.1 amd64
libstd-rust-1.34/bionic-updates,bionic-security 1.34.1+dfsg2+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.35/bionic-updates,bionic-security 1.35.0+dfsg0.1+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.36/bionic-updates,bionic-security 1.36.0+dfsg1+llvm-2ubuntu1~18.04.1 amd64
libstd-rust-1.37/bionic-updates,bionic-security 1.37.0+dfsg1+llvm-1ubuntu1~18.04.1 amd64
libstd-rust-1.39/bionic-updates,bionic-security 1.39.0+dfsg1+llvm-3ubuntu1~18.04.1 amd64
libstd-rust-1.41/bionic-updates,bionic-security 1.41.0+dfsg1+llvm-0ubuntu1~18.04.1 amd64
libstd-rust-1.43/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 amd64
libstd-rust-dev/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 amd64
libstd-rust-dev-wasm32-cross/bionic-updates,bionic-security 1.41.0+dfsg1+llvm-0ubuntu1~18.04.1 all
llvm/bionic-updates 1:6.0-41~exp5~ubuntu1 amd64
llvm-10/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed]
llvm-10-dev/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed]
llvm-10-doc/unknown 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 all
llvm-10-examples/unknown 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 all
llvm-10-runtime/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed,automatic]
llvm-10-tools/unknown,now 1:10.0.1~++20200809072545+ef32c611aa2-1~exp1~20200809173142.193 amd64 [installed,automatic]
llvm-3.7-doc/bionic 1:3.7.1-5ubuntu3 all
llvm-3.9/bionic 1:3.9.1-19ubuntu1 amd64
llvm-3.9-dev/bionic 1:3.9.1-19ubuntu1 amd64
llvm-3.9-doc/bionic 1:3.9.1-19ubuntu1 all
llvm-3.9-examples/bionic 1:3.9.1-19ubuntu1 all
llvm-3.9-runtime/bionic 1:3.9.1-19ubuntu1 amd64
llvm-3.9-tools/bionic 1:3.9.1-19ubuntu1 amd64
llvm-4.0/bionic 1:4.0.1-10 amd64
llvm-4.0-dev/bionic 1:4.0.1-10 amd64
llvm-4.0-doc/bionic 1:4.0.1-10 all
llvm-4.0-examples/bionic 1:4.0.1-10 all
llvm-4.0-runtime/bionic 1:4.0.1-10 amd64
llvm-4.0-tools/bionic 1:4.0.1-10 amd64
llvm-5.0/bionic 1:5.0.1-4 amd64
llvm-5.0-dev/bionic 1:5.0.1-4 amd64
llvm-5.0-doc/bionic 1:5.0.1-4 all
llvm-5.0-examples/bionic 1:5.0.1-4 all
llvm-5.0-runtime/bionic 1:5.0.1-4 amd64
llvm-5.0-tools/bionic 1:5.0.1-4 amd64
llvm-6.0/bionic 1:6.0-1ubuntu2 amd64
llvm-6.0-dev/bionic 1:6.0-1ubuntu2 amd64
llvm-6.0-doc/bionic 1:6.0-1ubuntu2 all
llvm-6.0-examples/bionic 1:6.0-1ubuntu2 all
llvm-6.0-runtime/bionic 1:6.0-1ubuntu2 amd64
llvm-6.0-tools/bionic 1:6.0-1ubuntu2 amd64
llvm-7/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
llvm-7-dev/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
llvm-7-doc/bionic-updates,now 1:7-3~ubuntu0.18.04.1 all [installed]
llvm-7-examples/bionic-updates,now 1:7-3~ubuntu0.18.04.1 all [installed]
llvm-7-runtime/bionic-updates,now 1:7-3~ubuntu0.18.04.1 amd64 [installed]
llvm-7-tools/bionic-updates 1:7-3~ubuntu0.18.04.1 amd64
llvm-8/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-8-dev/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-8-doc/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 all
llvm-8-examples/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 all
llvm-8-runtime/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-8-tools/bionic-updates,bionic-security 1:8-3~ubuntu18.04.2 amd64
llvm-9/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-9-dev/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-9-doc/bionic-updates,bionic-security 1:9-2~ubuntu18.04.2 all
llvm-9-examples/bionic-updates,bionic-security 1:9-2~ubuntu18.04.2 all
llvm-9-runtime/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-9-tools/bionic-updates,bionic-security,now 1:9-2~ubuntu18.04.2 amd64 [installed,automatic]
llvm-dev/bionic-updates 1:6.0-41~exp5~ubuntu1 amd64
llvm-runtime/bionic-updates 1:6.0-41~exp5~ubuntu1 amd64
llvmlite-doc/bionic 0.19.0-2 all
python-llvmlite/bionic 0.19.0-2 amd64
python3-llvmlite/bionic 0.19.0-2 amd64
rust-doc/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rust-gdb/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rust-lldb/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rust-src/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 all
rustc/bionic-updates,bionic-security 1.43.0+dfsg1+llvm-1~exp1ubuntu2~18.04.1 amd64
```

Please guide me how can I solve it.

**Comment by maartenbreddels** [comment]
Hi,

Please don't use you system pip: https://stackoverflow.com/questions/61452582/why-is-using-sudo-pip-a-bad-idea

Use virtualenv or conda instead. Note that this is an llvmlite install issue (not vaex), which needs to be installed because vaex depends on vaex-ml. If you don't need it you could instead choose to install vaex-core, vaex-hdf5, etc.

Hope this helps.

Cheers,

Maarten

**Comment by stevesolun** [comment]
Thanks a lot @maartenbreddels, just before I will post the issue on their git, do you know what can be a possible solution for llvm?

**Comment by maartenbreddels** [comment]
Try installing llvmlite first like this: https://github.com/numba/llvmlite/issues/531#issuecomment-623689362

**Comment by stevesolun** [comment]
@maartenbreddels already done. I am getting the above error even when I am installing numba.

**Comment by maartenbreddels** [comment]
Probably have to install an older version of numba. I always do
```
pip install numba=x
```
Where x is really x, so pip spits out all the version numbers. They iteratively find a version number that works.

**Comment by maartenbreddels** [comment]
Or go through the setup.py history in the numba repo, whichever you deep faster.

**Comment by esc** [comment]
I believe you can close this as it is an issue installing `llvmlite` as the pip version is outdated. `llvmlite` 0.34.0 needs at least pip 19.0 to install the binary (manylinux2010) wheels.

**Comment by stevesolun** [comment]
The solution was to delete manually the llvm package from dist-packages (all versions), install pip (latest version) not pip3.
Right after this I have installed llvmlite 0.33.0 and numba 0.49.1.

Reinstalled vaex and who reinstalled llvmlite 0.34.0 and numba 0.51 and vaex installation successfully finished!
