### ISSUE TITLE
Running vaex.example() results in http 403

### ISSUE THREAD

**Issue by javadba** [vaexio/vaex#950]
Running   

```vaex.example()```

is resulting in a 403

17:25:41/~ $python -c "import vaex; df = vaex.example(); df.describe()"
Downloading http://vaex.astro.rug.nl/data/helmi-dezeeuw-2000-10p.hdf5 to /Users/steve/.vaex/data/helmi-dezeeuw-2000-10p.hdf5
--2020-08-29 17:25:57--  http://vaex.astro.rug.nl/data/helmi-dezeeuw-2000-10p.hdf5
Resolving vaex.astro.rug.nl (vaex.astro.rug.nl)... 129.125.6.3
Connecting to vaex.astro.rug.nl (vaex.astro.rug.nl)|129.125.6.3|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://vaex.io/data/helmi-dezeeuw-2000-10p.hdf5 [following]
--2020-08-29 17:25:58--  https://vaex.io/data/helmi-dezeeuw-2000-10p.hdf5
Resolving vaex.io (vaex.io)... 172.67.69.63, 104.26.1.195, 104.26.0.195
Connecting to vaex.io (vaex.io)|172.67.69.63|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-29 17:25:58 ERROR 404: Not Found.

wget failed, using urlretrieve
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/steve/miniconda3/lib/python3.7/site-packages/vaex/__init__.py", line 575, in example
    return vaex.datasets.helmi_de_zeeuw_10percent.fetch()
  File "/Users/steve/miniconda3/lib/python3.7/site-packages/vaex/datasets.py", line 47, in fetch
    self.download(force=force_download)
  File "/Users/steve/miniconda3/lib/python3.7/site-packages/vaex/datasets.py", line 41, in download
    self.download_urlretrieve()
  File "/Users/steve/miniconda3/lib/python3.7/site-packages/vaex/datasets.py", line 44, in download_urlretrieve
    urlretrieve(self.url, self.filename)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/steve/miniconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Software information**
 - Vaex version   1.0.0-beta.6
 - Vaex was installed via:  conda-forge 
 - OS:  macOS catalina

**Comment by JovanVeljanoski** [comment]
Hi, 

You seem to be running a _very_ old version of vaex. Please upgrade to the latest version.

The latest release of vaex is:
vaex: 3.0.0
vaex-core: 2.0.3

I hope this helps. 
J.

**Comment by javadba** [comment]
Thx that fixed it!   Note I had just done the conda installation per instructions yesterday so they are pointing to a v old version.
