### ISSUE TITLE
[BUG-REPORT] vaex-astro and vaex-viz 

### ISSUE THREAD

**Issue by sheridp** [vaexio/vaex#960]
Observed on Python 3.8.5 & 3.7.5
```
>>> vaex.__version__
{'vaex': '3.0.0', 'vaex-core': '2.0.3', 'vaex-hdf5': '0.6.0', 'vaex-server': '0.3.1', 'vaex-jupyter': '0.5.2', 'vaex-ml': '0.9.0', 'vaex-arrow': '0.5.1'}
```
**Steps:**

`pipenv install vaex`
`pipenv shell`
`python`

```
>>> import vaex
ERROR:MainThread:vaex:issue loading plot
Traceback (most recent call last):
  File "/home/psheridan/.local/share/virtualenvs/Traces-6Q4U88k-/lib64/python3.8/site-packages/vaex/__init__.py", line 789, in <module>
    add_namespace = entry.load()
  File "/home/psheridan/.local/share/virtualenvs/Traces-6Q4U88k-/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/home/psheridan/.local/share/virtualenvs/Traces-6Q4U88k-/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.viz'
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "/home/psheridan/.local/share/virtualenvs/Traces-6Q4U88k-/lib64/python3.8/site-packages/vaex/__init__.py", line 789, in <module>
    add_namespace = entry.load()
  File "/home/psheridan/.local/share/virtualenvs/Traces-6Q4U88k-/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/home/psheridan/.local/share/virtualenvs/Traces-6Q4U88k-/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.astro'
```

If I `pip uninstall vaex-astro vaex-viz` then the module loads correctly.

**Comment by sheridp** [comment]
It's odd because vaex/__init__.py", line 789 is wrapped in an try...except Exception

**Comment by sheridp** [comment]
Sorry, this was simply printing a warning that included the stacktrace; in jupyter notebook I thought that it had actually thrown the exception.  Still probably shouldn't be printing a warning.

**Comment by arunpersaud** [comment]
I'm getting the same error with vaex on my linux desktop:

>>> vaex.__version__
{'vaex': '4.16.0', 'vaex-core': '4.16.1', 'vaex-hdf5': '0.14.1', 'vaex-server': '0.8.1', 'vaex-jupyter': '0.8.1', 'vaex-ml': '0.18.1'}


05/25/23 16:10:20] ERROR    issue loading plot                               __init__.py:818
                             Traceback (most recent call last):                              
                               File                                                          
                             "/usr/lib64/python3.10/site-packages/vaex/__init                
                             __.py", line 815, in <module>                                   
                                 add_namespace = entry.load()                                
                               File                                                          
                             "/usr/lib/python3.10/site-packages/importlib_met                
                             adata/__init__.py", line 210, in load                           
                                 module =                                                    
                             import_module(match.group('module'))                            
                               File                                                          
                             "/usr/lib64/python3.10/importlib/__init__.py",                  
                             line 126, in import_module                                      
                                 return _bootstrap._gcd_import(name[level:],                 
                             package, level)                                                 
                               File "<frozen importlib._bootstrap>", line                    
                             1050, in _gcd_import                                            
                               File "<frozen importlib._bootstrap>", line                    
                             1027, in _find_and_load                                         
                               File "<frozen importlib._bootstrap>", line                    
                             992, in _find_and_load_unlocked                                 
                               File "<frozen importlib._bootstrap>", line                    
                             241, in _call_with_frames_removed                               
                               File "<frozen importlib._bootstrap>", line                    
                             1050, in _gcd_import                                            
                               File "<frozen importlib._bootstrap>", line                    
                             1027, in _find_and_load                                         
                               File "<frozen importlib._bootstrap>", line                    
                             1004, in _find_and_load_unlocked                                
                             ModuleNotFoundError: No module named 'vaex.viz'                 
                    ERROR    issue loading astro                              __init__.py:818
                             Traceback (most recent call last):                              
                               File                                                          
                             "/usr/lib64/python3.10/site-packages/vaex/__init                
                             __.py", line 815, in <module>                                   
                                 add_namespace = entry.load()                                
                               File                                                          
                             "/usr/lib/python3.10/site-packages/importlib_met                
                             adata/__init__.py", line 210, in load                           
                                 module =                                                    
                             import_module(match.group('module'))                            
                               File                                                          
                             "/usr/lib64/python3.10/importlib/__init__.py",                  
                             line 126, in import_module                                      
                                 return _bootstrap._gcd_import(name[level:],                 
                             package, level)                                                 
                               File "<frozen importlib._bootstrap>", line                    
                             1050, in _gcd_import                                            
                               File "<frozen importlib._bootstrap>", line                    
                             1027, in _find_and_load                                         
                               File "<frozen importlib._bootstrap>", line                    
                             992, in _find_and_load_unlocked                                 
                               File "<frozen importlib._bootstrap>", line                    
                             241, in _call_with_frames_removed                               
                               File "<frozen importlib._bootstrap>", line                    
                             1050, in _gcd_import                                            
                               File "<frozen importlib._bootstrap>", line                    
                             1027, in _find_and_load                                         
                               File "<frozen importlib._bootstrap>", line                    
                             1004, in _find_and_load_unlocked                                
                             ModuleNotFoundError: No module named                            
                             'vaex.astro'     

uninstalling as suggested above seems to solve this.

**Comment by arunpersaud** [comment]
Just to follow up: adding links as described in #1713 fixed this for me.
