### ISSUE TITLE
[FEATURE-REQUEST]

### ISSUE THREAD

**Issue by balbinot** [vaexio/vaex#969]
I modified the vaex-astro transformations.py package to remove the kapteyn package dependency (PR #183). At that point I introduced a matrix called comat that could be accessed/modified via

vaex.astro.transformations.comat['gd1'] = gd1.R

On more recent vaex versions this is no longer accessible that way, perhaps due to the DataFrameAcessor refactoring. Which is beyond my capabilities to understand right now. This feature was very useful for making transformations between Equatorial coordinates and e.g. a  coordinate system aligned with a stellar stream to enable complex on-sky geometric selections.
Do you have any suggestions on how I could access the comat dictionary now?

**Comment by JovanVeljanoski** [comment]
Hi @balbinot 

Would this help?

```
from vaex.astro import transformations

print(transformations.comat)
```

**Comment by balbinot** [comment]
Hi,

thanks that works for accessing it. But then I ran into the following error when trying to use the matrix

```
In [31]: transformations.comat['test'] = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])                                                                                                                                                                      
In [32]: df.add_virtual_columns_celestial(long_in='ra', lat_in='dec', long_out='phi1', lat_out='phi2', _matrix='test')   

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 3580, in table_part
    values[name] = df.evaluate(name)
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 5352, in _evaluate_implementation
    dtypes[expression] = df.data_type(expression, internal=False)
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 1998, in data_type
    data = self.evaluate(expression, 0, 1, filtered=True, internal=True, parallel=False)
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/dataframe.py", line 5427, in _evaluate_implementation
    value = scope.evaluate(expression)
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 139, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/balbinot/anaconda3/lib/python3.7/site-packages/vaex/scopes.py", line 103, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
NameError: name 'pi' is not define
```

**Comment by maartenbreddels** [comment]
Ah, that sounds like a bug. A workaround would be
`df.add_variable('pi', math.pi)`, but this should be done automatically.
