### ISSUE TITLE
Error during vaex import

### ISSUE THREAD

**Issue by aclifton314** [vaexio/vaex#982]
**Description**
`vaex` throws the following error on import:
```python
ERROR:MainThread:vaex:issue loading plot
Traceback (most recent call last):
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/__init__.py", line 789, in <module>
    add_namespace = entry.load()
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/viz/mpl.py", line 9, in <module>
    import vaex.image
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/image.py", line 2, in <module>
    import PIL.Image
  File "/path/to/anaconda3/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
ERROR:MainThread:vaex:issue loading reader
Traceback (most recent call last):
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/__init__.py", line 789, in <module>
    add_namespace = entry.load()
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/vaex_arrow/opener.py", line 1, in <module>
    import vaex.file
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/file/__init__.py", line 11, in <module>
    import vaex.file.other
  File "/path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/file/other.py", line 11, in <module>
    import astropy.table
  File "/path/to/anaconda3/lib/python3.8/site-packages/astropy/__init__.py", line 368, in <module>
    _initialize_astropy()
  File "/path/to/anaconda3/lib/python3.8/site-packages/astropy/__init__.py", line 263, in _initialize_astropy
    from .utils import _compiler
ImportError: cannot import name '_compiler'
```

**Software information**
 - Vaex version: 3.0.0
 - Vaex was installed via: pip 
 - OS: RHEL Server 7.7 Maipo (using 3 GPUs).
- Python: 3.6.7

Any ideas about how to correct it? Thanks in advance for your help!

**Comment by JovanVeljanoski** [comment]
I am not sure about this one.. maybe @maartenbreddels can provide more insight.

But looking at the error messages, I see references to both anaconda distribution (and python3.8) and and what looks like venvs and python 3.6. There is some mixup going on there..

If you are already using (ana)conda, maybe you can try installing vaex via conda-forge in a clean environment?

**Comment by aclifton314** [comment]
@JovanVeljanoski good eye. I went through and fixed the python version mixing. Here is the error now:
```python
ERROR:MainThread:vaex:issue loading plot
Traceback (most recent call last):
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/__init__.py", line 789, in <module>
    add_namespace = entry.load()
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/viz/mpl.py", line 9, in <module>
    import vaex.image
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/image.py", line 12, in <module>
    import matplotlib.colors
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 205, in <module>
    _check_versions()
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 199, in _check_versions
    module = importlib.import_module(modname)
  File "/cm/local/apps/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'kiwisolver'
ERROR:MainThread:vaex:issue loading reader
Traceback (most recent call last):
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/__init__.py", line 789, in <module>
    add_namespace = entry.load()
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/vaex_arrow/opener.py", line 1, in <module>
    import vaex.file
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/file/__init__.py", line 17, in <module>
    import vaex.hdf5.dataset
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/vaex/hdf5/dataset.py", line 33, in <module>
    import h5py
  File /path/to/venvs/my-venv/lib/python3.6/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: cannot import name '_errors'
```

**Comment by maartenbreddels** [comment]
Hi.

Both error do not seem to be vaex related, but matplitlib and h5py. How do you do the installation?

cheers,

Maarten

**Comment by aclifton314** [comment]
If I remember correctly, I installed anaconda 2020.07 first then created the virtual environment with `python -m venv ~/venvs/my-venv`

**Comment by maartenbreddels** [comment]
I don't think one should do that. If you use conda, create an environment
with conda to avoid issues like this. Hope that helps! Cheers

(from mobile phone)

**Comment by aclifton314** [comment]
Ok thanks. I'll give that a try.
